//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Absences
    {
        public System.Guid ID { get; set; }
        public int HID { get; set; }
        public int Type { get; set; }
        public int EmpID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<double> Hours { get; set; }
        public Nullable<double> Days { get; set; }
        public Nullable<System.DateTime> StartDateActual { get; set; }
        public Nullable<System.DateTime> EndDateActual { get; set; }
        public Nullable<double> HoursActual { get; set; }
        public Nullable<double> DaysActual { get; set; }
        public Nullable<double> Amount { get; set; }
        public string Currency { get; set; }
        public Nullable<double> AmountFC { get; set; }
        public Nullable<double> AmountActual { get; set; }
        public string CurrencyActual { get; set; }
        public Nullable<double> AmountFCActual { get; set; }
        public Nullable<int> PaymentType { get; set; }
        public Nullable<System.Guid> CustomerID { get; set; }
        public Nullable<System.Guid> CustomerContactID { get; set; }
        public Nullable<System.Guid> CustomerResellerID { get; set; }
        public Nullable<System.Guid> InvoiceAccount { get; set; }
        public int BillCustomer { get; set; }
        public string ItemCode { get; set; }
        public Nullable<System.Guid> ReleaseID { get; set; }
        public Nullable<double> ItemCount { get; set; }
        public Nullable<double> ItemCountActual { get; set; }
        public Nullable<System.Guid> ItemNumberID { get; set; }
        public Nullable<System.Guid> DocumentID { get; set; }
        public bool DocumentsReceived { get; set; }
        public string ItemCode_2 { get; set; }
        public Nullable<System.Guid> ReleaseID_2 { get; set; }
        public Nullable<double> ItemCount_2 { get; set; }
        public Nullable<double> ItemCountActual_2 { get; set; }
        public Nullable<System.Guid> ItemNumberID_2 { get; set; }
        public Nullable<System.Guid> DocumentID_2 { get; set; }
        public string ItemCountry { get; set; }
        public string ItemCountry_2 { get; set; }
        public int Status { get; set; }
        public string Description { get; set; }
        public bool Buildup { get; set; }
        public string ProcessNumber { get; set; }
        public Nullable<System.Guid> FinancialEntryKey { get; set; }
        public string ReferenceNumber { get; set; }
        public string ProjectNumber { get; set; }
        public string RequestComments { get; set; }
        public string WorkflowComments { get; set; }
        public Nullable<int> ToBeApprovedBy { get; set; }
        public int Approver { get; set; }
        public Nullable<System.DateTime> Approved { get; set; }
        public Nullable<int> Processor { get; set; }
        public Nullable<System.DateTime> Processed { get; set; }
        public Nullable<int> Realizer { get; set; }
        public Nullable<System.DateTime> Realized { get; set; }
        public Nullable<System.DateTime> StatusChanged { get; set; }
        public int Priority { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public bool Private { get; set; }
        public Nullable<int> CreatorProduct { get; set; }
        public string OrderNumber { get; set; }
        public string PurchaseNumber { get; set; }
        public string ExchangeLink { get; set; }
        public int SecurityLevel { get; set; }
        public Nullable<System.Guid> EntryGuid { get; set; }
        public string Division { get; set; }
        public Nullable<short> DivisionX { get; set; }
        public Nullable<System.Guid> ParentRequest { get; set; }
        public string FreeTextField_01 { get; set; }
        public string FreeTextField_02 { get; set; }
        public string FreeTextField_03 { get; set; }
        public string FreeTextField_04 { get; set; }
        public string FreeTextField_05 { get; set; }
        public string FreeTextField_06 { get; set; }
        public string FreeTextField_07 { get; set; }
        public string FreeTextField_08 { get; set; }
        public string FreeTextField_09 { get; set; }
        public string FreeTextField_10 { get; set; }
        public string FreeTextField_11 { get; set; }
        public string FreeTextField_12 { get; set; }
        public string FreeTextField_13 { get; set; }
        public string FreeTextField_14 { get; set; }
        public string FreeTextField_15 { get; set; }
        public Nullable<System.DateTime> FreeDateField_01 { get; set; }
        public Nullable<System.DateTime> FreeDateField_02 { get; set; }
        public Nullable<System.DateTime> FreeDateField_03 { get; set; }
        public Nullable<System.DateTime> FreeDateField_04 { get; set; }
        public Nullable<System.DateTime> FreeDateField_05 { get; set; }
        public Nullable<byte> FreeBoolField_01 { get; set; }
        public Nullable<byte> FreeBoolField_02 { get; set; }
        public Nullable<byte> FreeBoolField_03 { get; set; }
        public Nullable<byte> FreeBoolField_04 { get; set; }
        public Nullable<byte> FreeBoolField_05 { get; set; }
        public Nullable<double> FreeNumberField_01 { get; set; }
        public Nullable<double> FreeNumberField_02 { get; set; }
        public Nullable<double> FreeNumberField_03 { get; set; }
        public Nullable<double> FreeNumberField_04 { get; set; }
        public Nullable<double> FreeNumberField_05 { get; set; }
        public Nullable<int> FreeIntField_01 { get; set; }
        public Nullable<int> FreeIntField_02 { get; set; }
        public Nullable<int> FreeIntField_03 { get; set; }
        public Nullable<int> FreeIntField_04 { get; set; }
        public Nullable<int> FreeIntField_05 { get; set; }
        public Nullable<System.Guid> FreeGuidField_01 { get; set; }
        public Nullable<System.Guid> FreeGuidField_02 { get; set; }
        public Nullable<System.Guid> FreeGuidField_03 { get; set; }
        public Nullable<System.Guid> FreeGuidField_04 { get; set; }
        public Nullable<System.Guid> FreeGuidField_05 { get; set; }
        public Nullable<System.Guid> FreeGuidField_06 { get; set; }
        public Nullable<System.Guid> FreeGuidField_07 { get; set; }
        public Nullable<System.Guid> FreeGuidField_08 { get; set; }
        public Nullable<System.Guid> FreeGuidField_09 { get; set; }
        public Nullable<System.Guid> FreeGuidField_10 { get; set; }
        public Nullable<System.Guid> RelatedRequestID { get; set; }
        public byte[] timestamp { get; set; }
        public Nullable<int> RejectedBy { get; set; }
        public Nullable<System.DateTime> Rejected { get; set; }
        public Nullable<System.Guid> TemplateID { get; set; }
        public Nullable<short> Stage { get; set; }
        public string AbsenceBasis { get; set; }
        public byte Entitlement { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
    }
}
