//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class AbsenceEntitlements
    {
        public System.Guid ID { get; set; }
        public int AbsenceType { get; set; }
        public Nullable<int> EmpID { get; set; }
        public string CompanyCode { get; set; }
        public double Scale { get; set; }
        public string JobGroup { get; set; }
        public double Hours { get; set; }
        public double Days { get; set; }
        public Nullable<short> Division { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public int IDCol { get; set; }
        public Nullable<bool> ApplyExpiryDate { get; set; }
        public string EffectiveExpiryPeriod { get; set; }
        public Nullable<short> EffectiveExpiryYear { get; set; }
        public string StatutoryEntitlementUnit { get; set; }
        public string NonStatutoryEntitlementUnit { get; set; }
        public int StatutoryEntitlementExpiry { get; set; }
        public double StatutoryEntitlementDays { get; set; }
        public double StatutoryEntitlementHours { get; set; }
        public int NonStatutoryEntitlementExpiry { get; set; }
        public double NonStatutoryEntitlementDays { get; set; }
        public double NonStatutoryEntitlementHours { get; set; }
    }
}
