//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class accncd
    {
        public int ID { get; set; }
        public string accncd1 { get; set; }
        public string oms40_0 { get; set; }
        public string oms40_1 { get; set; }
        public string oms40_2 { get; set; }
        public string oms40_3 { get; set; }
        public string oms40_4 { get; set; }
        public string accnmask { get; set; }
        public string proeftype { get; set; }
        public short aant_tests { get; set; }
        public short wtabel1_0 { get; set; }
        public short wtabel1_1 { get; set; }
        public short wtabel1_2 { get; set; }
        public short wtabel1_3 { get; set; }
        public short wtabel1_4 { get; set; }
        public short wtabel1_5 { get; set; }
        public short wtabel1_6 { get; set; }
        public short wtabel1_7 { get; set; }
        public short wtabel1_8 { get; set; }
        public short wtabel1_9 { get; set; }
        public short wtabel1_10 { get; set; }
        public short wtabel1_11 { get; set; }
        public short wtabel1_12 { get; set; }
        public short wtabel1_13 { get; set; }
        public short wtabel1_14 { get; set; }
        public short wtabel1_15 { get; set; }
        public short wtabel1_16 { get; set; }
        public short wtabel1_17 { get; set; }
        public short wtabel1_18 { get; set; }
        public short wtabel1_19 { get; set; }
        public short wtabel1_20 { get; set; }
        public short wtabel1_21 { get; set; }
        public short wtabel1_22 { get; set; }
        public short wtabel1_23 { get; set; }
        public short wtabel1_24 { get; set; }
        public short wtabel1_25 { get; set; }
        public short wtabel1_26 { get; set; }
        public short wtabel1_27 { get; set; }
        public short wtabel1_28 { get; set; }
        public short wtabel1_29 { get; set; }
        public short wtabel1_30 { get; set; }
        public short wtabel1_31 { get; set; }
        public short wtabel1_32 { get; set; }
        public short wtabel1_33 { get; set; }
        public byte addinddig1 { get; set; }
        public short modulus1 { get; set; }
        public short wtabel2_0 { get; set; }
        public short wtabel2_1 { get; set; }
        public short wtabel2_2 { get; set; }
        public short wtabel2_3 { get; set; }
        public short wtabel2_4 { get; set; }
        public short wtabel2_5 { get; set; }
        public short wtabel2_6 { get; set; }
        public short wtabel2_7 { get; set; }
        public short wtabel2_8 { get; set; }
        public short wtabel2_9 { get; set; }
        public short wtabel2_10 { get; set; }
        public short wtabel2_11 { get; set; }
        public short wtabel2_12 { get; set; }
        public short wtabel2_13 { get; set; }
        public short wtabel2_14 { get; set; }
        public short wtabel2_15 { get; set; }
        public short wtabel2_16 { get; set; }
        public short wtabel2_17 { get; set; }
        public short wtabel2_18 { get; set; }
        public short wtabel2_19 { get; set; }
        public short wtabel2_20 { get; set; }
        public short wtabel2_21 { get; set; }
        public short wtabel2_22 { get; set; }
        public short wtabel2_23 { get; set; }
        public short wtabel2_24 { get; set; }
        public short wtabel2_25 { get; set; }
        public short wtabel2_26 { get; set; }
        public short wtabel2_27 { get; set; }
        public short wtabel2_28 { get; set; }
        public short wtabel2_29 { get; set; }
        public short wtabel2_30 { get; set; }
        public short wtabel2_31 { get; set; }
        public short wtabel2_32 { get; set; }
        public short wtabel2_33 { get; set; }
        public byte addinddig2 { get; set; }
        public short modulus2 { get; set; }
        public string en_of { get; set; }
        public string vanaf_sort { get; set; }
        public string tot_sort { get; set; }
        public Nullable<short> Division { get; set; }
        public byte use_branch { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
        public byte[] timestamp { get; set; }
    }
}
