//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountAdministrations
    {
        public int ID { get; set; }
        public System.Guid Account { get; set; }
        public string ServerName { get; set; }
        public string DataBaseName { get; set; }
        public string Description { get; set; }
        public string Extra { get; set; }
        public string URL { get; set; }
        public string BackupDirectory { get; set; }
        public string WebServer { get; set; }
        public string IntervalType { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> Date1 { get; set; }
        public Nullable<System.DateTime> Date2 { get; set; }
        public Nullable<System.DateTime> Date3 { get; set; }
        public Nullable<System.DateTime> Date4 { get; set; }
        public Nullable<System.DateTime> Date5 { get; set; }
        public Nullable<System.DateTime> Date6 { get; set; }
        public Nullable<System.DateTime> Date7 { get; set; }
        public Nullable<System.DateTime> Date8 { get; set; }
        public Nullable<System.DateTime> Date9 { get; set; }
        public Nullable<System.DateTime> Date10 { get; set; }
        public string Description1 { get; set; }
        public string Description2 { get; set; }
        public string Description3 { get; set; }
        public string Description4 { get; set; }
        public string Description5 { get; set; }
        public string Description6 { get; set; }
        public string Description7 { get; set; }
        public string Description8 { get; set; }
        public string Description9 { get; set; }
        public string Description10 { get; set; }
        public double Quantity1 { get; set; }
        public double Quantity2 { get; set; }
        public double Quantity3 { get; set; }
        public double Quantity4 { get; set; }
        public double Quantity5 { get; set; }
        public double Quantity6 { get; set; }
        public double Quantity7 { get; set; }
        public double Quantity8 { get; set; }
        public double Quantity9 { get; set; }
        public double Quantity10 { get; set; }
        public Nullable<short> Division { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
        public byte[] timestamp { get; set; }
    }
}
