//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdditionalInvoiceLines
    {
        public int ID { get; set; }
        public string InvoiceCode { get; set; }
        public string SequenceNumber { get; set; }
        public string LineNumber { get; set; }
        public string Field01 { get; set; }
        public string Field02 { get; set; }
        public string Field03 { get; set; }
        public string Field04 { get; set; }
        public string Field05 { get; set; }
        public string Field06 { get; set; }
        public string Field07 { get; set; }
        public string Field08 { get; set; }
        public string Field09 { get; set; }
        public string Field10 { get; set; }
        public Nullable<double> NumberField01 { get; set; }
        public Nullable<double> NumberField02 { get; set; }
        public Nullable<double> NumberField03 { get; set; }
        public Nullable<double> NumberField04 { get; set; }
        public Nullable<double> NumberField05 { get; set; }
        public Nullable<double> NumberField06 { get; set; }
        public Nullable<double> NumberField07 { get; set; }
        public Nullable<double> NumberField08 { get; set; }
        public Nullable<double> NumberField09 { get; set; }
        public Nullable<double> NumberField10 { get; set; }
        public Nullable<System.DateTime> DateField01 { get; set; }
        public Nullable<System.DateTime> DateField02 { get; set; }
        public Nullable<System.DateTime> DateField03 { get; set; }
        public Nullable<System.DateTime> DateField04 { get; set; }
        public Nullable<System.DateTime> DateField05 { get; set; }
        public bool YesNoField01 { get; set; }
        public bool YesNoField02 { get; set; }
        public bool YesNoField03 { get; set; }
        public bool YesNoField04 { get; set; }
        public bool YesNoField05 { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
    }
}
