//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressStates
    {
        public int IdEx { get; set; }
        public System.Guid ID { get; set; }
        public string StateCode { get; set; }
        public string CountryCode { get; set; }
        public string Name { get; set; }
        public Nullable<short> Division { get; set; }
    }
}
