//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Addresses
    {
        public System.Guid ID { get; set; }
        public int IDCol { get; set; }
        public string Type { get; set; }
        public System.Guid Account { get; set; }
        public System.Guid ContactPerson { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressLine3 { get; set; }
        public string PostCode { get; set; }
        public string City { get; set; }
        public string StateCode { get; set; }
        public string County { get; set; }
        public string Country { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> KeepSameAsVisit { get; set; }
        public Nullable<System.DateTime> datefield1 { get; set; }
        public Nullable<System.DateTime> datefield2 { get; set; }
        public Nullable<System.DateTime> datefield3 { get; set; }
        public Nullable<System.DateTime> datefield4 { get; set; }
        public Nullable<System.DateTime> datefield5 { get; set; }
        public double numberfield1 { get; set; }
        public double numberfield2 { get; set; }
        public double numberfield3 { get; set; }
        public double numberfield4 { get; set; }
        public double numberfield5 { get; set; }
        public byte YesNofield1 { get; set; }
        public byte YesNofield2 { get; set; }
        public byte YesNofield3 { get; set; }
        public byte YesNofield4 { get; set; }
        public byte YesNofield5 { get; set; }
        public string textfield1 { get; set; }
        public string textfield2 { get; set; }
        public string textfield3 { get; set; }
        public string textfield4 { get; set; }
        public string textfield5 { get; set; }
        public Nullable<bool> CustomerReq { get; set; }
        public string PoNumber { get; set; }
        public Nullable<int> InvoiceType { get; set; }
        public Nullable<double> DamageWaiver { get; set; }
        public Nullable<int> InvoiceFrequency { get; set; }
        public byte Main { get; set; }
        public string AddressCode { get; set; }
        public Nullable<int> SalesPersonNumber { get; set; }
        public string ShipVia { get; set; }
        public string UPSZone { get; set; }
        public Nullable<byte> IsTaxable { get; set; }
        public string TaxCode { get; set; }
        public string TaxCode2 { get; set; }
        public string TaxCode3 { get; set; }
        public string TaxSchedule { get; set; }
        public string warehouse { get; set; }
        public string FOBCode { get; set; }
        public string EDI_StoreID { get; set; }
        public string EDI_DCID { get; set; }
        public string EDI_StoreName { get; set; }
        public Nullable<short> Division { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public byte[] Timestamp { get; set; }
        public bool AvalaraAddressValidated { get; set; }
        public string TerritoryCode { get; set; }
        public string VatCode { get; set; }
        public byte ChangeVatCode { get; set; }
        public Nullable<System.Guid> SyncID { get; set; }
        public string VATNumber { get; set; }
    }
}
