//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllocationRules
    {
        public int ID { get; set; }
        public string RuleName { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public string EntryType { get; set; }
        public string Condition { get; set; }
        public string CashFlow { get; set; }
        public string GLNumber { get; set; }
        public string VATCode { get; set; }
        public string CostCenter { get; set; }
        public string CostUnit { get; set; }
        public string ProjectNr { get; set; }
        public int ResourceID { get; set; }
        public string ItemCode { get; set; }
        public string DebtorNumber { get; set; }
        public string CreditorNumber { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
        public byte[] timestamp { get; set; }
    }
}
