//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class amutak
    {
        public int ID { get; set; }
        public Nullable<short> bkjrcode { get; set; }
        public string periode { get; set; }
        public string dagbknr { get; set; }
        public string volgnr5 { get; set; }
        public double beginsaldo { get; set; }
        public double eindsaldo { get; set; }
        public string bkstnr { get; set; }
        public string oms25 { get; set; }
        public Nullable<System.DateTime> datum { get; set; }
        public string debnr { get; set; }
        public string crdnr { get; set; }
        public double bedrag { get; set; }
        public string valcode { get; set; }
        public double koers { get; set; }
        public double val_bdr { get; set; }
        public string weeknummer { get; set; }
        public string transreknr { get; set; }
        public string transper { get; set; }
        public string betaalref { get; set; }
        public string betwijze { get; set; }
        public string betcond { get; set; }
        public string kredbep { get; set; }
        public double bdrkredbep { get; set; }
        public double bdrkredbp2 { get; set; }
        public Nullable<System.DateTime> vervdatfak { get; set; }
        public Nullable<System.DateTime> vervdatkrd { get; set; }
        public Nullable<System.DateTime> vervdtkrd2 { get; set; }
        public double percentag { get; set; }
        public double percentag2 { get; set; }
        public double grek_bdr { get; set; }
        public byte storno { get; set; }
        public string match_fakt { get; set; }
        public string reknr { get; set; }
        public string oorsprong { get; set; }
        public string banksubtyp { get; set; }
        public byte struct_m { get; set; }
        public string btw_nummer { get; set; }
        public string adres_cd { get; set; }
        public string adres_nr { get; set; }
        public Nullable<System.DateTime> afldat { get; set; }
        public string guids { get; set; }
        public string status { get; set; }
        public string docnumber { get; set; }
        public Nullable<System.DateTime> docdate { get; set; }
        public string entryorigin { get; set; }
        public int DEL_res_identry { get; set; }
        public byte crdnote { get; set; }
        public System.DateTime syscreated { get; set; }
        public string match_nr { get; set; }
        public int syscreator { get; set; }
        public Nullable<int> amktext { get; set; }
        public System.DateTime sysmodified { get; set; }
        public double bedr_vvaf1 { get; set; }
        public double bedr_vvaf2 { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
        public double bedr_vvaf3 { get; set; }
        public byte[] timestamp { get; set; }
        public double bedr_vvaf4 { get; set; }
        public double bedr_vvaf5 { get; set; }
        public double wisselkrs { get; set; }
        public string kstplcode { get; set; }
        public string kstdrcode { get; set; }
        public string faktuurnr { get; set; }
        public Nullable<System.Guid> DocumentID { get; set; }
        public Nullable<System.Guid> DocAttachmentID { get; set; }
        public Nullable<System.Guid> cmp_wwn { get; set; }
        public string project { get; set; }
        public byte BlockOutstandingItem { get; set; }
        public Nullable<System.Guid> orderdebtor { get; set; }
        public string bankacc { get; set; }
        public string entrytype { get; set; }
        public string freefield1 { get; set; }
        public string freefield2 { get; set; }
        public string freefield3 { get; set; }
        public Nullable<double> freefield4 { get; set; }
        public Nullable<double> freefield5 { get; set; }
        public string CashRegisterAccount { get; set; }
        public string Selcode { get; set; }
        public Nullable<short> Division { get; set; }
        public string csFakregRegister { get; set; }
        public byte csFakregEntry { get; set; }
    }
}
