//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class artbst
    {
        public int ID { get; set; }
        public string artcode { get; set; }
        public string ar_soort { get; set; }
        public byte samengest { get; set; }
        public string kort_oms { get; set; }
        public string oms30_0 { get; set; }
        public string oms30_1 { get; set; }
        public string oms30_2 { get; set; }
        public string oms30_3 { get; set; }
        public string oms30_4 { get; set; }
        public string lev_crdnr { get; set; }
        public string tekst { get; set; }
        public string artgrp { get; set; }
        public string magcode { get; set; }
        public Nullable<byte> voorrart { get; set; }
        public string eenh_verk { get; set; }
        public Nullable<double> aant_verp { get; set; }
        public Nullable<double> verkp_verp { get; set; }
        public string bestadvc { get; set; }
        public string btw_verk { get; set; }
        public string btw_ink { get; set; }
        public string statistnr { get; set; }
        public Nullable<byte> backordart { get; set; }
        public string verp_oms { get; set; }
        public string serie_art { get; set; }
        public Nullable<byte> orderink { get; set; }
        public Nullable<double> vwrd1 { get; set; }
        public Nullable<double> vwrd2 { get; set; }
        public double vvp { get; set; }
        public string intfac_ink { get; set; }
        public string intfac_vrk { get; set; }
        public Nullable<double> stateenh { get; set; }
        public Nullable<double> nettogew { get; set; }
        public Nullable<double> brutogew { get; set; }
        public string btw_vlevy { get; set; }
        public Nullable<double> vmargin { get; set; }
        public string status { get; set; }
        public string picturefile { get; set; }
        public string condition { get; set; }
        public string property { get; set; }
        public Nullable<byte> divisible { get; set; }
        public Nullable<double> freefield1 { get; set; }
        public Nullable<double> freefield2 { get; set; }
        public Nullable<double> freefield3 { get; set; }
        public string freefield4 { get; set; }
        public string freefield5 { get; set; }
        public string freefield6 { get; set; }
        public string freefield7 { get; set; }
        public string freefield8 { get; set; }
        public string freefield9 { get; set; }
        public string freefield10 { get; set; }
        public Nullable<System.DateTime> freefield11 { get; set; }
        public Nullable<System.DateTime> freefield12 { get; set; }
        public Nullable<double> freefield13 { get; set; }
        public Nullable<double> freefield14 { get; set; }
        public Nullable<double> freefield15 { get; set; }
        public Nullable<byte> freefield16 { get; set; }
        public Nullable<byte> freefield17 { get; set; }
        public Nullable<byte> freefield18 { get; set; }
        public Nullable<byte> freefield19 { get; set; }
        public Nullable<byte> freefield20 { get; set; }
        public byte discount { get; set; }
        public byte explode { get; set; }
        public byte from_synergy { get; set; }
        public string Class_01 { get; set; }
        public string Class_02 { get; set; }
        public string Class_03 { get; set; }
        public string Class_04 { get; set; }
        public string Class_05 { get; set; }
        public string Class_06 { get; set; }
        public string Class_07 { get; set; }
        public string Class_08 { get; set; }
        public string Class_09 { get; set; }
        public string Class_10 { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
        public byte[] timestamp { get; set; }
    }
}
