//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class artlev
    {
        public int ID { get; set; }
        public string artcode { get; set; }
        public string lev_crdnr { get; set; }
        public string artcodlev { get; set; }
        public string eenh_ink { get; set; }
        public double aantverpi { get; set; }
        public double inkp_verp { get; set; }
        public Nullable<double> gip { get; set; }
        public Nullable<double> tot_nontv { get; set; }
        public Nullable<double> omr_fact { get; set; }
        public string btw_ink { get; set; }
        public Nullable<int> prafspr { get; set; }
        public Nullable<short> levt { get; set; }
        public Nullable<byte> levb { get; set; }
        public double bestgr { get; set; }
        public string verp_oms { get; set; }
        public string bestn_l { get; set; }
        public Nullable<System.DateTime> bestdatl { get; set; }
        public Nullable<System.DateTime> ontvdatl { get; set; }
        public Nullable<double> qtypack { get; set; }
        public Nullable<double> qtyunit { get; set; }
        public double SlsPkgsPerPurPkg { get; set; }
        public string barcode { get; set; }
        public byte[] timestamp { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
    }
}
