//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit_Def_Instellingen_routine
    {
        public string menunaam { get; set; }
        public string sub { get; set; }
        public string onderdeel { get; set; }
        public string tablenaam { get; set; }
        public string settinggroup { get; set; }
        public string settingname { get; set; }
        public string field { get; set; }
        public int ID { get; set; }
    }
}
