//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BacoAccessServers
    {
        public int ID { get; set; }
        public string IPAddress { get; set; }
        public bool CheckIPAddress { get; set; }
        public string MachineName { get; set; }
        public bool CheckMachineName { get; set; }
        public string MacAddress { get; set; }
        public bool CheckMacAddress { get; set; }
        public Nullable<short> Division { get; set; }
        public string MacAddress2 { get; set; }
        public string MachineName2 { get; set; }
    }
}
