//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BacoDiscussionGroups
    {
        public int ID { get; set; }
        public int GroupOrder { get; set; }
        public string Description { get; set; }
        public bool AllowReplies { get; set; }
        public bool RestrictedRights { get; set; }
        public bool Publish { get; set; }
        public byte[] GroupIcon { get; set; }
        public string GroupIconFileName { get; set; }
        public byte UseProductLine { get; set; }
        public byte UseItems { get; set; }
        public byte UseHumResID { get; set; }
        public byte UseCmpWwn { get; set; }
        public byte UseLanguageID { get; set; }
        public byte UseCompGroup { get; set; }
        public byte UseCompany { get; set; }
        public byte UseProjectNr { get; set; }
        public byte UseEntryKey { get; set; }
        public byte UseVote { get; set; }
        public Nullable<System.Guid> TemplateID { get; set; }
        public Nullable<short> Division { get; set; }
        public byte UseItemNumber { get; set; }
    }
}
