//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BacoAppLog
    {
        public System.Guid ID { get; set; }
        public System.DateTime Created { get; set; }
        public int SessionID { get; set; }
        public int HumresID { get; set; }
        public Nullable<int> DelegateID { get; set; }
        public int SecurityLevel { get; set; }
        public Nullable<System.Guid> CustomerID { get; set; }
        public string App { get; set; }
        public string QueryString { get; set; }
        public string DataKey { get; set; }
        public string ServerName { get; set; }
        public string ServerAddress { get; set; }
        public string HostName { get; set; }
        public string ClientAddress { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> SPID { get; set; }
        public Nullable<short> Division { get; set; }
    }
}
