//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BacoProducts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BacoProducts()
        {
            this.ReportCategories = new HashSet<ReportCategories>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
        public Nullable<int> DescriptionTermID { get; set; }
        public string Prefix { get; set; }
        public Nullable<int> Color { get; set; }
        public string DocDefault { get; set; }
        public string DocSearch { get; set; }
        public string DocNews { get; set; }
        public string DocReports { get; set; }
        public string DocMaintenance { get; set; }
        public string DocOrganization { get; set; }
        public Nullable<short> Division { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportCategories> ReportCategories { get; set; }
    }
}
