//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BacoDiscussionFixedTypes
    {
        public int TypeID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public byte SystemType { get; set; }
        public string Description { get; set; }
        public Nullable<byte> Active { get; set; }
        public Nullable<System.Guid> Policy { get; set; }
        public Nullable<int> Manager { get; set; }
        public Nullable<short> DefSecurity { get; set; }
        public Nullable<byte> EditSecurity { get; set; }
        public Nullable<int> DefGroupID { get; set; }
        public Nullable<System.Guid> DefCategory { get; set; }
        public Nullable<System.Guid> DefSubCategory { get; set; }
        public Nullable<byte> Attachment { get; set; }
        public Nullable<byte> UsePublish { get; set; }
        public Nullable<byte> UseRating { get; set; }
        public Nullable<byte> UseStatistics { get; set; }
        public Nullable<byte> UseOwner { get; set; }
        public Nullable<short> Cr_Security { get; set; }
        public Nullable<byte> Cr_SystemGen { get; set; }
        public Nullable<int> Cr_Role1 { get; set; }
        public Nullable<int> Cr_Level1 { get; set; }
        public Nullable<int> Cr_Role2 { get; set; }
        public Nullable<int> Cr_Level2 { get; set; }
        public Nullable<int> Cr_Role3 { get; set; }
        public Nullable<int> Cr_Level3 { get; set; }
        public Nullable<byte> Ap_Use { get; set; }
        public Nullable<byte> It_Use { get; set; }
        public string It_Default { get; set; }
        public string It_Selection { get; set; }
        public string It_Status { get; set; }
        public string It_Label { get; set; }
        public Nullable<byte> As_Use { get; set; }
        public Nullable<int> As_Default { get; set; }
        public Nullable<byte> Re_Use { get; set; }
        public string Re_Type { get; set; }
        public string Re_Status { get; set; }
        public string Re_Selection { get; set; }
        public string Re_Label { get; set; }
        public Nullable<byte> Ac_Use { get; set; }
        public string Ac_Type { get; set; }
        public string Ac_Selection { get; set; }
        public string Ac_Label { get; set; }
        public Nullable<byte> Pr_Use { get; set; }
        public string Pr_Default { get; set; }
        public string Pr_Selection { get; set; }
        public Nullable<byte> Fi_Use { get; set; }
        public string Fi_Selection { get; set; }
        public Nullable<byte> Fi_OurRef { get; set; }
        public Nullable<byte> Fi_YourRef { get; set; }
        public byte It_UseNumber { get; set; }
        public Nullable<int> DaysToExpiry { get; set; }
        public byte OrderNumber_Use { get; set; }
        public byte ShipmentMethod_Use { get; set; }
        public byte PaymentReference_Use { get; set; }
        public byte Warehouse_Use { get; set; }
        public Nullable<System.Guid> TemplateID { get; set; }
        public string VersionType { get; set; }
        public string EditRights { get; set; }
        public string DeleteRights { get; set; }
        public Nullable<byte> Sec_Ap_Use { get; set; }
        public Nullable<short> Division { get; set; }
        public Nullable<System.Guid> GroupID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public bool UseInBackOffice { get; set; }
    }
}
