//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BacoErrorLog
    {
        public int LogID { get; set; }
        public System.DateTime LogDate { get; set; }
        public int SessionID { get; set; }
        public int HumresID { get; set; }
        public Nullable<System.Guid> CustomerID { get; set; }
        public string App { get; set; }
        public string WebServer { get; set; }
        public string Machine { get; set; }
        public string LogText { get; set; }
        public Nullable<short> Division { get; set; }
    }
}
