//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BacoDiscussions
    {
        public System.Guid ID { get; set; }
        public int HID { get; set; }
        public Nullable<System.Guid> ParentID { get; set; }
        public int GroupID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public System.DateTime ViewDate { get; set; }
        public int CreatedBy { get; set; }
        public string CreatedByFullName { get; set; }
        public string Subject { get; set; }
        public string Class_02_1 { get; set; }
        public string Class_02_2 { get; set; }
        public string Category { get; set; }
        public string SubCategory { get; set; }
        public int Type { get; set; }
        public string Filename { get; set; }
        public string Body { get; set; }
        public byte[] Document { get; set; }
        public string Company { get; set; }
        public int JobLevel { get; set; }
        public int Status { get; set; }
        public string ItemCode { get; set; }
        public Nullable<int> HumResID { get; set; }
        public Nullable<System.Guid> CmpWwn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public byte NewsType { get; set; }
        public string LanguageID { get; set; }
        public bool IsTemplate { get; set; }
        public bool IsMailMerge { get; set; }
        public string StatusText { get; set; }
        public string ProjectNr { get; set; }
        public Nullable<System.Guid> EntryKey { get; set; }
        public Nullable<int> Owner { get; set; }
        public Nullable<short> OwnerType { get; set; }
        public string OwnerTypeValue { get; set; }
        public Nullable<int> VoteCount { get; set; }
        public Nullable<int> VoteSum { get; set; }
        public Nullable<System.Guid> ItemNumberID { get; set; }
        public string FPIntroText { get; set; }
        public Nullable<int> Assortment { get; set; }
        public Nullable<System.Guid> cnt_id { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string OrderNumber { get; set; }
        public string ShipmentMethod { get; set; }
        public string OurRef { get; set; }
        public string YourRef { get; set; }
        public string PaymentReference { get; set; }
        public string Warehouse { get; set; }
        public string Source { get; set; }
        public string Note { get; set; }
        public string Version { get; set; }
        public Nullable<System.DateTime> CheckedOut { get; set; }
        public Nullable<int> CheckedOutBy { get; set; }
        public Nullable<short> Division { get; set; }
        public byte[] timestamp { get; set; }
    }
}
