//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BacoDiscussionNewsLayouts
    {
        public string BDLayoutID { get; set; }
        public string Description { get; set; }
        public string HeaderPage { get; set; }
        public string FooterPage { get; set; }
        public string DefaultImage { get; set; }
        public bool Headlines { get; set; }
        public string HLBackGround { get; set; }
        public string Condition { get; set; }
        public short MaxNews { get; set; }
        public short MaxHeadlines { get; set; }
        public string TextHeader { get; set; }
        public string TextFooter { get; set; }
        public byte Enabled { get; set; }
        public byte UseSelectionCombo { get; set; }
        public Nullable<System.Guid> ImageDefault { get; set; }
        public Nullable<System.Guid> ImageHLBackground { get; set; }
        public byte LayoutType { get; set; }
        public Nullable<System.Guid> EditorialDocID { get; set; }
        public Nullable<System.Guid> HeaderDocID { get; set; }
        public Nullable<System.Guid> FooterDocID { get; set; }
        public string Bedrnr { get; set; }
        public string ConditionDivision { get; set; }
        public string ConditionLanguage { get; set; }
        public string ConditionJobLevelOperator { get; set; }
        public Nullable<int> ConditionJobLevelValue { get; set; }
        public byte OrDivisionUse { get; set; }
        public byte OrCountryUse { get; set; }
        public byte OrDivisionGroupUse { get; set; }
        public bool HeadlineImage { get; set; }
        public Nullable<short> Division { get; set; }
    }
}
