//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BacoDiscussionSubCategories
    {
        public System.Guid ID { get; set; }
        public int GroupID { get; set; }
        public Nullable<System.Guid> CategoryID { get; set; }
        public string Category { get; set; }
        public string SubCategory { get; set; }
        public bool NeedsApproval { get; set; }
        public int SecurityLevel { get; set; }
        public bool FullText { get; set; }
        public bool ForumCustomer { get; set; }
        public bool ForumReseller { get; set; }
        public bool ForumEmployee { get; set; }
        public string ForumDescription { get; set; }
        public Nullable<short> Division { get; set; }
    }
}
