//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BacoAppLogHours
    {
        public System.DateTime Day { get; set; }
        public int Hour { get; set; }
        public int PageViews { get; set; }
        public int PageViewsEmployees { get; set; }
        public int PageViewsResellers { get; set; }
        public int PageViewsCustomers { get; set; }
        public int PageViewsPublic { get; set; }
        public Nullable<short> Division { get; set; }
    }
}
