//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAccounts
    {
        public string BankAccount { get; set; }
        public int ID { get; set; }
        public Nullable<int> HumanResourceID { get; set; }
        public Nullable<System.Guid> NameAddressDateBank { get; set; }
        public string BankAccountIncludingMask { get; set; }
        public string CurrencyCode { get; set; }
        public string SWIFTCode { get; set; }
        public string BICCode { get; set; }
        public string Description { get; set; }
        public double CurrentBalance { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string IdentificationNumberBank { get; set; }
        public string IdentificationNumberBankOffice { get; set; }
        public string InternetAddress { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string BankAccountType { get; set; }
        public double CreditLine { get; set; }
        public string Notes { get; set; }
        public string LedgerAccount { get; set; }
        public string PaymentInTransitAccount { get; set; }
        public string bedrnr { get; set; }
        public string Creditor { get; set; }
        public string AccountNumberBank { get; set; }
        public string land_isonr { get; set; }
        public string BankName { get; set; }
        public double CostsPayments { get; set; }
        public double CostsReceipts { get; set; }
        public double DebitInterest { get; set; }
        public double CreditInterest { get; set; }
        public Nullable<int> MaxLines { get; set; }
        public Nullable<double> MaxAmount { get; set; }
        public string Purpose { get; set; }
        public string DocumentNumber { get; set; }
        public double FixedCostsYr { get; set; }
        public Nullable<System.Guid> DocAttachmentID { get; set; }
        public byte Blocked { get; set; }
        public double CostsPaymentRun { get; set; }
        public string CreditCardType { get; set; }
        public string PresetCode { get; set; }
        public string MenuBar { get; set; }
        public string eftterminal { get; set; }
        public string eftport { get; set; }
        public string cardreader { get; set; }
        public string crdr_port { get; set; }
        public short fontsize { get; set; }
        public string colfield0 { get; set; }
        public int colwidth0 { get; set; }
        public string colfield1 { get; set; }
        public int colwidth1 { get; set; }
        public string colfield2 { get; set; }
        public int colwidth2 { get; set; }
        public string colfield3 { get; set; }
        public int colwidth3 { get; set; }
        public string colfield4 { get; set; }
        public int colwidth4 { get; set; }
        public string colfield5 { get; set; }
        public int colwidth5 { get; set; }
        public string colfield6 { get; set; }
        public int colwidth6 { get; set; }
        public string colfield7 { get; set; }
        public int colwidth7 { get; set; }
        public string colfield8 { get; set; }
        public int colwidth8 { get; set; }
        public string colfield9 { get; set; }
        public int colwidth9 { get; set; }
        public string colfield10 { get; set; }
        public int colwidth10 { get; set; }
        public string InvoiceLayout { get; set; }
        public byte PrintLayout { get; set; }
        public string magcode { get; set; }
        public byte CountMandatory { get; set; }
        public double LimitAmount { get; set; }
        public byte CashierMandatory { get; set; }
        public string Journal { get; set; }
        public byte Excluding { get; set; }
        public string Header1 { get; set; }
        public string Header2 { get; set; }
        public string Header3 { get; set; }
        public string Header4 { get; set; }
        public string Trailer1 { get; set; }
        public string Trailer2 { get; set; }
        public string Trailer3 { get; set; }
        public string Trailer4 { get; set; }
        public string AccountSequenceNumber { get; set; }
        public string Cashier { get; set; }
        public Nullable<byte> DebtorMandatory { get; set; }
        public string BankAccountRef { get; set; }
        public string ProcessorCode { get; set; }
        public string MerchantNumber { get; set; }
        public string PCChargeDirectory { get; set; }
        public string ActiveLDPCode { get; set; }
        public string InActiveLDPCode { get; set; }
        public string Officenumber { get; set; }
        public string Contractnumber { get; set; }
        public string Suffix { get; set; }
        public string IBAN { get; set; }
        public Nullable<byte> UseSEPA { get; set; }
        public string TransactionGroupType { get; set; }
        public Nullable<short> Division { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
        public string ClientID { get; set; }
        public string MerchantKey { get; set; }
        public double PreAuthorizationLimit { get; set; }
        public double CreditCardLimit { get; set; }
        public int TimeOut { get; set; }
        public string LastValidYear { get; set; }
        public Nullable<System.Guid> BankLinkID { get; set; }
        public string SynchronizationCode { get; set; }
        public bool TransactionsPermission { get; set; }
        public bool PaymentsPermission { get; set; }
        public bool CollectionsPermission { get; set; }
        public Nullable<int> SequenceNumber { get; set; }
        public int Active { get; set; }
        public Nullable<int> Administration { get; set; }
        public Nullable<byte> UseSEPADirectDebit { get; set; }
        public string CreditorID { get; set; }
        public bool CreditorIDChanged { get; set; }
        public bool CompanyNameChanged { get; set; }
        public bool SentSEPADirectDebit { get; set; }
        public string OldCreditorID { get; set; }
        public bool SCTBatchBook { get; set; }
        public bool SDDBatchBook { get; set; }
        public string SCTExportFileFormatType { get; set; }
        public Nullable<System.Guid> SCTDocumentID { get; set; }
        public string SDDExportFileFormatType { get; set; }
        public Nullable<System.Guid> SDDDocumentID { get; set; }
        public Nullable<int> SDDFirstDays { get; set; }
        public Nullable<int> SDDRecurrentDays { get; set; }
        public string SCTCurrency { get; set; }
        public string bankcode { get; set; }
        public string branchcode { get; set; }
        public string ClearanceIdentification { get; set; }
        public string BankAccountSubType { get; set; }
    }
}
