//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAccountsView
    {
        public string BankAccount { get; set; }
        public Nullable<int> HumanResourceID { get; set; }
        public string BankAccountIncludingMask { get; set; }
        public string CurrencyCode { get; set; }
        public string SWIFTCode { get; set; }
        public string BICCode { get; set; }
        public string Description { get; set; }
        public double CurrentBalance { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string IdentificationNumberBank { get; set; }
        public string IdentificationNumberBankOffice { get; set; }
        public string InternetAddress { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string BankAccountType { get; set; }
        public double CreditLine { get; set; }
        public string Notes { get; set; }
        public Nullable<System.Guid> NameAddressDateBank { get; set; }
        public string LedgerAccount { get; set; }
        public string PaymentInTransitAccount { get; set; }
        public string bedrnr { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
        public int ID { get; set; }
        public string Creditor { get; set; }
        public string AccountNumberBank { get; set; }
        public string ShortDescription { get; set; }
        public string BankAddress1 { get; set; }
        public string BankAddress2 { get; set; }
        public string BankCity { get; set; }
        public string BankCountryCode { get; set; }
        public string BankCountry_0 { get; set; }
        public string BankName { get; set; }
        public string BankPostCode { get; set; }
        public Nullable<System.Guid> ContactID { get; set; }
        public string ContactEmail { get; set; }
        public string ContactFaxNumber { get; set; }
        public string ContactJobDescription { get; set; }
        public string ContactName { get; set; }
        public string ContactPhoneExtension { get; set; }
        public string ContactPhoneNumber { get; set; }
        public string CurrencyDescription_0 { get; set; }
        public string CurrencyDescription_1 { get; set; }
        public string CurrencyDescription_2 { get; set; }
        public string CurrencyDescription_3 { get; set; }
        public string CurrencyDescription_4 { get; set; }
        public string HumanResourceFullName { get; set; }
        public string BankCountry_1 { get; set; }
        public string BankCountry_2 { get; set; }
        public string BankCountry_3 { get; set; }
        public string BankCountry_4 { get; set; }
        public int LandID { get; set; }
    }
}
