//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankBalancePerCurrencyView
    {
        public string Currency { get; set; }
        public string Description { get; set; }
        public Nullable<int> NumberOfAccounts { get; set; }
        public Nullable<double> ClosingBalance { get; set; }
        public int ClosingBalanceEUR { get; set; }
    }
}
