//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankStatementHeadersExView
    {
        public Nullable<int> StatusMark { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> StatementDate { get; set; }
        public string BankName { get; set; }
        public string OwnBankAccount { get; set; }
        public string StatementNumber { get; set; }
        public string CurrencyCode { get; set; }
        public string FullName { get; set; }
        public string BankAccountType { get; set; }
        public int ID { get; set; }
    }
}
