//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankFormats
    {
        public int ID { get; set; }
        public string FormatType { get; set; }
        public string land_isonr { get; set; }
        public string FormatName { get; set; }
        public string BankName { get; set; }
        public string FormatFileName { get; set; }
        public string FormatSystem { get; set; }
        public byte OneCurrencyPerBatch { get; set; }
        public byte OneOffsetPerBatch { get; set; }
        public byte OneAccountPerBatch { get; set; }
        public byte OneDatePerBatch { get; set; }
        public string MatchingCriteria1 { get; set; }
        public string MatchingCriteria2 { get; set; }
        public string ProgID { get; set; }
        public string Mask { get; set; }
        public Nullable<int> DataModuleID { get; set; }
        public string Description { get; set; }
        public int TotalPackageCount { get; set; }
        public int DatePackageCount { get; set; }
        public Nullable<System.DateTime> LastPackageDate { get; set; }
        public byte OneBatchDatePerFile { get; set; }
        public byte EURBatchesInSeparateFile { get; set; }
        public byte MultiCurrency { get; set; }
        public string ExtraMatchingDelimiter { get; set; }
        public string ExtraMatchingCriteria1 { get; set; }
        public string ExtraMatchingCriteria2 { get; set; }
        public string ExtraMatchingCriteria3 { get; set; }
        public string Assembly { get; set; }
        public string AssemblyClass { get; set; }
        public Nullable<short> Division { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
    }
}
