//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankImportLogs
    {
        public int ID { get; set; }
        public int BankTransactionID { get; set; }
        public string FileName { get; set; }
        public Nullable<System.DateTime> StatementDate { get; set; }
        public string StatementNumber { get; set; }
        public string OwnBankAccount { get; set; }
        public string CreditorNumber { get; set; }
        public string DebtorNumber { get; set; }
        public string AllocationRule { get; set; }
        public string AllocationCriteria { get; set; }
        public string AllocationStatus { get; set; }
        public Nullable<int> MatchID { get; set; }
        public string MatchingRule { get; set; }
        public string MatchingCriteria { get; set; }
        public string MatchingStatus { get; set; }
        public Nullable<short> Division { get; set; }
        public System.Guid sysguid { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
    }
}
