//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAuthorizations
    {
        public int ID { get; set; }
        public string BankAccount { get; set; }
        public int ResourceID { get; set; }
        public double Amount { get; set; }
        public Nullable<System.Guid> DocumentID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public double AmountRestricted { get; set; }
        public Nullable<short> Division { get; set; }
    }
}
