//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasePwfunc
    {
        public string fnc_id { get; set; }
        public string descr30 { get; set; }
        public int term_id { get; set; }
        public string settings { get; set; }
        public string descr64 { get; set; }
        public string app_type { get; set; }
        public string rtype { get; set; }
        public byte pwreg { get; set; }
        public byte mpackage_0 { get; set; }
        public string exename { get; set; }
        public string param { get; set; }
        public string option_exp { get; set; }
        public string slic { get; set; }
        public string sparam { get; set; }
        public string origin { get; set; }
        public int icon { get; set; }
        public string helpcontext { get; set; }
        public System.Guid sysguid { get; set; }
    }
}
