//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class bdgvrs
    {
        public int ID { get; set; }
        public string bud_vers { get; set; }
        public short revisienr { get; set; }
        public string oms30_0 { get; set; }
        public string oms30_1 { get; set; }
        public string oms30_2 { get; set; }
        public string oms30_3 { get; set; }
        public string oms30_4 { get; set; }
        public string vers_stat { get; set; }
        public Nullable<short> bkjrcode_v { get; set; }
        public string periode_v { get; set; }
        public Nullable<short> bkjrcode_t { get; set; }
        public string periode_t { get; set; }
        public short prec { get; set; }
        public int factor { get; set; }
        public string bud_niveau { get; set; }
        public byte bud_bev { get; set; }
        public string planperiod { get; set; }
        public Nullable<short> Division { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
        public byte[] timestamp { get; set; }
    }
}
