//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BDPictureRefs
    {
        public System.Guid DocID { get; set; }
        public System.Guid PictureID { get; set; }
        public string Version { get; set; }
        public Nullable<short> Division { get; set; }
    }
}
