//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BDViewColumns
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public Nullable<int> DescriptionTermID { get; set; }
        public string Caption { get; set; }
        public Nullable<int> CaptionTermID { get; set; }
        public string Columns { get; set; }
        public int ColumnCount { get; set; }
        public int DataType { get; set; }
        public string Joins { get; set; }
        public Nullable<bool> InnerJoin { get; set; }
        public bool WorkflowOnly { get; set; }
        public string DescriptionSuffix { get; set; }
        public Nullable<int> DescriptionSuffixTermID { get; set; }
        public Nullable<short> Division { get; set; }
    }
}
