//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class betcd
    {
        public int ID { get; set; }
        public string betcond { get; set; }
        public string oms30_0 { get; set; }
        public string oms30_1 { get; set; }
        public string oms30_2 { get; set; }
        public string oms30_3 { get; set; }
        public string oms30_4 { get; set; }
        public string kredbep { get; set; }
        public short kbdagen { get; set; }
        public short kbdagen2 { get; set; }
        public double percentag { get; set; }
        public double percentag2 { get; set; }
        public short termijn { get; set; }
        public short dagvmnd { get; set; }
        public short maanden { get; set; }
        public string type_verv { get; set; }
        public string brut_net_f { get; set; }
        public byte termijnen { get; set; }
        public string type_verv1 { get; set; }
        public string type_verv2 { get; set; }
        public string type_verv3 { get; set; }
        public string type_verv4 { get; set; }
        public string type_verv5 { get; set; }
        public short termijn1 { get; set; }
        public short termijn2 { get; set; }
        public short termijn3 { get; set; }
        public short termijn4 { get; set; }
        public short termijn5 { get; set; }
        public double int_perc { get; set; }
        public string brut_net_p { get; set; }
        public Nullable<short> Discount3 { get; set; }
        public Nullable<float> DiscountPercentage3 { get; set; }
        public Nullable<short> Division { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
        public byte[] timestamp { get; set; }
        public byte UseSplitPayment { get; set; }
    }
}
