//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BI_USER_INT
    {
        public string user_profile { get; set; }
        public string user_name { get; set; }
        public string user_email_address { get; set; }
        public string administer_gps_network { get; set; }
        public string licensed_to_powerui { get; set; }
        public string private_zero_client_user { get; set; }
        public string licensed_to_dashboard { get; set; }
        public string licensed_to_bui { get; set; }
        public string licensed_to_bui_plus { get; set; }
        public string save_to_repository { get; set; }
        public string maintain_financial_hierarchy { get; set; }
        public string licensed_to_expressui { get; set; }
        public string ALLOW_WEB_REFRESH { get; set; }
        public string CHANGE_PERSONAL_WEBPARTS { get; set; }
        public string CHANGE_SHARED_WEBPARTS { get; set; }
    }
}
