//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class bnkacc
    {
        public int ID { get; set; }
        public string banknr { get; set; }
        public Nullable<System.Guid> AccountID { get; set; }
        public string accncd { get; set; }
        public string bnkaccmsk { get; set; }
        public string naam { get; set; }
        public string adres1 { get; set; }
        public string adres2 { get; set; }
        public string adres3 { get; set; }
        public string postcode { get; set; }
        public string woonpl { get; set; }
        public string landcode { get; set; }
        public string telnr { get; set; }
        public string faxnr { get; set; }
        public string cntpers1 { get; set; }
        public string mv1 { get; set; }
        public string prdcode1 { get; set; }
        public string vrlttrs1 { get; set; }
        public string functie1 { get; set; }
        public string telnrcp1 { get; set; }
        public string pstbanknrb { get; set; }
        public string bank_rek { get; set; }
        public string swiftadres { get; set; }
        public string bankcode { get; set; }
        public string valcode { get; set; }
        public string natbnc { get; set; }
        public string cont_veld { get; set; }
        public string branchcode { get; set; }
        public string BranchName { get; set; }
        public string CreditCardName { get; set; }
        public string CreditCardType { get; set; }
        public string CreditCardSecurityCode { get; set; }
        public Nullable<System.DateTime> CreditCardExpiryDate { get; set; }
        public string IBAN { get; set; }
        public string BICCode { get; set; }
        public Nullable<short> Division { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
        public byte[] timestamp { get; set; }
        public string BankAccountType { get; set; }
        public bool IsBlocked { get; set; }
        public byte IsRegistered { get; set; }
        public string ClearanceIdentification { get; set; }
    }
}
