//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class btwtrs
    {
        public int ID { get; set; }
        public string btwtrans { get; set; }
        public string CompanyCode { get; set; }
        public string oms30_0 { get; set; }
        public string oms30_1 { get; set; }
        public string oms30_2 { get; set; }
        public string oms30_3 { get; set; }
        public string oms30_4 { get; set; }
        public string code_iv { get; set; }
        public byte verlegdbtw { get; set; }
        public double btwper { get; set; }
        public string btwoms { get; set; }
        public string exclus { get; set; }
        public string landcode { get; set; }
        public string btwlist { get; set; }
        public string reknr { get; set; }
        public string rek_btw_vk { get; set; }
        public string tegreknr { get; set; }
        public string crednota { get; set; }
        public string cred_btwcd { get; set; }
        public byte btw_vt { get; set; }
        public byte btw_vrij { get; set; }
        public byte btw_reg { get; set; }
        public double levy_per { get; set; }
        public double invest_per { get; set; }
        public string acc_invtax { get; set; }
        public string acc_invtdb { get; set; }
        public string acc_invtcr { get; set; }
        public string creditor { get; set; }
        public string pay_period { get; set; }
        public string PurchaseType { get; set; }
        public double NonDeductiblePercentage { get; set; }
        public string NonDeductibleAccount { get; set; }
        public string taxtype { get; set; }
        public string calculationbasis { get; set; }
        public string AutofatturaCode { get; set; }
        public Nullable<double> AmountMinimum { get; set; }
        public Nullable<double> AmountMaximum { get; set; }
        public string Taxkey { get; set; }
        public string Taxsubkey { get; set; }
        public string Rent { get; set; }
        public Nullable<short> Division { get; set; }
        public string VATToBeClaimed { get; set; }
        public bool PerpertualService { get; set; }
        public string RoundingScheme { get; set; }
        public string VATToPaySuspenseGL { get; set; }
        public string VATToClaimSuspenseGL { get; set; }
        public bool UseCashSystem { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
        public byte[] timestamp { get; set; }
        public string VATSection { get; set; }
    }
}
