//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class btwvrt
    {
        public int ID { get; set; }
        public string btwvrtnr { get; set; }
        public string naam { get; set; }
        public string adres1 { get; set; }
        public string adres2 { get; set; }
        public string adres3 { get; set; }
        public string postcode { get; set; }
        public string woonpl { get; set; }
        public string landcode { get; set; }
        public string telefoon { get; set; }
        public string faxnr { get; set; }
        public string cpers { get; set; }
        public string btw_nummer { get; set; }
        public Nullable<short> Division { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
        public byte[] timestamp { get; set; }
    }
}
