//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChargeTransactions
    {
        public int ID { get; set; }
        public System.Guid ParentID { get; set; }
        public int SequenceNumber { get; set; }
        public string ChargeCode { get; set; }
        public string ActionType { get; set; }
        public Nullable<double> NetPrice { get; set; }
        public double Quantity { get; set; }
        public Nullable<double> Percentage { get; set; }
        public Nullable<double> WeightFactor { get; set; }
        public double ChargeAmount { get; set; }
        public string VatCode { get; set; }
        public string TaxCode2 { get; set; }
        public string TaxCode3 { get; set; }
        public string TaxCode4 { get; set; }
        public string TaxCode5 { get; set; }
        public Nullable<double> VatBasis { get; set; }
        public Nullable<double> TaxBasis2 { get; set; }
        public Nullable<double> TaxBasis3 { get; set; }
        public Nullable<double> TaxBasis4 { get; set; }
        public Nullable<double> TaxBasis5 { get; set; }
        public Nullable<double> VatAmount { get; set; }
        public Nullable<double> TaxAmount2 { get; set; }
        public Nullable<double> TaxAmount3 { get; set; }
        public Nullable<double> TaxAmount4 { get; set; }
        public Nullable<double> TaxAmount5 { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
    }
}
