//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChargeConditions
    {
        public int ID { get; set; }
        public string ChargeCode { get; set; }
        public string Field { get; set; }
        public string StringValue { get; set; }
        public Nullable<System.DateTime> DateValue { get; set; }
        public Nullable<double> DoubleValue { get; set; }
        public string ActionType { get; set; }
        public Nullable<double> WeightFactor { get; set; }
        public Nullable<double> Percentage { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
    }
}
