//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class cicntp
    {
        public int ID { get; set; }
        public System.Guid cnt_id { get; set; }
        public Nullable<System.Guid> cmp_wwn { get; set; }
        public string cnt_f_name { get; set; }
        public string cnt_l_name { get; set; }
        public string cnt_m_name { get; set; }
        public string FullName { get; set; }
        public string Initials { get; set; }
        public string Gender { get; set; }
        public string predcode { get; set; }
        public string cnt_job_desc { get; set; }
        public string cnt_dept { get; set; }
        public string taalcode { get; set; }
        public string cnt_f_ext { get; set; }
        public string cnt_f_fax { get; set; }
        public string cnt_f_tel { get; set; }
        public string cnt_f_mobile { get; set; }
        public string cnt_email { get; set; }
        public int cnt_acc_man { get; set; }
        public string cnt_note { get; set; }
        public byte active_y { get; set; }
        public string Administration { get; set; }
        public int res_id { get; set; }
        public byte WebAccess { get; set; }
        public byte[] Picture { get; set; }
        public string PictureFileName { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
        public byte[] timestamp { get; set; }
        public Nullable<System.DateTime> datefield1 { get; set; }
        public Nullable<System.DateTime> datefield2 { get; set; }
        public Nullable<System.DateTime> datefield3 { get; set; }
        public Nullable<System.DateTime> datefield4 { get; set; }
        public Nullable<System.DateTime> datefield5 { get; set; }
        public Nullable<double> numberfield1 { get; set; }
        public Nullable<double> numberfield2 { get; set; }
        public Nullable<double> numberfield3 { get; set; }
        public Nullable<double> numberfield4 { get; set; }
        public Nullable<double> numberfield5 { get; set; }
        public byte YesNoField1 { get; set; }
        public byte YesNoField2 { get; set; }
        public byte YesNoField3 { get; set; }
        public byte YesNoField4 { get; set; }
        public byte YesNoField5 { get; set; }
        public string textfield1 { get; set; }
        public string textfield2 { get; set; }
        public string textfield3 { get; set; }
        public string textfield4 { get; set; }
        public string textfield5 { get; set; }
        public string cntp_Directory { get; set; }
        public Nullable<short> Division { get; set; }
        public Nullable<bool> ContactChange { get; set; }
        public string OldFileName { get; set; }
        public Nullable<System.Guid> SyncID { get; set; }
        public byte FinancialContactPerson { get; set; }
    }
}
