//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ciFreeFields
    {
        public System.Guid ID { get; set; }
        public string BedrNr { get; set; }
        public string TableName { get; set; }
        public string ColumnName { get; set; }
        public string Description { get; set; }
        public string SelectionValues { get; set; }
        public string Selection { get; set; }
        public Nullable<int> Reference { get; set; }
        public Nullable<short> Division { get; set; }
    }
}
