//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class cnhrpayroll
    {
        public int ID { get; set; }
        public string type { get; set; }
        public short contract { get; set; }
        public System.DateTime startdate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public string description { get; set; }
        public string job_title { get; set; }
        public Nullable<System.Guid> DocAttachmentID { get; set; }
        public Nullable<short> PayrollYear { get; set; }
        public int Res_id { get; set; }
        public short Period { get; set; }
        public string Payment_Period { get; set; }
        public string Country { get; set; }
        public string Base_Value_Method { get; set; }
        public double Fixed_Value { get; set; }
        public string District { get; set; }
        public string Sliptext1 { get; set; }
        public string Sliptext2 { get; set; }
        public string Sliptext3 { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
        public byte[] timestamp { get; set; }
    }
}
