//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyParticipations
    {
        public System.Guid ID { get; set; }
        public string ParentCompanyCode { get; set; }
        public string ChildCompanyCode { get; set; }
        public double PercentageControl { get; set; }
        public double PercentageFinancial { get; set; }
        public Nullable<short> Division { get; set; }
        public byte[] timestamp { get; set; }
    }
}
