//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractParameters
    {
        public System.Guid ID { get; set; }
        public string Company { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public int Method { get; set; }
        public int RenewalPeriod { get; set; }
        public string RenewalInterval { get; set; }
        public double PriceIndex { get; set; }
        public int CurrencySource { get; set; }
        public string DocumentType { get; set; }
        public int MonthsToBillAhead { get; set; }
        public string InvoiceCode { get; set; }
        public int BillingType { get; set; }
        public Nullable<short> Division { get; set; }
    }
}
