//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSPickITSKUMut
    {
        public string OuterSku { get; set; }
        public string InnerSku { get; set; }
        public string ItemCode { get; set; }
        public string Warehouse { get; set; }
        public string Location { get; set; }
        public double Quantity { get; set; }
        public string Number { get; set; }
        public Nullable<System.DateTime> ReferenceDate { get; set; }
        public Nullable<int> OrderPicker { get; set; }
        public string PickITModule { get; set; }
        public string GbkmutFaktuurNr { get; set; }
        public Nullable<System.Guid> GbkmutEntryGuid { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
        public byte[] timestamp { get; set; }
        public int ID { get; set; }
    }
}
