//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSPickITRFSubLine
    {
        public int ID { get; set; }
        public Nullable<System.Guid> RFSubLineGuid { get; set; }
        public Nullable<System.Guid> ParentRFSubLineGuid { get; set; }
        public int RFHeaderLineID { get; set; }
        public int RFTransactionID { get; set; }
        public int SequenceNumber { get; set; }
        public string Warehouse { get; set; }
        public string Location { get; set; }
        public string SSCCNumber { get; set; }
        public string SSCCNumber2 { get; set; }
        public string ItemCode { get; set; }
        public string ItemDescription { get; set; }
        public byte IsFractionAllowedItem { get; set; }
        public string SalesUnit { get; set; }
        public string PurchaseUnit { get; set; }
        public string SerialBatchItem { get; set; }
        public string SerialBatchNumber { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public byte IsIssue { get; set; }
        public byte IsReturn { get; set; }
        public Nullable<double> Quantity { get; set; }
        public string Instruction { get; set; }
        public byte IsInstructionShown { get; set; }
        public string CostUnit { get; set; }
        public Nullable<double> SalesPackagePrice { get; set; }
        public int TransferLineID { get; set; }
        public int CountsID { get; set; }
        public int OrsrgID { get; set; }
        public int RecipeID { get; set; }
        public int GbkmutID { get; set; }
        public Nullable<System.Guid> OrsrgExGUID { get; set; }
        public string UserIDString { get; set; }
        public byte IsCreatedOnDevice { get; set; }
        public byte IsReady { get; set; }
        public int CrossDockOrsrgID { get; set; }
        public int CrossDockGBKMUTID { get; set; }
        public string OuterSku { get; set; }
        public string InnerSku { get; set; }
        public string ScanUnit { get; set; }
        public double UnitFactor { get; set; }
        public byte IsParent { get; set; }
        public byte IsSkuItem { get; set; }
        public byte IsInnerSkuItem { get; set; }
        public byte IsOuterSkuItem { get; set; }
        public Nullable<int> SkuItemID { get; set; }
        public double Factor { get; set; }
        public double QuantityInXUnits { get; set; }
        public string ScanCode { get; set; }
        public string PackageDescription { get; set; }
        public byte IsDpaAdvice { get; set; }
        public byte IsFullSkuTransfer { get; set; }
        public byte IsToBeTransfered { get; set; }
        public string ReceiptLocation { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
        public byte[] timestamp { get; set; }
    }
}
