//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSPickITShipment
    {
        public int ID { get; set; }
        public string ShipmentSSCC { get; set; }
        public string Warehouse { get; set; }
        public string DeliveryDebtor { get; set; }
        public string Description { get; set; }
        public string Del_Debtor_Name { get; set; }
        public string Del_AddressLine1 { get; set; }
        public string Del_AddressLine2 { get; set; }
        public string Del_AddressLine3 { get; set; }
        public string Del_City { get; set; }
        public string Del_PostCode { get; set; }
        public string Del_LandCode { get; set; }
        public string Del_cnt_job_desc { get; set; }
        public string Del_County { get; set; }
        public string Del_StateCode { get; set; }
        public string Del_Phone { get; set; }
        public string Del_Fax { get; set; }
        public string Del_Initials { get; set; }
        public string Del_ContactPerson { get; set; }
        public string Del_ContactEmail { get; set; }
        public string Del_PredCode { get; set; }
        public byte IsPrinted { get; set; }
        public byte isFCBSShipment { get; set; }
        public Nullable<System.Guid> TransactionGUID { get; set; }
        public Nullable<System.DateTime> Del_date { get; set; }
        public string ShipmentMethod { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
        public byte[] timestamp { get; set; }
    }
}
