//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSPickITRFHeaderLine
    {
        public int ID { get; set; }
        public int RFTransactionID { get; set; }
        public int TransferID { get; set; }
        public int CountsRangeID { get; set; }
        public string SalesOrderNumber { get; set; }
        public string Reference { get; set; }
        public string DeliveryDebtor { get; set; }
        public string InvoiceDebtor { get; set; }
        public string OrderDebtor { get; set; }
        public string OrderDebtorName { get; set; }
        public string PurchaseOrderNumber { get; set; }
        public string OrderedAt { get; set; }
        public string OrderedAtName { get; set; }
        public string ProductionOrderNumber { get; set; }
        public string ProductionOrderDescription { get; set; }
        public int Step { get; set; }
        public string Operation { get; set; }
        public string OperationDescription { get; set; }
        public string EndProduct { get; set; }
        public string EndProductDescription { get; set; }
        public string Parent { get; set; }
        public byte Urgent { get; set; }
        public byte PartialDelivery { get; set; }
        public string SelectionCode { get; set; }
        public string InvoiceCode { get; set; }
        public string CostCenter { get; set; }
        public Nullable<System.DateTime> FulfillmentDate { get; set; }
        public int Packages { get; set; }
        public Nullable<double> GrossWeight { get; set; }
        public Nullable<double> NetWeight { get; set; }
        public string RouteCode { get; set; }
        public string Project { get; set; }
        public string GLAccount { get; set; }
        public string Warehouse { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
        public byte[] timestamp { get; set; }
        public string STTCode { get; set; }
    }
}
