//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSPickITHTsettingsSTO
    {
        public int ID { get; set; }
        public string SettingName { get; set; }
        public string Description { get; set; }
        public string STODetailedScreen { get; set; }
        public string STOFocusTo { get; set; }
        public byte STOScanComb { get; set; }
        public string STOScanCombChar { get; set; }
        public byte STOEAN128 { get; set; }
        public byte STOFocusToNextField { get; set; }
        public string STOWarehouseDef { get; set; }
        public string STOWarehouseNFLD { get; set; }
        public string STOLocationDef { get; set; }
        public string STOLocationNFLD { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
        public byte[] timestamp { get; set; }
    }
}
