//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSPickITRForsrg
    {
        public int ID { get; set; }
        public string SalesOrderNumberExact { get; set; }
        public int RecipeIDExact { get; set; }
        public int OrsrgIDExact { get; set; }
        public int OrkrgID { get; set; }
        public string ItemCode { get; set; }
        public byte Gereed { get; set; }
        public string Description { get; set; }
        public string Reference { get; set; }
        public string SerialBatchItem { get; set; }
        public byte PickMore { get; set; }
        public string Instruction { get; set; }
        public string CostUnit { get; set; }
        public string SerialBatchNumber { get; set; }
        public string Warehouse { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> SalesPackagePrice { get; set; }
        public string SalesUnit { get; set; }
        public Nullable<double> QuantityPicked { get; set; }
        public string OrderDebtorName { get; set; }
        public string HandTerminalID { get; set; }
        public string UserID { get; set; }
        public string PurchaseUnit { get; set; }
        public string ProductionOrderNumber { get; set; }
        public int GbkmutIDExact { get; set; }
        public string ProductionOrderNumberExact { get; set; }
        public string ProdOrderDescription { get; set; }
        public int Step { get; set; }
        public string Operation { get; set; }
        public string OperationDescription { get; set; }
        public string EndProduct { get; set; }
        public string EndProductDescription { get; set; }
        public string Parent { get; set; }
        public string Location { get; set; }
        public byte IsFractionAllowedItem { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
        public byte[] timestamp { get; set; }
    }
}
