//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSPickITStatistics
    {
        public int ID { get; set; }
        public int ResourceID { get; set; }
        public byte IsServiceJob { get; set; }
        public string PickITModule { get; set; }
        public string PickITProcess { get; set; }
        public string Number { get; set; }
        public int NLines { get; set; }
        public int NItems { get; set; }
        public int NSerialNumbers { get; set; }
        public int NBatchNumbers { get; set; }
        public string HandTerminalID { get; set; }
        public int ORSRGID { get; set; }
        public string ItemCode { get; set; }
        public int TimeSpanSeconds { get; set; }
        public int GBKMUTID { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
        public byte[] timestamp { get; set; }
        public Nullable<double> Quantity { get; set; }
    }
}
