//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSPickITItemLocations
    {
        public int ID { get; set; }
        public string ItemCode { get; set; }
        public string Warehouse { get; set; }
        public string Location { get; set; }
        public string Description { get; set; }
        public Nullable<double> Min_Stock { get; set; }
        public Nullable<double> Max_Stock { get; set; }
        public Nullable<double> Max_Stock_Validated { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
        public byte[] timestamp { get; set; }
    }
}
