//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSPickITHTsettingsVPT
    {
        public int ID { get; set; }
        public string SettingName { get; set; }
        public string Description { get; set; }
        public string VPTCrdDef { get; set; }
        public byte VPTCrdScan { get; set; }
        public byte VPTCrdNameDisp { get; set; }
        public byte VPTCrdVal { get; set; }
        public string VPTWarehouseDef { get; set; }
        public string VPTWarehouseScanNFLD { get; set; }
        public string VPTReferDef { get; set; }
        public byte VPTReferScan { get; set; }
        public string VPTSelDef { get; set; }
        public byte VPTSelScan { get; set; }
        public string VPTCCtrDef { get; set; }
        public byte VPTCCtrEnter { get; set; }
        public byte VPTProjectVal { get; set; }
        public byte VPTProjectEnter { get; set; }
        public string VPTUserDef { get; set; }
        public byte VPTItemVal { get; set; }
        public byte VPTItemDescDisp { get; set; }
        public byte VPTItemQty { get; set; }
        public Nullable<double> VPTQuantityDef { get; set; }
        public Nullable<double> VPTQuantityMax { get; set; }
        public Nullable<double> VPTQuantityMin { get; set; }
        public string VPTCUnitDef { get; set; }
        public byte VPTCUnitEnter { get; set; }
        public string VPTDetailedScreen { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
        public byte[] timestamp { get; set; }
    }
}
