//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSPickITHTsettingsGER
    {
        public int ID { get; set; }
        public string SettingName { get; set; }
        public string Description { get; set; }
        public string GERGSBDef { get; set; }
        public string GERItemCodeNFLD { get; set; }
        public byte GERItemLookup { get; set; }
        public string GERFocusTo { get; set; }
        public string GERLocationDef { get; set; }
        public string GERLocationNFLD { get; set; }
        public Nullable<double> GERQuantityDef { get; set; }
        public Nullable<double> GERQuantityMax { get; set; }
        public Nullable<double> GERQuantityMin { get; set; }
        public string GERQuantityNFLD { get; set; }
        public string GERSerialBatchNFLD { get; set; }
        public string GERWarehouseDef { get; set; }
        public string GERWarehouseNFLD { get; set; }
        public byte GERScanComb { get; set; }
        public string GERScanCombChar { get; set; }
        public byte GERStockBrowse { get; set; }
        public byte GERBestBeforeDateSerialItem { get; set; }
        public byte GERBestBeforeDateBatchItem { get; set; }
        public byte GERProdDateSerialItem { get; set; }
        public byte GERProdDateBatchItem { get; set; }
        public byte GEREAN128 { get; set; }
        public byte GERFocusToNextField { get; set; }
        public byte GERAutoOpenSkuScreen { get; set; }
        public string GERDetailedScreen { get; set; }
        public byte GERBarcodePopup { get; set; }
        public byte GERSBLabelScreen { get; set; }
        public byte GERAcceptExtSkus { get; set; }
        public byte GERAllowAutoReceive { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
        public byte[] timestamp { get; set; }
    }
}
