//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSRekregFuncties
    {
        public int ID { get; set; }
        public string FormulaName { get; set; }
        public string Description { get; set; }
        public string Rounding { get; set; }
        public Nullable<double> RoundOffTo { get; set; }
        public string LabelName_0 { get; set; }
        public string LabelName_1 { get; set; }
        public string LabelName_2 { get; set; }
        public string LabelName_3 { get; set; }
        public string LabelName_4 { get; set; }
        public string LabelName_5 { get; set; }
        public string LabelName_6 { get; set; }
        public string LabelName_7 { get; set; }
        public string LabelName_8 { get; set; }
        public string LabelName_9 { get; set; }
        public string LabelName_10 { get; set; }
        public byte Changeable_0 { get; set; }
        public byte Changeable_1 { get; set; }
        public byte Changeable_2 { get; set; }
        public byte Changeable_3 { get; set; }
        public byte Changeable_4 { get; set; }
        public byte Changeable_5 { get; set; }
        public byte Changeable_6 { get; set; }
        public byte Changeable_7 { get; set; }
        public byte Changeable_8 { get; set; }
        public byte Changeable_9 { get; set; }
        public byte Changeable_10 { get; set; }
        public string Type_0 { get; set; }
        public string Type_1 { get; set; }
        public string Type_2 { get; set; }
        public string Type_3 { get; set; }
        public string Type_4 { get; set; }
        public string Type_5 { get; set; }
        public string Type_6 { get; set; }
        public string Type_7 { get; set; }
        public string Type_8 { get; set; }
        public string Type_9 { get; set; }
        public string Type_10 { get; set; }
        public Nullable<double> Value_0 { get; set; }
        public Nullable<double> Value_1 { get; set; }
        public Nullable<double> Value_2 { get; set; }
        public Nullable<double> Value_3 { get; set; }
        public Nullable<double> Value_4 { get; set; }
        public Nullable<double> Value_5 { get; set; }
        public Nullable<double> Value_6 { get; set; }
        public Nullable<double> Value_7 { get; set; }
        public Nullable<double> Value_8 { get; set; }
        public Nullable<double> Value_9 { get; set; }
        public Nullable<double> Value_10 { get; set; }
        public string Operator_0 { get; set; }
        public string Operator_1 { get; set; }
        public string Operator_2 { get; set; }
        public string Operator_3 { get; set; }
        public string Operator_4 { get; set; }
        public string Operator_5 { get; set; }
        public string Operator_6 { get; set; }
        public string Operator_7 { get; set; }
        public string Operator_8 { get; set; }
        public string Operator_9 { get; set; }
        public string Subrounding_0 { get; set; }
        public string Subrounding_1 { get; set; }
        public string Subrounding_2 { get; set; }
        public string Subrounding_3 { get; set; }
        public string Subrounding_4 { get; set; }
        public string Subrounding_5 { get; set; }
        public string Subrounding_6 { get; set; }
        public string Subrounding_7 { get; set; }
        public string Subrounding_8 { get; set; }
        public string Subrounding_9 { get; set; }
        public string Subrounding_10 { get; set; }
        public Nullable<double> SubroundOffTo_0 { get; set; }
        public Nullable<double> SubroundOffTo_1 { get; set; }
        public Nullable<double> SubroundOffTo_2 { get; set; }
        public Nullable<double> SubroundOffTo_3 { get; set; }
        public Nullable<double> SubroundOffTo_4 { get; set; }
        public Nullable<double> SubroundOffTo_5 { get; set; }
        public Nullable<double> SubroundOffTo_6 { get; set; }
        public Nullable<double> SubroundOffTo_7 { get; set; }
        public Nullable<double> SubroundOffTo_8 { get; set; }
        public Nullable<double> SubroundOffTo_9 { get; set; }
        public Nullable<double> SubroundOffTo_10 { get; set; }
        public string Extra01 { get; set; }
        public string Extra02 { get; set; }
        public string Extra03 { get; set; }
        public string Extra04 { get; set; }
        public string Extra05 { get; set; }
        public string Extra06 { get; set; }
        public int QuantityField { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
        public byte[] timestamp { get; set; }
    }
}
