//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DDTables
    {
        public int ID { get; set; }
        public string TableName { get; set; }
        public Nullable<int> TermId { get; set; }
        public string Abbr { get; set; }
        public string Description { get; set; }
        public string ReportOptions { get; set; }
        public string Uid { get; set; }
        public int Flags { get; set; }
        public int GroupId { get; set; }
        public int UserLevel { get; set; }
        public string SecurityLevelField { get; set; }
        public string Suffix { get; set; }
        public Nullable<int> SuffixId { get; set; }
    }
}
