//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class dehrpayrollcontract
    {
        public int ID { get; set; }
        public string type { get; set; }
        public short contract { get; set; }
        public string payment_period { get; set; }
        public string country { get; set; }
        public int res_id { get; set; }
        public System.DateTime startdate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public string description { get; set; }
        public string job_title { get; set; }
        public Nullable<System.Guid> DocAttachmentID { get; set; }
        public string Vertragsart { get; set; }
        public byte LohnEintritt { get; set; }
        public byte AustrittDurchTod { get; set; }
        public string Arbeitnehmergruppe { get; set; }
        public string Personengruppe { get; set; }
        public Nullable<int> Taetigkeitsschluessel { get; set; }
        public string AuslandArt { get; set; }
        public string Leistungsgruppe { get; set; }
        public string Beschaeftigungsart { get; set; }
        public Nullable<System.DateTime> GekuendigtAm { get; set; }
        public Nullable<System.DateTime> GekuendigtZum { get; set; }
        public Nullable<System.DateTime> BefristetBis { get; set; }
        public string Befristungsgrund { get; set; }
        public string Kuendigungsgrund { get; set; }
        public string KuendigungDurch { get; set; }
        public Nullable<System.DateTime> AusbildungsPruefungstermin { get; set; }
        public string Ausbildungsziel { get; set; }
        public string Ausbildungsart { get; set; }
        public byte AusbildungBestanden { get; set; }
        public byte AusbildungVerkuerzt { get; set; }
        public double AusbildungsWochenstunden { get; set; }
        public double AusbildungsMonatsentgelt { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
        public byte[] timestamp { get; set; }
    }
}
