//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class dehrpayroll
    {
        public int ID { get; set; }
        public string type { get; set; }
        public short contract { get; set; }
        public string payment_period { get; set; }
        public string country { get; set; }
        public string description { get; set; }
        public int res_id { get; set; }
        public System.DateTime startdate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public string LohnartSoll { get; set; }
        public string pauschalsteuersatz { get; set; }
        public Nullable<System.DateTime> Einstufungsdatum { get; set; }
        public Nullable<System.DateTime> VersorgungBeginn { get; set; }
        public double KinderfreibetragKUG { get; set; }
        public double VersorgungBemessungLfd { get; set; }
        public double VersorgungBemessungEGA { get; set; }
        public double sollentgelt { get; set; }
        public double kinderfreibetraege { get; set; }
        public double grundlohn_sfn { get; set; }
        public double ueberstd_prozent { get; set; }
        public double freibetrag_month { get; set; }
        public double freibetrag_year { get; set; }
        public double krankenvers_privat { get; set; }
        public double pflegevers_privat { get; set; }
        public double zuverdienstgrenze_rente { get; set; }
        public double jahreseinkommen_abweich { get; set; }
        public byte lohnsteuerjahresausgleich { get; set; }
        public byte Lohnsteuerbescheinigung { get; set; }
        public byte KinderPV { get; set; }
        public Nullable<short> steuerklasse { get; set; }
        public Nullable<short> SteuerklasseKUG { get; set; }
        public Nullable<short> pauschale_kirchensteuer { get; set; }
        public Nullable<short> beitragsgruppe { get; set; }
        public Nullable<short> uebernahme_sv_ag { get; set; }
        public string bundesland { get; set; }
        public string lohnsteuertabelle { get; set; }
        public string Arbeitskammer_land { get; set; }
        public string krankenvers_freiw { get; set; }
        public string pflegevers_freiw { get; set; }
        public string rentenbezug { get; set; }
        public string mehrfach_beschaeftigt { get; set; }
        public string beitragsgrenze_abweichung { get; set; }
        public string arbeitnehmergruppe { get; set; }
        public string sv_kennzeichen { get; set; }
        public string sollentgeld_art { get; set; }
        public string grundlohn_sfn_formel { get; set; }
        public string sv_unterbrechung { get; set; }
        public string DEUEVStatus { get; set; }
        public string konfession { get; set; }
        public string konfession_ehegatte { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
        public byte[] TimeStamp { get; set; }
    }
}
