//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeletionLogs
    {
        public int ID { get; set; }
        public string TableName { get; set; }
        public string KeyString1 { get; set; }
        public string KeyString2 { get; set; }
        public string KeyString3 { get; set; }
        public string KeyString4 { get; set; }
        public string KeyString5 { get; set; }
        public Nullable<int> KeyInt1 { get; set; }
        public Nullable<int> KeyInt2 { get; set; }
        public Nullable<int> KeyInt3 { get; set; }
        public Nullable<int> KeyInt4 { get; set; }
        public Nullable<int> KeyInt5 { get; set; }
        public Nullable<System.DateTime> KeyDate1 { get; set; }
        public Nullable<System.DateTime> KeyDate2 { get; set; }
        public Nullable<System.DateTime> KeyDate3 { get; set; }
        public Nullable<System.Guid> KeyGuid1 { get; set; }
        public Nullable<System.Guid> KeyGuid2 { get; set; }
        public Nullable<System.Guid> KeyGuid3 { get; set; }
        public string CompanyCode { get; set; }
        public Nullable<short> Division { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.Guid sysguid { get; set; }
        public byte[] timestamp { get; set; }
    }
}
