//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimTime
    {
        public int DATE_ID { get; set; }
        public System.DateTime DATE { get; set; }
        public System.DateTime NEXT_DAY_DATE { get; set; }
        public short YEAR { get; set; }
        public int YEAR_QUARTER { get; set; }
        public int YEAR_MONTH { get; set; }
        public int YEAR_DAY_OF_YEAR { get; set; }
        public byte QUARTER { get; set; }
        public byte MONTH { get; set; }
        public short DAY_OF_YEAR { get; set; }
        public short DAY_OF_MONTH { get; set; }
        public byte DAY_OF_WEEK { get; set; }
        public string YEAR_NAME { get; set; }
        public string YEAR_QUARTER_NAME { get; set; }
        public string YEAR_MONTH_NAME { get; set; }
        public string YEAR_MONTH_NAME_LONG { get; set; }
        public string QUARTER_NAME { get; set; }
        public string MONTH_NAME { get; set; }
        public string MONTH_NAME_LONG { get; set; }
        public string WEEKDAY_NAME { get; set; }
        public string WEEKDAY_NAME_LONG { get; set; }
        public System.DateTime START_OF_YEAR_DATE { get; set; }
        public System.DateTime END_OF_YEAR_DATE { get; set; }
        public System.DateTime START_OF_QUARTER_DATE { get; set; }
        public System.DateTime END_OF_QUARTER_DATE { get; set; }
        public System.DateTime START_OF_MONTH_DATE { get; set; }
        public System.DateTime END_OF_MONTH_DATE { get; set; }
        public System.DateTime START_OF_WEEK_STARTING_SUN_DATE { get; set; }
        public System.DateTime END_OF_WEEK_STARTING_SUN_DATE { get; set; }
        public System.DateTime START_OF_WEEK_STARTING_MON_DATE { get; set; }
        public System.DateTime END_OF_WEEK_STARTING_MON_DATE { get; set; }
        public System.DateTime START_OF_WEEK_STARTING_TUE_DATE { get; set; }
        public System.DateTime END_OF_WEEK_STARTING_TUE_DATE { get; set; }
        public System.DateTime START_OF_WEEK_STARTING_WED_DATE { get; set; }
        public System.DateTime END_OF_WEEK_STARTING_WED_DATE { get; set; }
        public System.DateTime START_OF_WEEK_STARTING_THU_DATE { get; set; }
        public System.DateTime END_OF_WEEK_STARTING_THU_DATE { get; set; }
        public System.DateTime START_OF_WEEK_STARTING_FRI_DATE { get; set; }
        public System.DateTime END_OF_WEEK_STARTING_FRI_DATE { get; set; }
        public System.DateTime START_OF_WEEK_STARTING_SAT_DATE { get; set; }
        public System.DateTime END_OF_WEEK_STARTING_SAT_DATE { get; set; }
        public int QUARTER_SEQ_NO { get; set; }
        public int MONTH_SEQ_NO { get; set; }
        public int WEEK_STARTING_SUN_SEQ_NO { get; set; }
        public int WEEK_STARTING_MON_SEQ_NO { get; set; }
        public int WEEK_STARTING_TUE_SEQ_NO { get; set; }
        public int WEEK_STARTING_WED_SEQ_NO { get; set; }
        public int WEEK_STARTING_THU_SEQ_NO { get; set; }
        public int WEEK_STARTING_FRI_SEQ_NO { get; set; }
        public int WEEK_STARTING_SAT_SEQ_NO { get; set; }
        public int JULIAN_DATE { get; set; }
        public int MODIFIED_JULIAN_DATE { get; set; }
        public string ISO_DATE { get; set; }
        public int ISO_YEAR_WEEK_NO { get; set; }
        public short ISO_WEEK_NO { get; set; }
        public byte ISO_DAY_OF_WEEK { get; set; }
        public string ISO_YEAR_WEEK_NAME { get; set; }
        public string ISO_YEAR_WEEK_DAY_OF_WEEK_NAME { get; set; }
        public string DATE_FORMAT_YYYY_MM_DD { get; set; }
        public string DATE_FORMAT_YYYY_M_D { get; set; }
        public string DATE_FORMAT_MM_DD_YYYY { get; set; }
        public string DATE_FORMAT_M_D_YYYY { get; set; }
        public string DATE_FORMAT_MMM_D_YYYY { get; set; }
        public string DATE_FORMAT_MMMMMMMMM_D_YYYY { get; set; }
        public string DATE_FORMAT_MM_DD_YY { get; set; }
        public string DATE_FORMAT_M_D_YY { get; set; }
    }
}
