//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentNumberTransactionRules
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string Description_0 { get; set; }
        public string Description_1 { get; set; }
        public string Description_2 { get; set; }
        public string Description_3 { get; set; }
        public string Description_4 { get; set; }
        public short TransactionTypeID { get; set; }
        public short OptionLimit { get; set; }
        public string FirstPriority { get; set; }
        public string SecondPriority { get; set; }
        public short Division { get; set; }
        public string Status { get; set; }
        public string FreeField1 { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
