//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class EbcComponentRelations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EbcComponentRelations()
        {
            this.EbcPropRelations = new HashSet<EbcPropRelations>();
        }
    
        public System.Guid CompRelationId { get; set; }
        public Nullable<int> CompRelationTypeId { get; set; }
        public string CompRelationName { get; set; }
        public System.Guid CompId1 { get; set; }
        public System.Guid CompId2 { get; set; }
        public string CompRelationValue { get; set; }
        public bool Enabled { get; set; }
        public string EnabledQuery { get; set; }
        public string Options { get; set; }
    
        public virtual EbcComponentRelationTypes EbcComponentRelationTypes { get; set; }
        public virtual EbcComponents EbcComponents { get; set; }
        public virtual EbcComponents EbcComponents1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EbcPropRelations> EbcPropRelations { get; set; }
    }
}
