//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class EbcComponents
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EbcComponents()
        {
            this.EbcComponentRelations = new HashSet<EbcComponentRelations>();
            this.EbcComponentRelations1 = new HashSet<EbcComponentRelations>();
            this.EbcProps = new HashSet<EbcProps>();
        }
    
        public System.Guid CompId { get; set; }
        public int GroupId { get; set; }
        public int ComponentTypeId { get; set; }
        public string ComponentName { get; set; }
        public string Description { get; set; }
        public Nullable<int> TermId { get; set; }
        public string ProgId { get; set; }
        public string Assembly { get; set; }
        public string Class { get; set; }
        public Nullable<int> DataComponentTypeId { get; set; }
        public string BaseTable { get; set; }
        public string Query { get; set; }
        public string Params { get; set; }
        public string QueryKey { get; set; }
        public Nullable<int> CacheSize { get; set; }
        public bool Placeholders { get; set; }
        public bool Log { get; set; }
        public string ComponentNameWS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EbcComponentRelations> EbcComponentRelations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EbcComponentRelations> EbcComponentRelations1 { get; set; }
        public virtual EbcComponentTypes EbcComponentTypes { get; set; }
        public virtual EbcDataComponentTypes EbcDataComponentTypes { get; set; }
        public virtual EbcGroups EbcGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EbcProps> EbcProps { get; set; }
    }
}
