//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class EbcEntityRelations
    {
        public System.Guid EntityRelationID { get; set; }
        public System.Guid EntityID { get; set; }
        public System.Guid PropId { get; set; }
        public System.Guid LinkedPropId { get; set; }
    }
}
