//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class EBDataQueueEntries
    {
        public int ID { get; set; }
        public string Type { get; set; }
        public string Status { get; set; }
        public int DataType { get; set; }
        public System.DateTime DateImported { get; set; }
        public string OriginalName { get; set; }
        public Nullable<System.DateTime> OriginalDate { get; set; }
        public byte[] Data { get; set; }
        public byte[] timestamp { get; set; }
        public int BankFormatID { get; set; }
        public Nullable<int> HumanResourceID { get; set; }
        public string bedrnr { get; set; }
        public int QtyTransactions { get; set; }
        public int QtyStatements { get; set; }
        public double TotalAmountDC { get; set; }
        public Nullable<short> Division { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
    }
}
