//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class esbplcs
    {
        public string NumInfor { get; set; }
        public string NomInfor { get; set; }
        public string CodClasOf { get; set; }
        public string DescCodClasOf { get; set; }
        public string CodContable { get; set; }
        public string CodContaUs { get; set; }
        public string Signo { get; set; }
    }
}
