//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class eshrpayrollcontract
    {
        public int ID { get; set; }
        public string type { get; set; }
        public short contract { get; set; }
        public System.DateTime startdate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public string description { get; set; }
        public string job_title { get; set; }
        public Nullable<System.Guid> DocAttachmentID { get; set; }
        public int res_id { get; set; }
        public string payment_period { get; set; }
        public string country { get; set; }
        public string con_actividad { get; set; }
        public string con_convenio { get; set; }
        public string con_group { get; set; }
        public string con_function { get; set; }
        public string soc_contract { get; set; }
        public string soc_education { get; set; }
        public byte soc_social_yn { get; set; }
        public string soc_group_epi { get; set; }
        public string soc_group_epi_calc { get; set; }
        public string contr_contracto { get; set; }
        public Nullable<System.DateTime> contr_date { get; set; }
        public string afi_accion { get; set; }
        public string afi_desempl { get; set; }
        public string afi_situation { get; set; }
        public Nullable<System.DateTime> afi_date { get; set; }
        public byte afi_make_yn { get; set; }
        public byte afi_woman_ny { get; set; }
        public byte afi_warning_yn { get; set; }
        public byte fan_more_job { get; set; }
        public string fan_Kind_Salary { get; set; }
        public Nullable<short> afi_Autorizacion { get; set; }
        public Nullable<System.DateTime> afi_Vigencia { get; set; }
        public string afi_Maternity { get; set; }
        public Nullable<System.DateTime> fec_antiguedad { get; set; }
        public byte afi_incap_readm { get; set; }
        public byte afi_exclu_social { get; set; }
        public byte afi_rar { get; set; }
        public byte soc_consej_admin { get; set; }
        public Nullable<short> afi_grado_minusv { get; set; }
        public double afi_fte { get; set; }
        public byte soc_fixday { get; set; }
        public Nullable<System.DateTime> soc_ContractStartDate { get; set; }
        public Nullable<System.DateTime> soc_ContractEndDate { get; set; }
        public byte soc_Older60 { get; set; }
        public byte soc_Older65 { get; set; }
        public Nullable<System.DateTime> soc_Older60Date { get; set; }
        public Nullable<System.DateTime> soc_Older65Date { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
        public byte[] timestamp { get; set; }
    }
}
