//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESSII
    {
        public int ID { get; set; }
        public string TabType { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> ReportingDate { get; set; }
        public Nullable<System.DateTime> FulfilmentDate { get; set; }
        public string JournalCode { get; set; }
        public string EntryNumber { get; set; }
        public string InvoiceNumber { get; set; }
        public string SupplierInvoiceNumber { get; set; }
        public string DebtorNumber { get; set; }
        public string CreditorNumber { get; set; }
        public Nullable<System.Guid> Cmp_wwn { get; set; }
        public Nullable<System.Guid> EntryGuid { get; set; }
        public string VATCode { get; set; }
        public double InvoiceAmount { get; set; }
        public double VATBasis { get; set; }
        public double VATAmount { get; set; }
        public double ExtraDutyAmount { get; set; }
        public double NonDeductibleAmount { get; set; }
        public string TransactionType { get; set; }
        public Nullable<short> GbkmutType { get; set; }
        public string LastInvoice { get; set; }
        public string InvoiceType { get; set; }
        public string CorrectionType { get; set; }
        public string OriginalInvoice { get; set; }
        public Nullable<System.Guid> OriginalInvoiceGuid { get; set; }
        public string TransactionCode { get; set; }
        public string Description { get; set; }
        public byte Rental { get; set; }
        public double CostTaxBasis { get; set; }
        public string Location { get; set; }
        public string Reference { get; set; }
        public string NIFRepresentative { get; set; }
        public string VATNumber { get; set; }
        public string CountryCode { get; set; }
        public string IDType { get; set; }
        public string IdentificationID { get; set; }
        public string ExemptionReason { get; set; }
        public string TaxTypeExempted { get; set; }
        public string NonSubjectedVAT { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string OffsetBankAccount { get; set; }
        public string Method { get; set; }
        public string TransactionNumber { get; set; }
        public byte ReversalTaxPerson { get; set; }
        public string IntraTransactionType { get; set; }
        public string Identifier { get; set; }
        public string EUCountryCode { get; set; }
        public string Address { get; set; }
        public byte ToSend { get; set; }
        public byte ToEdit { get; set; }
        public byte ToDelete { get; set; }
        public Nullable<int> BatchNumber { get; set; }
        public string Status { get; set; }
        public string Message { get; set; }
        public byte Sent { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public Nullable<System.DateTime> gbkmutSysCreated { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string DeliveryID { get; set; }
        public double AnnualFinalProrata { get; set; }
        public double AnnualRegularization { get; set; }
        public double RegularizedDeduction { get; set; }
        public string OriginalYourRefNumber { get; set; }
    }
}
