//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class evloc
    {
        public int ID { get; set; }
        public string magcode { get; set; }
        public string maglok { get; set; }
        public string oms30 { get; set; }
        public string type_loc { get; set; }
        public string pickbulk { get; set; }
        public byte intake { get; set; }
        public byte issue { get; set; }
        public string fixed_item { get; set; }
        public double min_stock { get; set; }
        public double max_stock { get; set; }
        public byte blocked_in { get; set; }
        public byte blocked_out { get; set; }
        public Nullable<double> NumberField1 { get; set; }
        public Nullable<double> NumberField2 { get; set; }
        public Nullable<double> NumberField3 { get; set; }
        public Nullable<double> NumberField4 { get; set; }
        public Nullable<double> NumberField5 { get; set; }
        public string TextField1 { get; set; }
        public string TextField2 { get; set; }
        public string TextField3 { get; set; }
        public string TextField4 { get; set; }
        public string TextField5 { get; set; }
        public Nullable<short> Division { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
        public byte[] timestamp { get; set; }
        public string CSPickITLocationType { get; set; }
        public int CSPickITPreference { get; set; }
    }
}
