//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExactTrialModules
    {
        public string ItemCode { get; set; }
        public string Description { get; set; }
        public int TermID { get; set; }
        public bool Active { get; set; }
        public System.DateTime ActivationDate { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public Nullable<short> Division { get; set; }
        public short Credit { get; set; }
    }
}
