//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class exeaCSPickitStockresView
    {
        public string Module { get; set; }
        public Nullable<int> ModuleTermID { get; set; }
        public string OrderNr { get; set; }
        public string ProductionOrderNr { get; set; }
        public Nullable<int> WMS_ID { get; set; }
        public string PickingState { get; set; }
        public string HTID { get; set; }
        public string TransType { get; set; }
        public string warehouse_name { get; set; }
        public string PickITModuleID { get; set; }
        public string ItemCode { get; set; }
        public string Warehouse { get; set; }
        public string Location { get; set; }
        public string CSPickITLocationType { get; set; }
        public string number { get; set; }
        public Nullable<double> Quantity { get; set; }
        public string OuterSKU { get; set; }
        public string InnerSKU { get; set; }
        public Nullable<System.Guid> ParentGUID { get; set; }
        public int IsAdvice { get; set; }
        public int IsBlocked { get; set; }
        public int IsOnScanner { get; set; }
        public string ParentTableName { get; set; }
        public int IsOffsetRec { get; set; }
        public int IsIssue { get; set; }
        public int IsTemp { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
        public byte[] timestamp { get; set; }
        public Nullable<byte> DirectStockCalculations { get; set; }
    }
}
