//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class exeaCSPickITgbkmutView
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public string Location { get; set; }
        public string Number { get; set; }
        public int GbkmutID { get; set; }
        public int GbkmutExID { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public string OuterSku { get; set; }
        public string InnerSku { get; set; }
        public string ScanUnit { get; set; }
        public int SkuItemID { get; set; }
        public byte DiscardQuantity { get; set; }
        public string CSPickITHandTerminalID { get; set; }
        public Nullable<int> CSPickITOrderPicker { get; set; }
        public string CSPickITState { get; set; }
        public int RFTransID { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
        public byte[] timestamp { get; set; }
        public string ItemCode { get; set; }
    }
}
