//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class exeaOrsrgAdviceView
    {
        public string ordernr { get; set; }
        public string OrdernrCollection { get; set; }
        public int orkrgID { get; set; }
        public int orsrgID { get; set; }
        public int Source { get; set; }
        public int isCollected { get; set; }
        public int HasAdvice { get; set; }
        public Nullable<int> NrOrdersInCollection { get; set; }
        public Nullable<int> CollectionID { get; set; }
        public string debnr { get; set; }
        public string debcode { get; set; }
        public string del_debtor_name { get; set; }
        public string artcode { get; set; }
        public string oms45 { get; set; }
        public string Itemcode { get; set; }
        public string ItemDescription { get; set; }
        public string ar_soort { get; set; }
        public string regel { get; set; }
        public Nullable<double> esr_aantal { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<System.DateTime> afldat { get; set; }
        public string Location { get; set; }
        public string OuterSku { get; set; }
        public string InnerSKU { get; set; }
        public string Number { get; set; }
        public string CSPickITState { get; set; }
        public byte uitgifte { get; set; }
        public string CSPickITOrderPicking { get; set; }
        public string MakeItemOrderPicking { get; set; }
        public Nullable<bool> IsFractionAllowedItem { get; set; }
        public Nullable<System.DateTime> afldat_orsrg { get; set; }
        public string ExplodeGUID { get; set; }
    }
}
