//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class facard
    {
        public System.DateTime activatedate { get; set; }
        public string artcode { get; set; }
        public string assetcode { get; set; }
        public string assetgroup { get; set; }
        public Nullable<System.Guid> attach_guid { get; set; }
        public string bedrnr { get; set; }
        public string Classification { get; set; }
        public string crdnr { get; set; }
        public int currqtyunits { get; set; }
        public double costlastmnt { get; set; }
        public double costlastmntfc { get; set; }
        public Nullable<System.Guid> debnr { get; set; }
        public string descr50_0 { get; set; }
        public string descr50_1 { get; set; }
        public string descr50_2 { get; set; }
        public string descr50_3 { get; set; }
        public string descr50_4 { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public string fiscalgroup { get; set; }
        public string freefield1 { get; set; }
        public Nullable<double> freefield10 { get; set; }
        public Nullable<int> freefield11 { get; set; }
        public Nullable<int> freefield12 { get; set; }
        public Nullable<int> freefield13 { get; set; }
        public Nullable<int> freefield14 { get; set; }
        public Nullable<int> freefield15 { get; set; }
        public Nullable<System.DateTime> freefield16 { get; set; }
        public Nullable<System.DateTime> freefield17 { get; set; }
        public Nullable<System.DateTime> freefield18 { get; set; }
        public string freefield19 { get; set; }
        public string freefield2 { get; set; }
        public string freefield20 { get; set; }
        public string freefield3 { get; set; }
        public string freefield4 { get; set; }
        public string freefield5 { get; set; }
        public Nullable<double> freefield6 { get; set; }
        public Nullable<double> freefield7 { get; set; }
        public Nullable<double> freefield8 { get; set; }
        public Nullable<double> freefield9 { get; set; }
        public int ID { get; set; }
        public string kstdrcode { get; set; }
        public string kstplcode { get; set; }
        public Nullable<System.DateTime> lastmntdate { get; set; }
        public double miscamt { get; set; }
        public double miscamtfc { get; set; }
        public Nullable<System.Guid> notesGuid { get; set; }
        public double origbkvalue { get; set; }
        public double origbkvaluefc { get; set; }
        public double origpurchamt { get; set; }
        public double origpurchamtfc { get; set; }
        public Nullable<System.Guid> parentid { get; set; }
        public byte passengercar { get; set; }
        public byte[] picture { get; set; }
        public string picturefilename { get; set; }
        public string pricelist { get; set; }
        public string primarymeth { get; set; }
        public string projectnr { get; set; }
        public string propertytype { get; set; }
        public Nullable<double> qtyrecd { get; set; }
        public string receiptnum { get; set; }
        public int res_id { get; set; }
        public double residualvalue { get; set; }
        public string secondarymeth { get; set; }
        public string Status { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.Guid sysguid { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public byte Tangible { get; set; }
        public Nullable<System.Guid> TransactionGuid { get; set; }
        public string usagestartper { get; set; }
        public string usagestartyear { get; set; }
        public string valcode { get; set; }
        public Nullable<double> exchrate { get; set; }
        public Nullable<System.Guid> AddressGUID { get; set; }
        public byte[] timestamp { get; set; }
    }
}
