//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class fadpre
    {
        public int ID { get; set; }
        public string assetcode { get; set; }
        public string assetpartnum { get; set; }
        public string valuation { get; set; }
        public string seqnum { get; set; }
        public string yearstart { get; set; }
        public string periodstart { get; set; }
        public string yearend { get; set; }
        public string periodend { get; set; }
        public string deprmeth { get; set; }
        public Nullable<System.DateTime> datestart { get; set; }
        public Nullable<System.DateTime> dateend { get; set; }
        public string valcode { get; set; }
        public double exchrate { get; set; }
        public string yearlastdepr { get; set; }
        public string periodlastdepr { get; set; }
        public double salvagevalue { get; set; }
        public double salvagevaluefc { get; set; }
        public double deprfactor { get; set; }
        public double switchacclevel { get; set; }
        public double cumdepr { get; set; }
        public double cumdeprfc { get; set; }
        public double firstdepramt { get; set; }
        public double firstdepramtfc { get; set; }
        public double origcumdepr { get; set; }
        public double origcumdeprfc { get; set; }
        public string numdeprpers { get; set; }
        public double purchamtstart { get; set; }
        public double purchamtstartfc { get; set; }
        public double purchamtend { get; set; }
        public double purchamtendfc { get; set; }
        public double bkvaluestart { get; set; }
        public double bkvaluestartfc { get; set; }
        public double bkvalueend { get; set; }
        public double bkvalueendfc { get; set; }
        public string hghrchgmethadj { get; set; }
        public string lwrchgmethadj { get; set; }
        public double currbkvalue { get; set; }
        public double currbkvaluefc { get; set; }
        public string artcode { get; set; }
        public Nullable<short> Division { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
        public byte[] timestamp { get; set; }
    }
}
