//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class fagrp
    {
        public int ID { get; set; }
        public string assetgroup { get; set; }
        public string descr50_0 { get; set; }
        public string descr50_1 { get; set; }
        public string descr50_2 { get; set; }
        public string descr50_3 { get; set; }
        public string descr50_4 { get; set; }
        public string primarymeth { get; set; }
        public string secondarymeth { get; set; }
        public string kstdrcode { get; set; }
        public string kstplcode { get; set; }
        public string reference1 { get; set; }
        public string reference2 { get; set; }
        public double valuelimit { get; set; }
        public string fiscalgroup { get; set; }
        public string AssetAC { get; set; }
        public string DeprBS { get; set; }
        public string DeprPL { get; set; }
        public string Extra { get; set; }
        public string SpecialDeprBS { get; set; }
        public string SpecialDeprPL { get; set; }
        public string WriteOffBalanceSheet { get; set; }
        public string WriteOffProfitLoss { get; set; }
        public string VATCorrectionJournal { get; set; }
        public string VATCorrectionExpenseGL { get; set; }
        public string VATCorrectionRevenueGL { get; set; }
        public string Rules { get; set; }
        public Nullable<short> Division { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
        public byte[] timestamp { get; set; }
    }
}
