//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class fatran
    {
        public int ID { get; set; }
        public string assetcode { get; set; }
        public string assetpartnum { get; set; }
        public string valuation { get; set; }
        public string tranyear { get; set; }
        public string tranper { get; set; }
        public string seqnum { get; set; }
        public string trantype { get; set; }
        public Nullable<System.DateTime> trandate { get; set; }
        public string assetgroup { get; set; }
        public int res_id { get; set; }
        public string kstdrcode { get; set; }
        public string kstplcode { get; set; }
        public string valcode { get; set; }
        public double exchrate { get; set; }
        public double tranamt { get; set; }
        public double tranamtfc { get; set; }
        public double tranperc { get; set; }
        public string olddataval { get; set; }
        public string newdataval { get; set; }
        public double purchamt { get; set; }
        public double purchamtfc { get; set; }
        public double purchamtpart { get; set; }
        public double purchamtpartfc { get; set; }
        public double bookvalue { get; set; }
        public double bookvaluefc { get; set; }
        public double bookvaluepart { get; set; }
        public double bookvaluepartfc { get; set; }
        public double revalamt { get; set; }
        public double revalamtfc { get; set; }
        public double revalamtpos { get; set; }
        public double revalamtposfc { get; set; }
        public double revalamtneg { get; set; }
        public double revalamtnegfc { get; set; }
        public double cumreval { get; set; }
        public double cumrevalfc { get; set; }
        public double cumrevalpos { get; set; }
        public double cumrevalposfc { get; set; }
        public double cumrevalneg { get; set; }
        public double cumrevalnegfc { get; set; }
        public double depramt { get; set; }
        public double depramtfc { get; set; }
        public double hghrdepramt { get; set; }
        public double hghrdepramtfc { get; set; }
        public double lwrdepramt { get; set; }
        public double lwrdepramtfc { get; set; }
        public double cumdepramt { get; set; }
        public double cumdepramtfc { get; set; }
        public double salvagevalue { get; set; }
        public double salvagevaluefc { get; set; }
        public string disposaltype { get; set; }
        public double disposalexp { get; set; }
        public double disposalexpfc { get; set; }
        public double salesamt { get; set; }
        public double salesamtfc { get; set; }
        public double plamount { get; set; }
        public double plamountfc { get; set; }
        public string dagbknr { get; set; }
        public string descr50 { get; set; }
        public string status { get; set; }
        public string jrnper { get; set; }
        public string jrnyear { get; set; }
        public double deprfactor { get; set; }
        public double deprcalcrate { get; set; }
        public string entrynumber { get; set; }
        public string fiscalgroup { get; set; }
        public string reknr { get; set; }
        public string deprmeth { get; set; }
        public Nullable<short> Division { get; set; }
        public System.DateTime syscreated { get; set; }
        public double depradjamt { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
        public byte[] timestamp { get; set; }
        public double depradjamtfc { get; set; }
        public string artcode { get; set; }
    }
}
