//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FiscalReports
    {
        public int ID { get; set; }
        public string FiscalAssetCode { get; set; }
        public string ItemCode { get; set; }
        public string FiscalDepreciationCode { get; set; }
        public string FiscalGroupCode { get; set; }
        public string CostCenter { get; set; }
        public string CostUnit { get; set; }
        public string Project { get; set; }
        public string StartYear { get; set; }
        public string EndYear { get; set; }
        public short FinancialYear { get; set; }
        public double InvestmentAmount { get; set; }
        public double ValuationAmount { get; set; }
        public double Revaluation { get; set; }
        public double TechnicalRevaluation { get; set; }
        public double PartialLiquidation { get; set; }
        public double AnnualDepreciation { get; set; }
        public double RoundedAnnualDepreciation { get; set; }
        public double CummulativeDepreciation { get; set; }
        public double WriteOff { get; set; }
        public double Disposal { get; set; }
        public double BookValue { get; set; }
        public double PartialLiquidatedBookValue { get; set; }
        public Nullable<short> Type { get; set; }
        public Nullable<System.DateTime> LiquidationDate { get; set; }
        public double DepreciationFactor { get; set; }
        public Nullable<short> Division { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public byte[] timestamp { get; set; }
    }
}
