//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FiscalTransactions
    {
        public int ID { get; set; }
        public System.DateTime PostingDate { get; set; }
        public string FinancialPeriod { get; set; }
        public short FinancialYear { get; set; }
        public double Amount { get; set; }
        public short Type { get; set; }
        public string Description { get; set; }
        public string FiscalAssetCode { get; set; }
        public string ItemCode { get; set; }
        public string FiscalGroupCode { get; set; }
        public string CostCenter { get; set; }
        public string CostUnit { get; set; }
        public string Project { get; set; }
        public Nullable<int> Resource { get; set; }
        public string FiscalPartCode { get; set; }
        public Nullable<short> Division { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public byte[] timestamp { get; set; }
    }
}
