//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormFieldMappings
    {
        public int ID { get; set; }
        public string TemplateName { get; set; }
        public string TemplateType { get; set; }
        public string Field { get; set; }
        public string LineType { get; set; }
        public string MappingType { get; set; }
        public Nullable<short> InputLength { get; set; }
        public string Value { get; set; }
        public string GLCode { get; set; }
        public string VATBox { get; set; }
        public string VATBoxType { get; set; }
        public string FieldDescription { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
    }
}
