//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class frhkrg
    {
        public int ID { get; set; }
        public string faknr { get; set; }
        public Nullable<System.DateTime> fakdat { get; set; }
        public string dagbknr { get; set; }
        public string debnr { get; set; }
        public string fakdebnr { get; set; }
        public string einddebnr { get; set; }
        public string refer { get; set; }
        public string refer1 { get; set; }
        public string refer2 { get; set; }
        public string refer3 { get; set; }
        public string ordernr { get; set; }
        public Nullable<System.DateTime> orddat { get; set; }
        public Nullable<System.DateTime> afldat { get; set; }
        public string magcode { get; set; }
        public string ex_artcode { get; set; }
        public byte inv_in_vv { get; set; }
        public string valcode { get; set; }
        public double koers { get; set; }
        public string orddeb { get; set; }
        public string selcode { get; set; }
        public byte nettoprijs { get; set; }
        public string betcond { get; set; }
        public string levwijze { get; set; }
        public double vrachtkost { get; set; }
        public double orderkost { get; set; }
        public string kstplcode { get; set; }
        public double fakt_kort { get; set; }
        public string user_id { get; set; }
        public string colli { get; set; }
        public double bruto_gew { get; set; }
        public double netto_gew { get; set; }
        public Nullable<short> bkjrcode { get; set; }
        public string btw_code { get; set; }
        public string pakbon_nr { get; set; }
        public double tot_bdr { get; set; }
        public string fak_soort { get; set; }
        public string iso_taalcd { get; set; }
        public string btw_cd_ord { get; set; }
        public Nullable<System.DateTime> pakbon_dat { get; set; }
        public string fak_adrnr { get; set; }
        public double ordkost_vv { get; set; }
        public double vrachtk_vv { get; set; }
        public double tot_bdr_vv { get; set; }
        public double tot_bdrb { get; set; }
        public double tot_bdrbvv { get; set; }
        public string afl_week { get; set; }
        public string routecode { get; set; }
        public int represent_id { get; set; }
        public string calc_meth_pc { get; set; }
        public string calc_incl_vat { get; set; }
        public double bdr_vat_ord_val { get; set; }
        public double bdr_vat_ship_val { get; set; }
        public double bdr_kb_val { get; set; }
        public double bdr_disc_val { get; set; }
        public double bdr_val { get; set; }
        public string docnumber { get; set; }
        public string projectnr { get; set; }
        public string paymentmethod { get; set; }
        public System.DateTime syscreated { get; set; }
        public Nullable<System.Guid> DocAttachmentID { get; set; }
        public string ord_debtor_name { get; set; }
        public string ord_AddressLine1 { get; set; }
        public string ord_AddressLine2 { get; set; }
        public string ord_AddressLine3 { get; set; }
        public string ord_PostCode { get; set; }
        public string ord_City { get; set; }
        public string ord_StateCode { get; set; }
        public string ord_landcode { get; set; }
        public string ord_Phone { get; set; }
        public string ord_Fax { get; set; }
        public string ord_contactperson { get; set; }
        public string ord_predcode { get; set; }
        public string ord_cnt_job_desc { get; set; }
        public string ord_Initials { get; set; }
        public string del_debtor_name { get; set; }
        public string del_AddressLine1 { get; set; }
        public string del_AddressLine2 { get; set; }
        public string del_AddressLine3 { get; set; }
        public string del_PostCode { get; set; }
        public string del_City { get; set; }
        public string del_StateCode { get; set; }
        public string del_landcode { get; set; }
        public string del_Phone { get; set; }
        public string del_Fax { get; set; }
        public string del_contactperson { get; set; }
        public string del_predcode { get; set; }
        public string del_cnt_job_desc { get; set; }
        public string del_Initials { get; set; }
        public string inv_debtor_name { get; set; }
        public string inv_AddressLine1 { get; set; }
        public string inv_AddressLine2 { get; set; }
        public string inv_AddressLine3 { get; set; }
        public string inv_PostCode { get; set; }
        public string inv_City { get; set; }
        public string inv_StateCode { get; set; }
        public string inv_landcode { get; set; }
        public string inv_Phone { get; set; }
        public string inv_Fax { get; set; }
        public string inv_contactperson { get; set; }
        public string inv_predcode { get; set; }
        public string inv_cnt_job_desc { get; set; }
        public string inv_Initials { get; set; }
        public int Approver { get; set; }
        public Nullable<System.DateTime> Approved { get; set; }
        public Nullable<System.Guid> DocumentID { get; set; }
        public string CashRegisterAccount { get; set; }
        public string inv_contactemail { get; set; }
        public string freefield1 { get; set; }
        public string freefield2 { get; set; }
        public string freefield3 { get; set; }
        public Nullable<double> freefield4 { get; set; }
        public Nullable<double> freefield5 { get; set; }
        public Nullable<double> TNTPostAmount { get; set; }
        public string TNTPostNrOfPages { get; set; }
        public string TNTPostQtySent { get; set; }
        public int TNTPostUserName { get; set; }
        public Nullable<System.DateTime> TNTPostDateSent { get; set; }
        public Nullable<int> TNTPostSession { get; set; }
        public string GoldenTaxInvoiceNumber { get; set; }
        public string ExternalNumber { get; set; }
        public Nullable<short> Division { get; set; }
        public Nullable<double> OfficialExchangeRate { get; set; }
        public byte ApplyLinkItem { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
        public byte[] timestamp { get; set; }
        public string del_County { get; set; }
        public bool AvalaraIsReconciled { get; set; }
        public bool UseAvalaraTaxation { get; set; }
        public bool IsEDI { get; set; }
        public Nullable<bool> Printed { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string CIPaymentCondition { get; set; }
        public Nullable<bool> ExcludePrinting { get; set; }
        public bool IsUseAdditionalFields { get; set; }
        public string AdditionalStatus { get; set; }
        public string CSPickITCWStatusCWDB { get; set; }
        public string VATNumber { get; set; }
        public string eSignature { get; set; }
    }
}
