//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class frhsrg
    {
        public int ID { get; set; }
        public string faknr { get; set; }
        public Nullable<System.DateTime> fakdat { get; set; }
        public string dagbknr { get; set; }
        public string regel { get; set; }
        public string artcode { get; set; }
        public string ar_soort { get; set; }
        public string oms45 { get; set; }
        public string magcode { get; set; }
        public string afl_week { get; set; }
        public Nullable<System.DateTime> afldat { get; set; }
        public double esr_aantal { get; set; }
        public byte ordreg { get; set; }
        public string btw_code { get; set; }
        public string prijslijst { get; set; }
        public double korting { get; set; }
        public double prijs_n { get; set; }
        public double prijs83 { get; set; }
        public string kstdrcode { get; set; }
        public double vvp { get; set; }
        public double pr_bedr { get; set; }
        public string kstplcode { get; set; }
        public string ordernr { get; set; }
        public string intra_nr { get; set; }
        public string pakbon_nr { get; set; }
        public string maglok { get; set; }
        public string prshisnr { get; set; }
        public Nullable<System.DateTime> pakbon_dat { get; set; }
        public string explsrtart { get; set; }
        public string verzdebnr { get; set; }
        public string vrz_adrcd { get; set; }
        public string vrz_adrnr { get; set; }
        public double koers { get; set; }
        public double bdr_ev_ed_val { get; set; }
        public double bdr_d_ev_val { get; set; }
        public double bdr_vat_val { get; set; }
        public double bdr_inv_d_val { get; set; }
        public string docnumber { get; set; }
        public string projectnr { get; set; }
        public int res_id { get; set; }
        public string serial_number { get; set; }
        public string unitcode { get; set; }
        public double unitfactor { get; set; }
        public string TaxCode2 { get; set; }
        public string TaxCode3 { get; set; }
        public string TaxCode4 { get; set; }
        public string TaxCode5 { get; set; }
        public double TaxBasis2 { get; set; }
        public double TaxBasis3 { get; set; }
        public double TaxBasis4 { get; set; }
        public double TaxBasis5 { get; set; }
        public double TaxAmount1 { get; set; }
        public double TaxAmount2 { get; set; }
        public double TaxAmount3 { get; set; }
        public double TaxAmount4 { get; set; }
        public double TaxAmount5 { get; set; }
        public Nullable<System.Guid> SalesOrderLine { get; set; }
        public string ReasonDiscount { get; set; }
        public string ReasonReturn { get; set; }
        public Nullable<System.Guid> InvoiceOrigin { get; set; }
        public double QuantityReturn { get; set; }
        public Nullable<System.Guid> LinkItemGuid { get; set; }
        public Nullable<short> Division { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
        public byte[] timestamp { get; set; }
        public string CSRekregLabelOms00 { get; set; }
        public string CSRekregLabelOms01 { get; set; }
        public string CSRekregLabelOms02 { get; set; }
        public string CSRekregLabelOms03 { get; set; }
        public string CSRekregLabelOms04 { get; set; }
        public string CSRekregLabelOms05 { get; set; }
        public string CSRekregLabelOms06 { get; set; }
        public string CSRekregLabelOms07 { get; set; }
        public string CSRekregLabelOms08 { get; set; }
        public string CSRekregLabelOms09 { get; set; }
        public string CSRekregLabelOms10 { get; set; }
        public Nullable<double> CSRekregValue00 { get; set; }
        public Nullable<double> CSRekregValue01 { get; set; }
        public Nullable<double> CSRekregValue02 { get; set; }
        public Nullable<double> CSRekregValue03 { get; set; }
        public Nullable<double> CSRekregValue04 { get; set; }
        public Nullable<double> CSRekregValue05 { get; set; }
        public Nullable<double> CSRekregValue06 { get; set; }
        public Nullable<double> CSRekregValue07 { get; set; }
        public Nullable<double> CSRekregValue08 { get; set; }
        public Nullable<double> CSRekregValue09 { get; set; }
        public Nullable<double> CSRekregValue10 { get; set; }
        public Nullable<double> CSRekregRoundedValue00 { get; set; }
        public Nullable<double> CSRekregRoundedValue01 { get; set; }
        public Nullable<double> CSRekregRoundedValue02 { get; set; }
        public Nullable<double> CSRekregRoundedValue03 { get; set; }
        public Nullable<double> CSRekregRoundedValue04 { get; set; }
        public Nullable<double> CSRekregRoundedValue05 { get; set; }
        public Nullable<double> CSRekregRoundedValue06 { get; set; }
        public Nullable<double> CSRekregRoundedValue07 { get; set; }
        public Nullable<double> CSRekregRoundedValue08 { get; set; }
        public Nullable<double> CSRekregRoundedValue09 { get; set; }
        public Nullable<double> CSRekregRoundedValue10 { get; set; }
        public string CSRekregRemark { get; set; }
        public string CSRekregFreeField01 { get; set; }
        public string CSRekregFreeField02 { get; set; }
        public string CSRekregFreeField03 { get; set; }
        public Nullable<System.DateTime> CSRekregFreeFieldDate { get; set; }
        public byte CSRekregFreeFieldNoYes01 { get; set; }
        public byte CSRekregFreeFieldNoYes02 { get; set; }
        public string ChargeLineType { get; set; }
        public double LineCharges { get; set; }
        public string CSRekregFormulaName { get; set; }
        public Nullable<int> RequestID { get; set; }
        public Nullable<System.Guid> SMSInvoiceLine { get; set; }
        public Nullable<System.DateTime> RequestedDelDate { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public Nullable<double> CollectiveInvoicesNumber { get; set; }
        public string InvoiceComments { get; set; }
        public Nullable<System.DateTime> eind_dat_c { get; set; }
    }
}
