//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class frvsrg
    {
        public int ID { get; set; }
        public string fakt_code { get; set; }
        public string volgnr5 { get; set; }
        public string regel { get; set; }
        public string artcode { get; set; }
        public string ar_soort { get; set; }
        public string oms45 { get; set; }
        public string magcode { get; set; }
        public string afl_week { get; set; }
        public double esr_aantal { get; set; }
        public string btw_code { get; set; }
        public string prijslijst { get; set; }
        public double korting { get; set; }
        public double prijs83 { get; set; }
        public double prijs_n { get; set; }
        public double lengte { get; set; }
        public double breedte { get; set; }
        public double hoogte { get; set; }
        public string dimensie { get; set; }
        public string kstdrcode { get; set; }
        public string project { get; set; }
        public string kstsrt { get; set; }
        public string pr_kstpl { get; set; }
        public double pr_aant { get; set; }
        public double pr_bedr { get; set; }
        public string kstplcode { get; set; }
        public string explsrtart { get; set; }
        public double gip_tekst { get; set; }
        public string prod_order { get; set; }
        public double extra_pr { get; set; }
        public string statistnr { get; set; }
        public string taric { get; set; }
        public string landoorspr { get; set; }
        public string landherk { get; set; }
        public string landbest { get; set; }
        public string landabc { get; set; }
        public string land_iso { get; set; }
        public string transact_a { get; set; }
        public string transact_b { get; set; }
        public string vervoer { get; set; }
        public string plts_ll { get; set; }
        public string stelsel { get; set; }
        public string int_regio { get; set; }
        public string intra_lvcd { get; set; }
        public string trsshpm_cd { get; set; }
        public byte container { get; set; }
        public double stateenh_i { get; set; }
        public double gewicht_bi { get; set; }
        public string boecode { get; set; }
        public string affiliates { get; set; }
        public string csacode { get; set; }
        public string TaxCode2 { get; set; }
        public string TaxCode3 { get; set; }
        public string TaxCode4 { get; set; }
        public string TaxCode5 { get; set; }
        public Nullable<short> Division { get; set; }
        public string ProjectNr { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
        public byte[] timestamp { get; set; }
    }
}
