//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class GbkItem201608110816394
    {
        public string warehouse { get; set; }
        public string artcode { get; set; }
        public string reknr { get; set; }
        public Nullable<System.DateTime> datum { get; set; }
        public string transtype { get; set; }
        public int ID { get; set; }
        public string transsubtype { get; set; }
        public string freefield1 { get; set; }
        public byte reviewed { get; set; }
        public string bud_vers { get; set; }
        public byte Checked { get; set; }
        public byte Blockitem { get; set; }
        public double aantal { get; set; }
        public double bdr_hfl { get; set; }
        public string StockTrackingNumber { get; set; }
    }
}
