//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class GbkmutOutStandingView_110015
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> RptDate { get; set; }
        public string InvoiceNumber { get; set; }
        public string ExternalNumber { get; set; }
        public string SupplierInvoiceNumber { get; set; }
        public string Description { get; set; }
        public Nullable<double> AmountDC { get; set; }
        public string TCCode { get; set; }
        public string Valcode { get; set; }
        public Nullable<double> AmountTC { get; set; }
        public string PaymentType { get; set; }
        public string Type { get; set; }
        public string status { get; set; }
        public string TransactionType { get; set; }
        public string OrderNumber { get; set; }
        public string dagbknr { get; set; }
        public string EntryNumber { get; set; }
        public string LedgerAccount { get; set; }
        public string DebtorNumber { get; set; }
        public string CreditorNumber { get; set; }
        public Nullable<double> InvoiceAmount { get; set; }
        public Nullable<int> ReminderLayout { get; set; }
        public Nullable<System.DateTime> LastReminderDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string TransactionNumber { get; set; }
        public Nullable<int> BatchNumber { get; set; }
        public string OwnBankAccount { get; set; }
        public string OffsetBankAccount { get; set; }
        public string OffsetLedgerAccountNumber { get; set; }
        public string PaymentCondition { get; set; }
        public int ForeignPayment { get; set; }
        public string OffsetReference { get; set; }
        public Nullable<double> ExchangeRate { get; set; }
        public Nullable<int> Document { get; set; }
        public string InvoiceCurrency { get; set; }
        public int AmountBAC { get; set; }
        public Nullable<double> InvoiceExchangeRate { get; set; }
        public Nullable<byte> Blocked { get; set; }
        public string cmp_fax { get; set; }
        public string AccountCode { get; set; }
        public string cmp_status { get; set; }
        public string cmp_name { get; set; }
        public string cmp_fctry { get; set; }
        public string adres1 { get; set; }
        public string postcode { get; set; }
        public string woonpl { get; set; }
        public string dc_telnr { get; set; }
        public string cntpers1 { get; set; }
        public string BankAccountNumber { get; set; }
        public string paymentmethod { get; set; }
        public string classificationID { get; set; }
        public double creditline { get; set; }
        public string postbanknumber { get; set; }
        public string prdcode1 { get; set; }
        public string lnd_oms60 { get; set; }
        public string cat_oms30 { get; set; }
        public Nullable<double> Termperc { get; set; }
        public int PayIntr { get; set; }
        public System.DateTime DistributionDate { get; set; }
        public string Project { get; set; }
        public string CostCenter { get; set; }
        public int DCPrecision { get; set; }
    }
}
