//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class genlibros
    {
        public int ID { get; set; }
        public string Linea { get; set; }
        public string Fecha { get; set; }
        public string FechaInf { get; set; }
        public string ClaveLinea { get; set; }
        public string Nombre { get; set; }
        public string Concepto { get; set; }
        public Nullable<decimal> Debe { get; set; }
        public Nullable<decimal> Haber { get; set; }
        public Nullable<decimal> Base { get; set; }
        public Nullable<decimal> Porcentaje { get; set; }
        public Nullable<decimal> Cuota { get; set; }
        public Nullable<decimal> PagoCobro { get; set; }
        public string FechaPagoCobro { get; set; }
        public string MetodoPagoCobro { get; set; }
        public string DescripcionPagoCobro { get; set; }
    }
}
