//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoldenTaxHeader
    {
        public int ID { get; set; }
        public string GTNumber { get; set; }
        public double TotalIncVAT { get; set; }
        public double TotalExcVAT { get; set; }
        public double TotalVAT { get; set; }
        public bool Authorized { get; set; }
        public bool Completed { get; set; }
        public Nullable<System.DateTime> ExportDate { get; set; }
        public string ActualGTNumber { get; set; }
        public Nullable<System.DateTime> ActualPrintDate { get; set; }
        public string Invdebnr { get; set; }
        public Nullable<System.Guid> GTHeaderguid { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
        public Nullable<System.Guid> GTGroupguid { get; set; }
    }
}
