//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRV_InvoiceHistory
    {
        public int ID { get; set; }
        public Nullable<short> Invoice_Year { get; set; }
        public Nullable<int> Invoice_Month { get; set; }
        public string Debtor_Code { get; set; }
        public Nullable<int> Representative { get; set; }
        public string Invoice_Number { get; set; }
        public string Journal { get; set; }
        public string Order_Number { get; set; }
        public string Currency { get; set; }
        public double Invoice_Amount_Ex_VAT { get; set; }
        public Nullable<System.DateTime> Invoice_Date { get; set; }
    }
}
