//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRV_InvoiceHistoryLines
    {
        public int ID { get; set; }
        public Nullable<int> Invoice_Year { get; set; }
        public Nullable<int> Invoice_Month { get; set; }
        public Nullable<System.DateTime> Invoice_Date { get; set; }
        public string Invoice_Number { get; set; }
        public string Journal { get; set; }
        public string Debtor_Code { get; set; }
        public string Itemcode { get; set; }
        public double Numbers { get; set; }
        public double DiscountPercentage { get; set; }
        public double Price_Net { get; set; }
        public double Price_Gross { get; set; }
        public double Price_Cost { get; set; }
        public double Margin { get; set; }
        public double Amount_Revenue { get; set; }
        public double Amount_Costprice { get; set; }
        public double Amount_Margin { get; set; }
        public double Amount_Discount { get; set; }
    }
}
