//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRV_Audit_UserToRoles
    {
        public string LoginName { get; set; }
        public string UserFullname { get; set; }
        public int RoleID { get; set; }
        public string RoleID2 { get; set; }
        public string Rolename { get; set; }
        public string Access { get; set; }
    }
}
