//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRV_DebtorToBeInvoiced
    {
        public string Debtor_Code { get; set; }
        public Nullable<System.DateTime> Invoice_Date { get; set; }
        public Nullable<short> Year { get; set; }
        public string Period { get; set; }
        public string Order_Number { get; set; }
        public double To_be_invoiced_amount { get; set; }
    }
}
