//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRV_Audit_ChangesDebtorBankaccount
    {
        public string FieldName { get; set; }
        public string Debtor { get; set; }
        public string Modifier { get; set; }
        public System.DateTime Modified { get; set; }
        public string Oldvalue { get; set; }
        public string NewValue { get; set; }
    }
}
