//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRV_CompanyDetails
    {
        public string Companycode { get; set; }
        public string Companyname { get; set; }
        public int Batchlevel { get; set; }
        public int Release { get; set; }
        public string CompanyAddress { get; set; }
        public string CompanyCity { get; set; }
    }
}
