//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRV_SalesItems
    {
        public string ItemCode { get; set; }
        public string Supplier { get; set; }
        public string SupplierCode { get; set; }
        public string Item_Description { get; set; }
        public string Item_Unit { get; set; }
        public Nullable<double> Sales_Price { get; set; }
        public double Standard_Cost_Price { get; set; }
        public Nullable<double> Purchase_Price { get; set; }
        public int Item_Group { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Last_Date_Delivered { get; set; }
        public string Assortment_1 { get; set; }
        public string Assortment_1_Property { get; set; }
        public string Assortment_2 { get; set; }
        public string Assortment_2_Property { get; set; }
        public string Assortment_3 { get; set; }
        public string Assortment_3_Property { get; set; }
        public string Assortment_4 { get; set; }
        public string Assortment_4_Property { get; set; }
        public string Assortment_5 { get; set; }
        public string Assortment_5_Property { get; set; }
        public string Assortment_6 { get; set; }
        public string Assortment_6_Property { get; set; }
        public string Assortment_7 { get; set; }
        public string Assortment_7_Property { get; set; }
        public string Assortment_8 { get; set; }
        public string Assortment_8_Property { get; set; }
        public string Assortment_9 { get; set; }
        public string Assortment_9_Property { get; set; }
        public string Assortment_10 { get; set; }
        public string Assortment_10_Property { get; set; }
        public string User_Text_Field_1 { get; set; }
        public string User_Text_Field_2 { get; set; }
        public string User_Text_Field_3 { get; set; }
        public string User_Text_Field_4 { get; set; }
        public string User_Text_Field_5 { get; set; }
        public string User_Text_Field_6 { get; set; }
        public string User_Text_Field_7 { get; set; }
        public string User_Text_Field_8 { get; set; }
        public string User_Text_Field_9 { get; set; }
        public string User_Text_Field_10 { get; set; }
        public Nullable<System.DateTime> User_Date_Field_1 { get; set; }
        public Nullable<System.DateTime> User_Date_Field_2 { get; set; }
        public Nullable<System.DateTime> User_Date_Field_3 { get; set; }
        public Nullable<System.DateTime> User_Date_Field_4 { get; set; }
        public Nullable<System.DateTime> User_Date_Field_5 { get; set; }
        public Nullable<double> User_Number_Field_1 { get; set; }
        public Nullable<double> User_Number_Field_2 { get; set; }
        public Nullable<double> User_Number_Field_3 { get; set; }
        public Nullable<double> User_Number_Field_4 { get; set; }
        public Nullable<double> User_Number_Field_5 { get; set; }
        public Nullable<double> User_Number_Field_6 { get; set; }
        public Nullable<double> User_Number_Field_7 { get; set; }
        public Nullable<double> User_Number_Field_8 { get; set; }
        public Nullable<double> User_Number_Field_9 { get; set; }
        public Nullable<double> User_Number_Field_10 { get; set; }
        public bool User_YesNo_Field_1 { get; set; }
        public bool User_YesNo_Field_2 { get; set; }
        public bool User_YesNo_Field_3 { get; set; }
        public bool User_YesNo_Field_4 { get; set; }
        public bool User_YesNo_Field_5 { get; set; }
    }
}
