//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRV_Stock_PurchaseLines
    {
        public string Order_Number { get; set; }
        public string ItemCode { get; set; }
        public Nullable<double> Quantity { get; set; }
        public string Warehouse { get; set; }
        public string Creditor_Code { get; set; }
        public Nullable<double> Purchase_Price { get; set; }
        public string Currency { get; set; }
        public Nullable<System.DateTime> Order_date { get; set; }
        public Nullable<double> Order_Amount { get; set; }
        public Nullable<double> Quantity_Received { get; set; }
        public Nullable<double> Amount_Received { get; set; }
        public Nullable<System.DateTime> Purchase_Date_Last_Received { get; set; }
        public Nullable<double> Purchase_Quantity_Invoiced { get; set; }
        public Nullable<double> Purchase_Amount_Invoiced { get; set; }
        public Nullable<System.DateTime> Purchase_Last_Invoice_Date { get; set; }
        public string Invoice_Number_Last { get; set; }
        public string Status { get; set; }
    }
}
