//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrcomp_trans
    {
        public int ID { get; set; }
        public Nullable<short> PayrollYear { get; set; }
        public int res_id { get; set; }
        public short period { get; set; }
        public short RunNumber { get; set; }
        public System.DateTime calculationdate { get; set; }
        public string comp_code { get; set; }
        public string country { get; set; }
        public string currency { get; set; }
        public string comp_type { get; set; }
        public string comp_sub_type { get; set; }
        public string status { get; set; }
        public string payment_period { get; set; }
        public string entryorigin { get; set; }
        public string paid_by { get; set; }
        public string unit { get; set; }
        public double entry_amount { get; set; }
        public double entry_percentage { get; set; }
        public double number { get; set; }
        public double hourlywage { get; set; }
        public double number_days_period { get; set; }
        public double number_days_absent { get; set; }
        public double amount_to_be_paid { get; set; }
        public double amount_costs { get; set; }
        public double base_value { get; set; }
        public double calc_country_float1 { get; set; }
        public double calc_country_float2 { get; set; }
        public double calc_country_float3 { get; set; }
        public string creditor_account { get; set; }
        public string creditor_costcenter { get; set; }
        public string creditor_costunit { get; set; }
        public string ledger_account { get; set; }
        public string ledger_costcenter { get; set; }
        public string ledger_costunit { get; set; }
        public string creditor { get; set; }
        public string bankaccount { get; set; }
        public string companycode { get; set; }
        public byte declaration_made { get; set; }
        public Nullable<System.DateTime> declaration_date { get; set; }
        public string declaration_number { get; set; }
        public string country_char1 { get; set; }
        public string country_char2 { get; set; }
        public string country_char3 { get; set; }
        public string country_char4 { get; set; }
        public string country_char5 { get; set; }
        public string country_char6 { get; set; }
        public string country_char7 { get; set; }
        public string country_char8 { get; set; }
        public string country_char9 { get; set; }
        public byte country_ny1 { get; set; }
        public byte country_ny2 { get; set; }
        public byte country_ny3 { get; set; }
        public byte country_ny4 { get; set; }
        public byte country_ny5 { get; set; }
        public byte country_ny6 { get; set; }
        public byte country_ny7 { get; set; }
        public byte country_ny8 { get; set; }
        public byte country_ny9 { get; set; }
        public byte country_ny10 { get; set; }
        public byte country_ny11 { get; set; }
        public byte country_ny12 { get; set; }
        public byte country_ny13 { get; set; }
        public byte country_ny14 { get; set; }
        public byte country_ny15 { get; set; }
        public byte country_ny16 { get; set; }
        public byte country_ny17 { get; set; }
        public byte country_ny18 { get; set; }
        public double country_float1 { get; set; }
        public double country_float2 { get; set; }
        public double country_float3 { get; set; }
        public double country_float4 { get; set; }
        public double country_float5 { get; set; }
        public double country_float6 { get; set; }
        public string country_string1 { get; set; }
        public Nullable<System.Guid> DocAttachmentID { get; set; }
        public Nullable<System.Guid> notes { get; set; }
        public string deviating_descr50 { get; set; }
        public string formulafield { get; set; }
        public string yourreference { get; set; }
        public string ourreference { get; set; }
        public string project { get; set; }
        public string StateCode { get; set; }
        public string LocalCode { get; set; }
        public short Priority { get; set; }
        public string ReferenceNr1 { get; set; }
        public string ReferenceNr2 { get; set; }
        public string ItemCode { get; set; }
        public double number_days_component { get; set; }
        public Nullable<System.Guid> ComponentGuid { get; set; }
        public short contract { get; set; }
        public Nullable<short> declaration_period { get; set; }
        public Nullable<short> declaration_sequence { get; set; }
        public Nullable<System.DateTime> VoidDate { get; set; }
        public Nullable<short> Division { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
        public byte[] timestamp { get; set; }
    }
}
