//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrfint
    {
        public int ID { get; set; }
        public string comp_type { get; set; }
        public string fingroup { get; set; }
        public string descr50_0 { get; set; }
        public string descr50_1 { get; set; }
        public string descr50_2 { get; set; }
        public string descr50_3 { get; set; }
        public string descr50_4 { get; set; }
        public string glac { get; set; }
        public string unit { get; set; }
        public byte employee_ny { get; set; }
        public byte employer_ny { get; set; }
        public string pay_period { get; set; }
        public string gn { get; set; }
        public string country { get; set; }
        public double def_amt { get; set; }
        public string @fixed { get; set; }
        public Nullable<int> notes { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
        public byte[] timestamp { get; set; }
        public Nullable<System.Guid> DocID { get; set; }
        public byte payroll { get; set; }
        public string toe_srt { get; set; }
        public string gbknr2 { get; set; }
        public int scale { get; set; }
        public string currency { get; set; }
        public bool DefAmtEditable { get; set; }
        public string MainType { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string JobActivity { get; set; }
        public Nullable<short> Division { get; set; }
    }
}
