//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrloc
    {
        public int ID { get; set; }
        public string loc { get; set; }
        public string descr50 { get; set; }
        public string street_0 { get; set; }
        public string street_1 { get; set; }
        public string addr_no { get; set; }
        public string addr_suf { get; set; }
        public string postcode { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public string telnr { get; set; }
        public string faxnr { get; set; }
        public string xaddress2 { get; set; }
        public string StateCode { get; set; }
        public int WeekendStart { get; set; }
        public int WeekendEnd { get; set; }
        public Nullable<short> Division { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
        public byte[] timestamp { get; set; }
    }
}
