//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRMCompetenceProfiles
    {
        public System.Guid ID { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string JobGroup { get; set; }
        public string JobActivity { get; set; }
        public string JobTitle { get; set; }
        public string Project { get; set; }
        public string ItemCode { get; set; }
        public Nullable<int> ResourceId { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<int> ReviewerId { get; set; }
        public string Status { get; set; }
        public Nullable<short> Division { get; set; }
        public string Rating { get; set; }
        public Nullable<System.Guid> RequestId { get; set; }
        public Nullable<System.DateTime> RequestStartDate { get; set; }
        public string CompanyCode { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
