//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRMCompetenceLinks
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> CompetenceId { get; set; }
        public Nullable<System.Guid> ProfileId { get; set; }
        public Nullable<System.Guid> FormElementId { get; set; }
        public string StringValue { get; set; }
        public Nullable<double> DoubleValue { get; set; }
        public Nullable<System.DateTime> DateValue { get; set; }
        public Nullable<bool> YesNoValue { get; set; }
        public Nullable<short> SelectionValue { get; set; }
        public Nullable<System.Guid> GuidValue { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<short> Division { get; set; }
        public short GroupSequenceNr { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
