//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRMFieldTypes
    {
        public System.Guid ID { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public string Notes { get; set; }
        public string DefaultStringValue { get; set; }
        public Nullable<double> DefaultDoubleValue { get; set; }
        public Nullable<System.DateTime> DefaultDateValue { get; set; }
        public Nullable<bool> DefaultYesNoValue { get; set; }
        public Nullable<short> DefaultSelectionValue { get; set; }
        public Nullable<System.Guid> DefaultGuidValue { get; set; }
        public byte Decimals { get; set; }
        public Nullable<short> Division { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
