//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRMSelectionValues
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> FieldTypeId { get; set; }
        public short SequenceNumber { get; set; }
        public short Value { get; set; }
        public string DisplayValue { get; set; }
        public string Description { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<double> Maximum { get; set; }
        public Nullable<double> Minimum { get; set; }
        public string Notes { get; set; }
        public Nullable<short> Division { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
