//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class humres
    {
        public int ID { get; set; }
        public int res_id { get; set; }
        public string fullname { get; set; }
        public string sur_name { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string initialen { get; set; }
        public string mv1 { get; set; }
        public string adres1 { get; set; }
        public string adres2 { get; set; }
        public string woonpl { get; set; }
        public string postcode { get; set; }
        public string land_iso { get; set; }
        public string iso_taalcd { get; set; }
        public string mail { get; set; }
        public string telnr_prv { get; set; }
        public string telnr_prv2 { get; set; }
        public string telnr_werk { get; set; }
        public string telnr_werk2 { get; set; }
        public string faxnr { get; set; }
        public string kamer { get; set; }
        public string toestel { get; set; }
        public string funcnivo { get; set; }
        public string socsec_nr { get; set; }
        public Nullable<System.DateTime> geb_ldat { get; set; }
        public string geb_pl { get; set; }
        public Nullable<System.DateTime> ldatindienst { get; set; }
        public Nullable<System.DateTime> ldatuitdienst { get; set; }
        public string usr_id { get; set; }
        public byte blocked { get; set; }
        public int repto_id { get; set; }
        public string nat { get; set; }
        public string mar_stat { get; set; }
        public Nullable<System.DateTime> mar_date { get; set; }
        public string addr_no { get; set; }
        public string email { get; set; }
        public string job_title { get; set; }
        public string loc { get; set; }
        public string comp { get; set; }
        public string task { get; set; }
        public string emp_type { get; set; }
        public Nullable<System.DateTime> emp_statd { get; set; }
        public string prob_per { get; set; }
        public string prob_pert { get; set; }
        public Nullable<System.DateTime> prob_endd { get; set; }
        public Nullable<int> notes { get; set; }
        public string reason_resign { get; set; }
        public string crcard_type { get; set; }
        public string crcard_no { get; set; }
        public Nullable<System.DateTime> crcard_expd { get; set; }
        public string addr_xtra { get; set; }
        public Nullable<System.DateTime> cont_end_date { get; set; }
        public string workstat { get; set; }
        public string workstat_addr { get; set; }
        public byte buyer { get; set; }
        public byte representative { get; set; }
        public byte projempl { get; set; }
        public string maiden_name { get; set; }
        public string prafd_code { get; set; }
        public double inttar { get; set; }
        public double exttar { get; set; }
        public int job_level { get; set; }
        public byte payempl { get; set; }
        public string identiteit { get; set; }
        public string kstdr_code { get; set; }
        public string uitk_code { get; set; }
        public string extra_text { get; set; }
        public string extra_code { get; set; }
        public string adv_code { get; set; }
        public string slip_tekst { get; set; }
        public string predcode { get; set; }
        public string costcenter { get; set; }
        public string crdnr { get; set; }
        public string bankac_0 { get; set; }
        public string bankac_1 { get; set; }
        public string valcode { get; set; }
        public double pur_limit { get; set; }
        public double fte { get; set; }
        public string picturefilename { get; set; }
        public string freefield1 { get; set; }
        public string freefield2 { get; set; }
        public string freefield3 { get; set; }
        public string freefield4 { get; set; }
        public string freefield5 { get; set; }
        public Nullable<System.DateTime> freefield6 { get; set; }
        public Nullable<System.DateTime> freefield7 { get; set; }
        public Nullable<System.DateTime> freefield8 { get; set; }
        public Nullable<System.DateTime> freefield9 { get; set; }
        public Nullable<System.DateTime> freefield10 { get; set; }
        public double freefield11 { get; set; }
        public double freefield12 { get; set; }
        public double freefield13 { get; set; }
        public double freefield14 { get; set; }
        public double freefield15 { get; set; }
        public byte freefield16 { get; set; }
        public byte freefield17 { get; set; }
        public byte freefield18 { get; set; }
        public byte freefield19 { get; set; }
        public byte freefield20 { get; set; }
        public string emp_stat { get; set; }
        public int absent { get; set; }
        public int assistant { get; set; }
        public Nullable<System.Guid> cmp_wwn { get; set; }
        public string internetac { get; set; }
        public string mobile_short { get; set; }
        public string rating { get; set; }
        public string UserGroup { get; set; }
        public byte[] Picture { get; set; }
        public string btw_nummer { get; set; }
        public Nullable<byte> IsPersonalAccount { get; set; }
        public int Scale { get; set; }
        public byte[] Signature { get; set; }
        public string SignatureFile { get; set; }
        public double BankingLimit { get; set; }
        public string OldNTFullName { get; set; }
        public Nullable<int> TimeZone { get; set; }
        public bool SynchronizeExchange { get; set; }
        public string StateCode { get; set; }
        public string ChildName1 { get; set; }
        public Nullable<System.DateTime> ChildBirthDate1 { get; set; }
        public string ChildName2 { get; set; }
        public Nullable<System.DateTime> ChildBirthDate2 { get; set; }
        public string ChildName3 { get; set; }
        public Nullable<System.DateTime> ChildBirthDate3 { get; set; }
        public string ChildName4 { get; set; }
        public Nullable<System.DateTime> ChildBirthDate4 { get; set; }
        public string ChildName5 { get; set; }
        public Nullable<System.DateTime> ChildBirthDate5 { get; set; }
        public string Partner { get; set; }
        public Nullable<System.DateTime> PartnerBirthDate { get; set; }
        public string ItemCode { get; set; }
        public string usr_id2 { get; set; }
        public string MainLoc { get; set; }
        public string prefix { get; set; }
        public string affix { get; set; }
        public string birth_prefix { get; set; }
        public string birth_affix { get; set; }
        public string predcode2 { get; set; }
        public string land_iso2 { get; set; }
        public string race { get; set; }
        public double SalesLimit { get; set; }
        public double InvoiceLimit { get; set; }
        public double RMALimit { get; set; }
        public string SkypeID { get; set; }
        public string MsnID { get; set; }
        public Nullable<System.DateTime> VacancyStartDate { get; set; }
        public string ApplicationStage { get; set; }
        public Nullable<short> Division { get; set; }
        public byte BackOfficeBlocked { get; set; }
        public short ProcessedByBackgroundJob { get; set; }
        public string VacancyType { get; set; }
        public string Classification { get; set; }
        public string JobCategory { get; set; }
        public Nullable<System.DateTime> AdjustedHireDate { get; set; }
        public int PortalCreator { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
        public byte[] timestamp { get; set; }
        public Nullable<int> CSIIR_Responsible { get; set; }
    }
}
