//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternalYearStatements
    {
        public System.Guid ID { get; set; }
        public string Country { get; set; }
        public string CompanyType { get; set; }
        public string TemplateType { get; set; }
        public int SeqNr { get; set; }
        public Nullable<bool> NewPage { get; set; }
        public string Section { get; set; }
        public string LineType { get; set; }
        public string Level1 { get; set; }
        public string Level2 { get; set; }
        public string Level3 { get; set; }
        public string Language { get; set; }
        public string Description { get; set; }
        public string BalanceSign { get; set; }
        public string BalanceCode { get; set; }
        public Nullable<int> CalculationSeqNr { get; set; }
        public string BalanceCodeTotal { get; set; }
        public string Operator { get; set; }
        public string BalanceCodeAlternate { get; set; }
        public string ControlCode { get; set; }
        public string ControlType { get; set; }
        public string Expression { get; set; }
        public Nullable<bool> PreviousYear { get; set; }
    }
}
