//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemDivisions
    {
        public int ID { get; set; }
        public string DivisionCode { get; set; }
        public string ItemCode { get; set; }
        public string GLAccountRevenue { get; set; }
        public string GLAccountCost { get; set; }
        public string GLAccountDistribution { get; set; }
        public string GLAccountAsset { get; set; }
        public string SalesVatCode { get; set; }
        public string PurchaseVatCode { get; set; }
        public Nullable<short> Division { get; set; }
    }
}
