//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemRelations
    {
        public System.Guid ID { get; set; }
        public int Type { get; set; }
        public string ItemCode { get; set; }
        public string ItemCodeRelated { get; set; }
        public byte[] timestamp { get; set; }
        public double Quantity { get; set; }
        public Nullable<short> Division { get; set; }
        public System.Guid sysguid { get; set; }
        public int IDCol { get; set; }
    }
}
