//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemUnits
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string Unit { get; set; }
        public string UnitType { get; set; }
        public byte active { get; set; }
        public Nullable<short> Division { get; set; }
        public System.Guid sysguid { get; set; }
        public string Description_0 { get; set; }
        public string Description_1 { get; set; }
        public string Description_2 { get; set; }
        public string Description_3 { get; set; }
        public string Description_4 { get; set; }
    }
}
