//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemAssortment
    {
        public int ID { get; set; }
        public int Assortment { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public int SecurityLevel { get; set; }
        public Nullable<int> PriceSecurityLevel { get; set; }
        public Nullable<int> OwnerPerson { get; set; }
        public bool UseReleases { get; set; }
        public bool UseTranslations { get; set; }
        public bool UseCountries { get; set; }
        public bool UseCatalog { get; set; }
        public string CatalogItemSelection { get; set; }
        public int CatalogOrder { get; set; }
        public Nullable<int> CatalogClass_1 { get; set; }
        public Nullable<int> CatalogClass_2 { get; set; }
        public Nullable<int> CatalogClass_3 { get; set; }
        public bool UseContract { get; set; }
        public string ContractItemSelection { get; set; }
        public Nullable<int> ContractDocGroup { get; set; }
        public string ContractDocCategory { get; set; }
        public string ContractDocSubCategory { get; set; }
        public int ContractDocSecurity { get; set; }
        public string ContractComponentProgID { get; set; }
        public string ContractComponentParameter { get; set; }
        public bool ContractReleaseMandatory { get; set; }
        public string Note { get; set; }
        public byte[] Picture { get; set; }
        public string PictureFilename { get; set; }
        public bool AllowInCatalog { get; set; }
        public bool AllowNewItem { get; set; }
        public bool AllowNewContract { get; set; }
        public bool AllowNewDocument { get; set; }
        public string LabelUserField_01 { get; set; }
        public string LabelUserField_02 { get; set; }
        public string LabelUserField_03 { get; set; }
        public string LabelUserField_04 { get; set; }
        public string LabelUserField_05 { get; set; }
        public string LabelUserField_06 { get; set; }
        public string LabelUserField_07 { get; set; }
        public string LabelUserField_08 { get; set; }
        public string LabelUserField_09 { get; set; }
        public string LabelUserField_10 { get; set; }
        public string LabelUserDate_01 { get; set; }
        public string LabelUserDate_02 { get; set; }
        public string LabelUserDate_03 { get; set; }
        public string LabelUserDate_04 { get; set; }
        public string LabelUserDate_05 { get; set; }
        public string LabelUserNumber_01 { get; set; }
        public string LabelUserNumber_02 { get; set; }
        public string LabelUserNumber_03 { get; set; }
        public string LabelUserNumber_04 { get; set; }
        public string LabelUserNumber_05 { get; set; }
        public string LabelUserYesNo_01 { get; set; }
        public string LabelUserYesNo_02 { get; set; }
        public string LabelUserYesNo_03 { get; set; }
        public string LabelUserYesNo_04 { get; set; }
        public string LabelUserYesNo_05 { get; set; }
        public string LabelNUserField_01 { get; set; }
        public string LabelNUserField_02 { get; set; }
        public string LabelNUserField_03 { get; set; }
        public string LabelNUserField_04 { get; set; }
        public string LabelNUserField_05 { get; set; }
        public string LabelNUserField_06 { get; set; }
        public string LabelNUserField_07 { get; set; }
        public string LabelNUserField_08 { get; set; }
        public string LabelNUserField_09 { get; set; }
        public string LabelNUserField_10 { get; set; }
        public string LabelNUserDate_01 { get; set; }
        public string LabelNUserDate_02 { get; set; }
        public string LabelNUserDate_03 { get; set; }
        public string LabelNUserDate_04 { get; set; }
        public string LabelNUserDate_05 { get; set; }
        public string LabelNUserNumber_01 { get; set; }
        public string LabelNUserNumber_02 { get; set; }
        public string LabelNUserNumber_03 { get; set; }
        public string LabelNUserNumber_04 { get; set; }
        public string LabelNUserNumber_05 { get; set; }
        public string LabelNUserYesNo_01 { get; set; }
        public string LabelNUserYesNo_02 { get; set; }
        public string LabelNUserYesNo_03 { get; set; }
        public string LabelNUserYesNo_04 { get; set; }
        public string LabelNUserYesNo_05 { get; set; }
        public string StatNumber { get; set; }
        public string Costunit { get; set; }
        public string GLRevenue { get; set; }
        public string GLDeferredRevenue { get; set; }
        public string GLDeferredCost { get; set; }
        public string GLRecognizeCosts { get; set; }
        public string GLDiscount { get; set; }
        public string GLCostOfGoodsSold { get; set; }
        public string GLStock { get; set; }
        public string GLPriceDifference { get; set; }
        public string Description_0 { get; set; }
        public string Description_1 { get; set; }
        public string Description_2 { get; set; }
        public string Description_3 { get; set; }
        public string Description_4 { get; set; }
        public string RoundOffMethod { get; set; }
        public string GLStkCoverage { get; set; }
        public string GLStkChange { get; set; }
        public string ItemToBeReceivedLedger { get; set; }
        public string GLAccountDiscount { get; set; }
        public Nullable<short> Division { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
        public byte[] timestamp { get; set; }
    }
}
