//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemProcess
    {
        public System.Guid ID { get; set; }
        public int Type { get; set; }
        public int RequestBy { get; set; }
        public System.DateTime RequestDate { get; set; }
        public int Status { get; set; }
        public string Company { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.DateTime DateEnd { get; set; }
        public Nullable<System.Guid> DocumentID { get; set; }
        public string Remark { get; set; }
        public int Mode { get; set; }
        public string ScenarioCode { get; set; }
        public Nullable<short> Division { get; set; }
    }
}
