//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemAttachments
    {
        public string ItemCode { get; set; }
        public System.Guid ReleaseID { get; set; }
        public byte[] Attachment { get; set; }
        public string AttachmentFilename { get; set; }
        public Nullable<System.DateTime> AttachmentDateTime { get; set; }
        public byte[] CompressedAttachment { get; set; }
        public string FileVersion { get; set; }
        public Nullable<System.DateTime> CheckedOut { get; set; }
        public Nullable<int> CheckedOutBy { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public string LastModifier { get; set; }
        public Nullable<int> Owner { get; set; }
        public Nullable<short> Division { get; set; }
    }
}
