//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemCountryTranslations
    {
        public System.Guid ID { get; set; }
        public System.Guid ItemCountryID { get; set; }
        public string LanguageCode { get; set; }
        public string Description { get; set; }
        public string Note { get; set; }
        public Nullable<short> Division { get; set; }
        public int Modifier { get; set; }
        public System.DateTime Modified { get; set; }
        public byte[] timestamp { get; set; }
    }
}
