//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemNumbers
    {
        public System.Guid ID { get; set; }
        public string ItemCode { get; set; }
        public string CountryCode { get; set; }
        public string Number { get; set; }
        public Nullable<System.Guid> ParentID { get; set; }
        public System.DateTime DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<System.DateTime> DateFinal { get; set; }
        public bool Active { get; set; }
        public string Description { get; set; }
        public string OwnerCompany { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<System.Guid> VariantID { get; set; }
        public string PurchaseCurrency { get; set; }
        public double PurchasePriceLocal { get; set; }
        public double PurchasePrice { get; set; }
        public double PurchaseBasePriceLocal { get; set; }
        public double PurchaseBasePrice { get; set; }
        public int Type { get; set; }
        public Nullable<System.Guid> Associate { get; set; }
        public string ProductRelease { get; set; }
        public string PreviousNumber { get; set; }
        public Nullable<System.Guid> Supplier { get; set; }
        public Nullable<System.Guid> DocumentID { get; set; }
        public int StatusValid { get; set; }
        public int StatusPrice { get; set; }
        public int StatusBudget { get; set; }
        public Nullable<System.DateTime> ShadowDateEnd { get; set; }
        public string ShadowCurrency { get; set; }
        public Nullable<double> ShadowPriceLocal { get; set; }
        public Nullable<double> ShadowPrice { get; set; }
        public int ShadowValid { get; set; }
        public Nullable<int> NumberInBatch { get; set; }
        public string VariantDescription { get; set; }
        public Nullable<int> VariantQuantity { get; set; }
        public string UserField_01 { get; set; }
        public string UserField_02 { get; set; }
        public string UserField_03 { get; set; }
        public string UserField_04 { get; set; }
        public string UserField_05 { get; set; }
        public string UserField_06 { get; set; }
        public string UserField_07 { get; set; }
        public string UserField_08 { get; set; }
        public string UserField_09 { get; set; }
        public string UserField_10 { get; set; }
        public Nullable<System.DateTime> UserDate_01 { get; set; }
        public Nullable<System.DateTime> UserDate_02 { get; set; }
        public Nullable<System.DateTime> UserDate_03 { get; set; }
        public Nullable<System.DateTime> UserDate_04 { get; set; }
        public Nullable<System.DateTime> UserDate_05 { get; set; }
        public Nullable<double> UserNumber_01 { get; set; }
        public Nullable<double> UserNumber_02 { get; set; }
        public Nullable<double> UserNumber_03 { get; set; }
        public Nullable<double> UserNumber_04 { get; set; }
        public Nullable<double> UserNumber_05 { get; set; }
        public Nullable<bool> UserYesNo_01 { get; set; }
        public Nullable<bool> UserYesNo_02 { get; set; }
        public Nullable<bool> UserYesNo_03 { get; set; }
        public Nullable<bool> UserYesNo_04 { get; set; }
        public Nullable<bool> UserYesNo_05 { get; set; }
        public string AssetGroup { get; set; }
        public string Classification { get; set; }
        public string SupplierNumber { get; set; }
        public int CurrQtyUnits { get; set; }
        public string Description2 { get; set; }
        public string Description3 { get; set; }
        public string Description4 { get; set; }
        public string Description5 { get; set; }
        public string FiscalGroup { get; set; }
        public Nullable<int> UserInteger_01 { get; set; }
        public Nullable<int> UserInteger_02 { get; set; }
        public Nullable<int> UserInteger_03 { get; set; }
        public Nullable<int> UserInteger_04 { get; set; }
        public Nullable<int> UserInteger_05 { get; set; }
        public int HID { get; set; }
        public string CostUnit { get; set; }
        public string CostCenter { get; set; }
        public Nullable<System.DateTime> LastMaintenanceDate { get; set; }
        public double MiscellaneousAmount { get; set; }
        public double MiscellaneousAmountFC { get; set; }
        public Nullable<System.Guid> NotesGuid { get; set; }
        public byte PassengerCar { get; set; }
        public byte[] Picture { get; set; }
        public string PictureFilename { get; set; }
        public string PriceList { get; set; }
        public string PrimaryMethod { get; set; }
        public string Projectnr { get; set; }
        public string PropertyType { get; set; }
        public string ReceiptNumber { get; set; }
        public int Resource { get; set; }
        public double ResidualValue { get; set; }
        public string SecondaryMethod { get; set; }
        public string Status { get; set; }
        public byte TangibleAsset { get; set; }
        public Nullable<System.Guid> TransactionGuid { get; set; }
        public string UsageStartPeriod { get; set; }
        public string UsageStartYear { get; set; }
        public double CostLastMaintenance { get; set; }
        public double CostLastMaintenanceFC { get; set; }
        public Nullable<System.Guid> AddressGUID { get; set; }
        public string LotNumber { get; set; }
        public string DepreciationBaseType { get; set; }
        public Nullable<short> DepreciationBaseDay { get; set; }
        public string SpecialCalcBasis { get; set; }
        public Nullable<System.DateTime> SpecialStartDate { get; set; }
        public string SpecialNumYears { get; set; }
        public string SpecialNumPeriods { get; set; }
        public string Status2 { get; set; }
        public Nullable<bool> UseSpecial { get; set; }
        public Nullable<short> Division { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public byte[] timestamp { get; set; }
        public string CountryOfAssembly { get; set; }
    }
}
