//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class kstdr
    {
        public int ID { get; set; }
        public string kstdrcode { get; set; }
        public string oms25_0 { get; set; }
        public string oms25_1 { get; set; }
        public string oms25_2 { get; set; }
        public string oms25_3 { get; set; }
        public string oms25_4 { get; set; }
        public string bedrnr { get; set; }
        public string UserField_01 { get; set; }
        public string UserField_02 { get; set; }
        public string UserField_03 { get; set; }
        public string UserField_04 { get; set; }
        public string UserField_05 { get; set; }
        public Nullable<double> UserNumber_01 { get; set; }
        public Nullable<double> UserNumber_02 { get; set; }
        public Nullable<double> UserNumber_03 { get; set; }
        public Nullable<double> UserNumber_04 { get; set; }
        public Nullable<double> UserNumber_05 { get; set; }
        public Nullable<short> Division { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
        public byte[] timestamp { get; set; }
    }
}
