//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class landClasses
    {
        public System.Guid ID { get; set; }
        public int ClassID { get; set; }
        public string landClassCode { get; set; }
        public string Description { get; set; }
        public Nullable<short> Division { get; set; }
    }
}
