//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class layouts
    {
        public int ID { get; set; }
        public int laytype { get; set; }
        public string name { get; set; }
        public string descr39 { get; set; }
        public int descr39_termid { get; set; }
        public byte std_layout { get; set; }
        public string std_country { get; set; }
        public byte[] layout { get; set; }
        public byte TNTPostLayout { get; set; }
        public Nullable<short> Division { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
        public string CoveringLetter { get; set; }
    }
}
