//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class nlhrpayroll
    {
        public int ID { get; set; }
        public string type { get; set; }
        public short contract { get; set; }
        public System.DateTime startdate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public string description { get; set; }
        public string job_title { get; set; }
        public Nullable<System.Guid> DocAttachmentID { get; set; }
        public Nullable<short> PayrollYear { get; set; }
        public int res_id { get; set; }
        public short period { get; set; }
        public byte tax_payment { get; set; }
        public string tax_table_color { get; set; }
        public string tax_extra_type { get; set; }
        public double tax_extra_amount { get; set; }
        public string tax_rebate_type { get; set; }
        public Nullable<System.DateTime> tax_rebate_ldate { get; set; }
        public byte tax_rebate_elderly { get; set; }
        public byte tax_rebate_young_disab { get; set; }
        public double tax_special_yearlywage { get; set; }
        public double tax_special_percentage { get; set; }
        public byte tax_voordeelregel { get; set; }
        public string tax_lagelonen_type { get; set; }
        public string tax_vermindering_type { get; set; }
        public double tax_vermindering_uren { get; set; }
        public double tax_vermindering_vastbedrag { get; set; }
        public Nullable<short> tax_income_code { get; set; }
        public string tax_reduction_type { get; set; }
        public string tax_exception_type { get; set; }
        public double tax_beschikking_amount { get; set; }
        public double tax_percentage_rule { get; set; }
        public string tax_franchise { get; set; }
        public string soc_ww_type { get; set; }
        public string soc_zw_type { get; set; }
        public string soc_wao_type { get; set; }
        public string soc_zfw_type { get; set; }
        public byte msv_print { get; set; }
        public string msv_declaration_type { get; set; }
        public string msv_resign_code { get; set; }
        public Nullable<System.DateTime> msv_change_ldate { get; set; }
        public Nullable<short> msv_cao_code { get; set; }
        public byte msv_labour_agreement { get; set; }
        public string msv_labour_code { get; set; }
        public string msv_labour_exception { get; set; }
        public byte msv_labour_regular { get; set; }
        public double msv_hours_week { get; set; }
        public Nullable<short> msv_wao_percentage { get; set; }
        public string msv_reduction_wa_code { get; set; }
        public string msv_premiumgrp_code { get; set; }
        public string msv_own_risk_code { get; set; }
        public double msv_loonsom { get; set; }
        public byte msv_part_vnps { get; set; }
        public byte msv_part_obf { get; set; }
        public byte msv_part_stein { get; set; }
        public byte msv_part_bps { get; set; }
        public Nullable<int> ydec_payment_amt { get; set; }
        public Nullable<short> ydec_payment_days { get; set; }
        public Nullable<int> ydec_payment_wao { get; set; }
        public Nullable<int> ydec_b_amount { get; set; }
        public Nullable<short> ydec_year_hours { get; set; }
        public Nullable<short> ydec_special_sv_code { get; set; }
        public Nullable<short> ydec_bpf_code { get; set; }
        public Nullable<short> ydec_vut_code { get; set; }
        public string ydec_vrijst_code { get; set; }
        public byte ydec_government { get; set; }
        public byte ydec_comp_car { get; set; }
        public Nullable<short> ydec_special_code1 { get; set; }
        public double ydec_special_amount1 { get; set; }
        public Nullable<short> ydec_special_code2 { get; set; }
        public double ydec_special_amount2 { get; set; }
        public Nullable<short> ydec_special_code3 { get; set; }
        public double ydec_special_amount3 { get; set; }
        public string sliptext1 { get; set; }
        public string sliptext2 { get; set; }
        public string sliptext3 { get; set; }
        public string payment_period { get; set; }
        public string country { get; set; }
        public double annual_wage { get; set; }
        public double afw_bter_pf { get; set; }
        public double soc_bter_days { get; set; }
        public string soc_type_line { get; set; }
        public byte plo_ris_fonds { get; set; }
        public string soc_leerling { get; set; }
        public byte soc_UTA { get; set; }
        public double days_period { get; set; }
        public string sector { get; set; }
        public string subsector { get; set; }
        public Nullable<short> abu_weeks_not_worked { get; set; }
        public Nullable<System.DateTime> abu_startdate { get; set; }
        public Nullable<System.DateTime> abu_enddate { get; set; }
        public Nullable<short> abp_dv_volgnr { get; set; }
        public Nullable<System.DateTime> abp_dv_startdate { get; set; }
        public Nullable<System.DateTime> abp_dv_enddate { get; set; }
        public string abp_dv_aard { get; set; }
        public string abp_dv_waarde { get; set; }
        public double abp_ptf_afw { get; set; }
        public string declaration_number { get; set; }
        public double reference_period { get; set; }
        public string component_group { get; set; }
        public Nullable<short> declaration_period { get; set; }
        public Nullable<short> declaration_sequence { get; set; }
        public string declaration_type { get; set; }
        public string declaration_made { get; set; }
        public Nullable<System.DateTime> declaration_date { get; set; }
        public string declaration_reference { get; set; }
        public Nullable<short> declaration_lastaction { get; set; }
        public string cd_ink_vermindering { get; set; }
        public string calc_svdays_method { get; set; }
        public double calc_days_week { get; set; }
        public double calc_hours_week { get; set; }
        public string calc_ptf_method { get; set; }
        public double calc_ptf { get; set; }
        public string slip_name_method { get; set; }
        public double reference_year { get; set; }
        public string tax_use_daily { get; set; }
        public Nullable<short> iv_nummer { get; set; }
        public Nullable<short> iv_indication { get; set; }
        public Nullable<System.DateTime> iv_startdate { get; set; }
        public Nullable<System.DateTime> iv_enddate { get; set; }
        public byte iv_dev_date { get; set; }
        public string cd_contract { get; set; }
        public string cd_fase_fz { get; set; }
        public double cd_cao { get; set; }
        public string cd_agh { get; set; }
        public string cd_zvw { get; set; }
        public double cvz_woonlandfactor { get; set; }
        public double korting_levensloop { get; set; }
        public string cd_redengeenbijtelling { get; set; }
        public string corr_arb_verh { get; set; }
        public double bter_uurloon { get; set; }
        public double bter_uurloon_excl { get; set; }
        public double tsf_dagen_opg { get; set; }
        public Nullable<short> TravelDaysPerYear { get; set; }
        public double TravelDistance { get; set; }
        public double ABPPercentageDeelnemerschap { get; set; }
        public Nullable<System.DateTime> EinddatumVergoedingsregeling { get; set; }
        public Nullable<System.DateTime> CodeVerminderingEinddatum { get; set; }
        public Nullable<short> Division { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
        public byte[] timestamp { get; set; }
    }
}
