//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Numbers
    {
        public string CompanyCode { get; set; }
        public short Type { get; set; }
        public int Number { get; set; }
        public bool Used { get; set; }
        public Nullable<short> Division { get; set; }
    }
}
