//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operations
    {
        public int ID { get; set; }
        public string Operation { get; set; }
        public string Description { get; set; }
        public string LayoutName { get; set; }
        public bool Blocked { get; set; }
        public bool OperationPrint { get; set; }
        public string AssetGroup { get; set; }
        public string AssetCode { get; set; }
        public string MachineHour { get; set; }
        public string CostCenter { get; set; }
        public Nullable<int> res_id { get; set; }
        public string LaborHourOperating { get; set; }
        public Nullable<double> OperatingTime { get; set; }
        public Nullable<double> LaborMachineRatio { get; set; }
        public string LaborHourSetup { get; set; }
        public Nullable<double> SetupTime { get; set; }
        public string OutsourcedItem { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
        public byte[] timestamp { get; set; }
        public Nullable<short> Division { get; set; }
        public int ScheduledResources { get; set; }
        public string Restrictions { get; set; }
        public bool IsParent { get; set; }
        public bool HasParent { get; set; }
        public Nullable<System.Guid> ParentID { get; set; }
        public bool FiniteSchedule { get; set; }
    }
}
