//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdlogSettings
    {
        public int ID { get; set; }
        public string TransactionType { get; set; }
        public string TableName { get; set; }
        public string FieldName { get; set; }
        public string OrdlogField { get; set; }
        public string BrowserTermID { get; set; }
        public Nullable<int> BrowserWidth { get; set; }
        public Nullable<int> BrowserScale { get; set; }
        public Nullable<int> BrowserOptions { get; set; }
        public bool BrowserInvisible { get; set; }
        public bool BrowserCheckmark { get; set; }
        public bool BrowserDefault { get; set; }
        public int BrowserSequence { get; set; }
        public bool Active { get; set; }
        public System.DateTime Created { get; set; }
        public int Creator { get; set; }
        public System.DateTime Modified { get; set; }
        public int Modifier { get; set; }
        public System.Guid sysguid { get; set; }
    }
}
