//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordlev
    {
        public int ID { get; set; }
        public string levwijze { get; set; }
        public string oms40_0 { get; set; }
        public string oms40_1 { get; set; }
        public string oms40_2 { get; set; }
        public string oms40_3 { get; set; }
        public string oms40_4 { get; set; }
        public string shipping { get; set; }
        public byte direct_shipping { get; set; }
        public Nullable<short> Division { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
        public byte[] timestamp { get; set; }
        public byte UseShippingManifest { get; set; }
        public bool DeliveryOnSaturday { get; set; }
        public bool DeliveryOnSunday { get; set; }
        public bool DeliveryOnPublicHolidays { get; set; }
    }
}
