//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class orhsrg
    {
        public int ID { get; set; }
        public string pakbon_nr { get; set; }
        public Nullable<System.DateTime> pakbon_dat { get; set; }
        public string regel { get; set; }
        public string artcode { get; set; }
        public string ordernr { get; set; }
        public string ar_soort { get; set; }
        public string oms45 { get; set; }
        public string magcode { get; set; }
        public Nullable<System.DateTime> afldat { get; set; }
        public string afl_week { get; set; }
        public double aant_gelev { get; set; }
        public string btw_code { get; set; }
        public string prijslijst { get; set; }
        public double korting { get; set; }
        public double prijs83 { get; set; }
        public double prijs_n { get; set; }
        public string kstdrcode { get; set; }
        public double vvp { get; set; }
        public double lengte { get; set; }
        public double breedte { get; set; }
        public double hoogte { get; set; }
        public string dimensie { get; set; }
        public string project { get; set; }
        public string kstsrt { get; set; }
        public string pr_kstpl { get; set; }
        public double pr_aant { get; set; }
        public double pr_bedr { get; set; }
        public string kstplcode { get; set; }
        public string kort_flags { get; set; }
        public string cat1 { get; set; }
        public string cat2 { get; set; }
        public string cat3 { get; set; }
        public string prod_order { get; set; }
        public double extra_pr { get; set; }
        public string explsrtart { get; set; }
        public string regel_hfda { get; set; }
        public string serie_num { get; set; }
        public double aantal_ser { get; set; }
        public string unit { get; set; }
        public double av_ont_in { get; set; }
        public double koers { get; set; }
        public double bdr_ev_ed_val { get; set; }
        public double bdr_d_ev_val { get; set; }
        public double bdr_vat_val { get; set; }
        public double bdr_inv_d_val { get; set; }
        public string instruction { get; set; }
        public string projectnr { get; set; }
        public int res_id { get; set; }
        public string unitcode { get; set; }
        public double unitfactor { get; set; }
        public Nullable<short> Division { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
        public byte[] timestamp { get; set; }
        public string CSRekregLabelOms00 { get; set; }
        public string CSRekregLabelOms01 { get; set; }
        public string CSRekregLabelOms02 { get; set; }
        public string CSRekregLabelOms03 { get; set; }
        public string CSRekregLabelOms04 { get; set; }
        public string CSRekregLabelOms05 { get; set; }
        public string CSRekregLabelOms06 { get; set; }
        public string CSRekregLabelOms07 { get; set; }
        public string CSRekregLabelOms08 { get; set; }
        public string CSRekregLabelOms09 { get; set; }
        public string CSRekregLabelOms10 { get; set; }
        public Nullable<double> CSRekregValue00 { get; set; }
        public Nullable<double> CSRekregValue01 { get; set; }
        public Nullable<double> CSRekregValue02 { get; set; }
        public Nullable<double> CSRekregValue03 { get; set; }
        public Nullable<double> CSRekregValue04 { get; set; }
        public Nullable<double> CSRekregValue05 { get; set; }
        public Nullable<double> CSRekregValue06 { get; set; }
        public Nullable<double> CSRekregValue07 { get; set; }
        public Nullable<double> CSRekregValue08 { get; set; }
        public Nullable<double> CSRekregValue09 { get; set; }
        public Nullable<double> CSRekregValue10 { get; set; }
        public Nullable<double> CSRekregRoundedValue00 { get; set; }
        public Nullable<double> CSRekregRoundedValue01 { get; set; }
        public Nullable<double> CSRekregRoundedValue02 { get; set; }
        public Nullable<double> CSRekregRoundedValue03 { get; set; }
        public Nullable<double> CSRekregRoundedValue04 { get; set; }
        public Nullable<double> CSRekregRoundedValue05 { get; set; }
        public Nullable<double> CSRekregRoundedValue06 { get; set; }
        public Nullable<double> CSRekregRoundedValue07 { get; set; }
        public Nullable<double> CSRekregRoundedValue08 { get; set; }
        public Nullable<double> CSRekregRoundedValue09 { get; set; }
        public Nullable<double> CSRekregRoundedValue10 { get; set; }
        public string CSRekregRemark { get; set; }
        public string CSRekregFreeField01 { get; set; }
        public string CSRekregFreeField02 { get; set; }
        public string CSRekregFreeField03 { get; set; }
        public Nullable<System.DateTime> CSRekregFreeFieldDate { get; set; }
        public byte CSRekregFreeFieldNoYes01 { get; set; }
        public byte CSRekregFreeFieldNoYes02 { get; set; }
        public Nullable<double> CSrekregFactor { get; set; }
        public string CSRekregFormulaName { get; set; }
        public Nullable<System.Guid> SMSConfiguration { get; set; }
        public byte CSPickITCWOriginIsSalesDB { get; set; }
        public string CSPickITCWStatusCWDB { get; set; }
        public string CSPickITCWStatusSalesDB { get; set; }
        public Nullable<System.Guid> CSPickITCWSysGUIDCWDB { get; set; }
        public Nullable<System.Guid> CSPickITCWSysGUIDSalesDB { get; set; }
        public string CSPickITCWWarehouseCWDB { get; set; }
        public string CSPickITHandTerminalID { get; set; }
        public byte CSPickITModifyQuantity { get; set; }
        public Nullable<int> CSPickITOrderPicker { get; set; }
        public string CSPickITState { get; set; }
        public Nullable<double> CSPickITQtyOrdered { get; set; }
        public Nullable<double> CSPickITQuantityPicked { get; set; }
        public byte CSPickITToBackOrder { get; set; }
        public Nullable<double> CSPickITQuantityCrossDock { get; set; }
        public Nullable<System.Guid> CSPickITTransactionGUID { get; set; }
        public Nullable<int> CSPickITTransferLineID { get; set; }
        public string CSPickITShipmentSSCC { get; set; }
    }
}
