//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PenaltyTemp83091D0BA1B1487283581377DF04F505
    {
        public int InforType { get; set; }
        public int ID { get; set; }
        public string Debtor { get; set; }
        public string naam { get; set; }
        public string EntryNumber { get; set; }
        public System.Guid InvoiceOrigin { get; set; }
        public Nullable<System.Guid> EntryGuid { get; set; }
        public string OurRef { get; set; }
        public Nullable<System.DateTime> Invoicedate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string Type { get; set; }
        public int Status { get; set; }
        public string Description { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<double> Interest { get; set; }
        public double InvoiceAmount { get; set; }
        public double InvoiceAmountFC { get; set; }
        public Nullable<double> AmountDueORLateDC { get; set; }
        public string TCCode { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<double> PenaltyAmountDC { get; set; }
        public string ClassificationDesc { get; set; }
        public int AccountEmployee { get; set; }
        public string AccountEmployeeFullName { get; set; }
    }
}
