//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PenaltyCodes
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string Type { get; set; }
        public double ExtraAmount { get; set; }
        public double FixedRate { get; set; }
        public short Day01 { get; set; }
        public double Rate01 { get; set; }
        public short Day02 { get; set; }
        public double Rate02 { get; set; }
        public short Day03 { get; set; }
        public double Rate03 { get; set; }
        public short Day04 { get; set; }
        public double Rate04 { get; set; }
        public short Day05 { get; set; }
        public double Rate05 { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
        public byte[] timestamp { get; set; }
    }
}
