//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PortalUsage
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> Portal { get; set; }
        public string NewsLayout { get; set; }
        public string DivisionGroup { get; set; }
        public string Division { get; set; }
        public Nullable<short> DivisionX { get; set; }
        public string CostcenterGroup { get; set; }
        public string Costcenter { get; set; }
        public string Classification { get; set; }
        public string Sector { get; set; }
        public Nullable<int> Role { get; set; }
        public string JobGroup { get; set; }
        public string JobActivity { get; set; }
        public string Language { get; set; }
        public System.DateTime syscreated { get; set; }
        public Nullable<int> syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public Nullable<int> sysmodifier { get; set; }
    }
}
