//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class pospreset
    {
        public int ID { get; set; }
        public string Type { get; set; }
        public string code { get; set; }
        public string line { get; set; }
        public string oms30_0 { get; set; }
        public string oms30_1 { get; set; }
        public string oms30_2 { get; set; }
        public string oms30_3 { get; set; }
        public string oms30_4 { get; set; }
        public byte shiftkeys { get; set; }
        public short vbkey { get; set; }
        public short shift { get; set; }
        public short posfunction { get; set; }
        public string fixedval { get; set; }
        public Nullable<System.Guid> account { get; set; }
        public string valcode { get; set; }
        public double RoundFact { get; set; }
        public byte OpenDrawer { get; set; }
        public byte PrintRcp { get; set; }
        public short InvoiceCopies { get; set; }
        public string Layout { get; set; }
        public int Change { get; set; }
        public string LimitType { get; set; }
        public double Limit { get; set; }
        public string BankAccount { get; set; }
        public string PaymentType { get; set; }
        public string LedgerAccount { get; set; }
        public int RoleID { get; set; }
        public string CashCount { get; set; }
        public Nullable<System.Guid> GroupBy { get; set; }
        public string Coin { get; set; }
        public Nullable<short> Division { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
    }
}
