//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class QIinvoiceLines
    {
        public string orig { get; set; }
        public int ID { get; set; }
        public string faknr { get; set; }
        public Nullable<System.DateTime> fakdat { get; set; }
        public string dagbknr { get; set; }
        public string fakt_code { get; set; }
        public string volgnr5 { get; set; }
        public string regel { get; set; }
        public string artcode { get; set; }
        public Nullable<double> bdr_val { get; set; }
        public string ar_soort { get; set; }
        public string oms45 { get; set; }
        public string reknr { get; set; }
        public string magcode { get; set; }
        public string oms160 { get; set; }
        public string afl_week { get; set; }
        public Nullable<System.DateTime> afldat { get; set; }
        public double esr_aantal { get; set; }
        public byte ordreg { get; set; }
        public string btw_code { get; set; }
        public string prijslijst { get; set; }
        public double korting { get; set; }
        public double prijs83 { get; set; }
        public double prijs_n { get; set; }
        public Nullable<double> gip { get; set; }
        public double vvp { get; set; }
        public string kstdrcode { get; set; }
        public Nullable<double> lengte { get; set; }
        public Nullable<double> breedte { get; set; }
        public Nullable<double> hoogte { get; set; }
        public string dimensie { get; set; }
        public string project { get; set; }
        public string pr_kstpl { get; set; }
        public string kstsrt { get; set; }
        public Nullable<byte> projvrw_c { get; set; }
        public string maglok { get; set; }
        public double pr_bedr { get; set; }
        public string kort_flags { get; set; }
        public string prshisnr { get; set; }
        public string kstplcode { get; set; }
        public string explsrtart { get; set; }
        public string prod_order { get; set; }
        public Nullable<double> extra_pr { get; set; }
        public string statistnr { get; set; }
        public string taric { get; set; }
        public string landoorspr { get; set; }
        public string landherk { get; set; }
        public string landbest { get; set; }
        public string landabc { get; set; }
        public string land_iso { get; set; }
        public string transact_a { get; set; }
        public string transact_b { get; set; }
        public string vervoer { get; set; }
        public string plts_ll { get; set; }
        public Nullable<byte> request { get; set; }
        public string stelsel { get; set; }
        public string int_regio { get; set; }
        public string intra_lvcd { get; set; }
        public string trsshpm_cd { get; set; }
        public Nullable<byte> container { get; set; }
        public Nullable<double> stateenh_i { get; set; }
        public Nullable<double> gewicht_bi { get; set; }
        public string boecode { get; set; }
        public string affiliates { get; set; }
        public string csacode { get; set; }
        public string ordernr { get; set; }
        public string pakbon_nr { get; set; }
        public Nullable<System.DateTime> pakbon_dat { get; set; }
        public string status { get; set; }
        public string regel_hfda { get; set; }
        public Nullable<byte> correction { get; set; }
        public Nullable<double> bdr_vat_val { get; set; }
        public Nullable<double> bdr_ev_ed_val { get; set; }
        public Nullable<double> bdr_d_ev_val { get; set; }
        public Nullable<double> bdr_inv_d_val { get; set; }
        public string serie_num { get; set; }
        public Nullable<System.DateTime> eind_dat_c { get; set; }
        public string serv_order { get; set; }
        public Nullable<double> perc_con { get; set; }
        public Nullable<double> perc_gar { get; set; }
        public string volgnr_mut { get; set; }
        public string contractnr { get; set; }
    }
}
