//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReminderRunData98DC0944ED034F4AA27D5F03832933DC
    {
        public int ID { get; set; }
        public string GrpType { get; set; }
        public string InfoLevel { get; set; }
        public Nullable<int> MatchID { get; set; }
        public string CompanyDescription { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAddress1 { get; set; }
        public string CompanyAddress2 { get; set; }
        public string CompanyAddress3 { get; set; }
        public string CompanyPostcode { get; set; }
        public string CompanyCity { get; set; }
        public string CompanyPhone { get; set; }
        public string CompanyBank { get; set; }
        public string CompanyBankLocation { get; set; }
        public string CompanyBankAccount { get; set; }
        public string CompanyBankPostbankAccount { get; set; }
        public string CompanyPostbankAccount { get; set; }
        public Nullable<int> CompanyRepresentativeCode { get; set; }
        public string CompanyRepresentativeName { get; set; }
        public Nullable<int> GbkmutID { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public Nullable<System.DateTime> ReminderDate { get; set; }
        public string LayoutCode { get; set; }
        public string DebtorNumber { get; set; }
        public string DebtorVatNumber { get; set; }
        public string DebtorPhone { get; set; }
        public string DebtorSearchCode { get; set; }
        public string DebtorName { get; set; }
        public string DebtorAddress1 { get; set; }
        public string DebtorAddress2 { get; set; }
        public string DebtorAddress3 { get; set; }
        public string DebtorPostcode { get; set; }
        public string DebtorCity { get; set; }
        public string DebtorBankAccountNumber { get; set; }
        public string DebtorPostbankAccountNumber { get; set; }
        public string Classification { get; set; }
        public string DebtorCountryCode { get; set; }
        public string DebtorCountryDescription { get; set; }
        public string DebtorContactName { get; set; }
        public string DebtorContactInitials { get; set; }
        public string DebtorContactPosition { get; set; }
        public string DebtorContactPhone { get; set; }
        public string DebtorContactFax { get; set; }
        public string DebtorContactTitle { get; set; }
        public string DebtorContactHeading { get; set; }
        public Nullable<System.DateTime> DebtorLastReminderDate { get; set; }
        public string DeliveryName { get; set; }
        public string DeliveryAddress1 { get; set; }
        public string DeliveryAddress2 { get; set; }
        public string DeliveryAddress3 { get; set; }
        public string DeliveryPostcode { get; set; }
        public string DeliveryCity { get; set; }
        public string PaymentConditionCode { get; set; }
        public string PaymentConditionDescription { get; set; }
        public string PaymentConditionType { get; set; }
        public Nullable<int> PaymentConditionNumberOfDays1 { get; set; }
        public Nullable<double> PaymentConditionPercentage { get; set; }
        public Nullable<int> PaymentConditionTerm { get; set; }
        public string StructuredAnnouncement { get; set; }
        public string ICONumber { get; set; }
        public string EntryNumber { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<double> InterestRate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string Description { get; set; }
        public string CurrencyCode { get; set; }
        public string CurrencyAbbreviation { get; set; }
        public Nullable<decimal> OriginalAmount { get; set; }
        public Nullable<decimal> DueAmount { get; set; }
        public Nullable<decimal> OutstandingAmount { get; set; }
        public Nullable<System.DateTime> LastReminderDate { get; set; }
        public Nullable<decimal> AmountDue { get; set; }
        public Nullable<decimal> AmountNotDue { get; set; }
        public Nullable<decimal> CSSDAmount { get; set; }
        public Nullable<int> NumberOfDaysOutstanding { get; set; }
        public Nullable<decimal> PenaltyAmount { get; set; }
        public Nullable<int> NumberOfDaysPastDueDate { get; set; }
        public Nullable<decimal> OutstandingAmountDC { get; set; }
        public string DebtorContactEmailAddress { get; set; }
        public Nullable<System.DateTime> DocumentDate { get; set; }
        public string DocumentNumber { get; set; }
        public string InvoiceNumber { get; set; }
        public string PaymentReference { get; set; }
        public string MaskedPaymentReference { get; set; }
        public string InvoiceNumberSub { get; set; }
        public Nullable<decimal> Exvalbdr { get; set; }
        public string Exvalcode { get; set; }
        public string LanguageCode { get; set; }
        public string Region { get; set; }
        public string DeliveryState { get; set; }
        public string cmp_Region { get; set; }
        public string DebtorCntMName { get; set; }
        public string DebtorCntFName { get; set; }
        public string DebtorCntLName { get; set; }
        public Nullable<int> CountRegels { get; set; }
        public string DebtorCode { get; set; }
        public string TransType { get; set; }
        public string ParentSortCode { get; set; }
    }
}
