//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResellerNews
    {
        public System.Guid ID { get; set; }
        public int Administration { get; set; }
        public string BDLayoutID { get; set; }
        public int Type { get; set; }
        public Nullable<short> Division { get; set; }
    }
}
