//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SDKASPButtons
    {
        public int ID { get; set; }
        public Nullable<System.Guid> ASPPageID { get; set; }
        public Nullable<System.Guid> GroupID { get; set; }
        public string Name { get; set; }
        public string Label { get; set; }
        public int LabelTermId { get; set; }
        public string AccessKey { get; set; }
        public string Class { get; set; }
        public byte Disabled { get; set; }
        public int TabIndex { get; set; }
        public string Title { get; set; }
        public int TitleTermId { get; set; }
        public string ButtonType { get; set; }
        public string URLParamNames { get; set; }
        public string URLParamValues { get; set; }
        public string Link { get; set; }
        public string Condition { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
        public byte[] timestamp { get; set; }
    }
}
