//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SDKGroups
    {
        public int ID { get; set; }
        public Nullable<System.Guid> GroupID { get; set; }
        public string GroupName { get; set; }
        public string Description { get; set; }
        public int TermId { get; set; }
        public int GroupNumber { get; set; }
        public string License { get; set; }
        public string DeveloperLicense { get; set; }
        public string DeveloperName { get; set; }
        public Nullable<int> DataModelDate { get; set; }
        public string SolutionType { get; set; }
        public string Component { get; set; }
        public int SequenceNumber { get; set; }
        public Nullable<bool> Activate { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
        public byte[] timestamp { get; set; }
    }
}
