//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SDKTabPages
    {
        public int ID { get; set; }
        public Nullable<System.Guid> TabPageID { get; set; }
        public Nullable<System.Guid> GroupID { get; set; }
        public string Description { get; set; }
        public int DescriptionTermID { get; set; }
        public string Prefix { get; set; }
        public int Color { get; set; }
        public string DocDefault { get; set; }
        public string DocSearch { get; set; }
        public string DocNews { get; set; }
        public string DocReports { get; set; }
        public string DocMaintenance { get; set; }
        public string DocOrganization { get; set; }
        public string DocEntry { get; set; }
        public string TabIcon { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
        public byte[] timestamp { get; set; }
    }
}
