//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Settings
    {
        public string SettingGroup { get; set; }
        public string SettingName { get; set; }
        public int ValueType { get; set; }
        public Nullable<byte> BitValue { get; set; }
        public Nullable<int> LongValue { get; set; }
        public Nullable<double> DblValue { get; set; }
        public Nullable<System.DateTime> DateValue { get; set; }
        public string StringValue { get; set; }
        public byte[] BinaryValue { get; set; }
        public Nullable<byte> Editable { get; set; }
        public string Description { get; set; }
        public Nullable<int> TermID { get; set; }
        public string Category { get; set; }
        public string Profile { get; set; }
        public Nullable<short> Division { get; set; }
    }
}
