//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class stfoms
    {
        public int ID { get; set; }
        public string prijslijst { get; set; }
        public string oms30_0 { get; set; }
        public string oms30_1 { get; set; }
        public string oms30_2 { get; set; }
        public string oms30_3 { get; set; }
        public string oms30_4 { get; set; }
        public string valcode { get; set; }
        public string country { get; set; }
        public string type { get; set; }
        public string AccountType { get; set; }
        public string AccountStatus { get; set; }
        public string AccountClassificationId { get; set; }
        public byte main_pricelist { get; set; }
        public Nullable<short> Division { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
        public byte[] timestamp { get; set; }
    }
}
