//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SynchronizationLog
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public Nullable<System.Guid> TransactionID { get; set; }
        public Nullable<System.Guid> MessageID { get; set; }
        public string Destination { get; set; }
        public string Message { get; set; }
        public string EntityName { get; set; }
        public string Action { get; set; }
        public string LogicalKey { get; set; }
    }
}
