//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class taxdef
    {
        public int ID { get; set; }
        public string typedefault { get; set; }
        public string reknr { get; set; }
        public string debnr { get; set; }
        public string crdnr { get; set; }
        public string artcode { get; set; }
        public int seq_nr { get; set; }
        public string taxtype { get; set; }
        public string taxcode { get; set; }
        public string invoicetype { get; set; }
        public double percentage { get; set; }
        public double percnonded { get; set; }
        public double amount { get; set; }
        public Nullable<short> Division { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
        public byte[] timestamp { get; set; }
    }
}
