//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxonomyTypes
    {
        public System.Guid ID { get; set; }
        public System.Guid TaxonomyNamespace { get; set; }
        public string Type { get; set; }
        public string PrefixedType { get; set; }
        public string BasicType { get; set; }
        public Nullable<short> Length { get; set; }
        public Nullable<short> MinLength { get; set; }
        public Nullable<short> MaxLength { get; set; }
        public string Pattern { get; set; }
        public string MinInclusive { get; set; }
        public string MaxInclusive { get; set; }
        public Nullable<short> TotalDigits { get; set; }
        public Nullable<short> FractionDigits { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
    }
}
