//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxonomyRelations
    {
        public System.Guid ID { get; set; }
        public System.Guid LinkBase { get; set; }
        public string ArcRole { get; set; }
        public System.Guid Parent { get; set; }
        public System.Guid Child { get; set; }
        public Nullable<double> SortOrder { get; set; }
        public Nullable<int> Weight { get; set; }
        public string UseOptional { get; set; }
        public Nullable<int> MinOccurs { get; set; }
        public Nullable<int> MaxOccurs { get; set; }
        public string PreferredLabel { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
    }
}
