//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxonomyPresentationRelations
    {
        public System.Guid ID { get; set; }
        public System.Guid Linkbase { get; set; }
        public System.Guid Parent { get; set; }
        public System.Guid Child { get; set; }
        public int Level { get; set; }
    }
}
