//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionsPending
    {
        public string CompanyCode { get; set; }
        public int TransactionType { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public Nullable<int> FinYear { get; set; }
        public Nullable<int> FinPeriod { get; set; }
        public string Description { get; set; }
        public string CompanyAccountCode { get; set; }
        public string CompanyContraAccountCode { get; set; }
        public string EntryNumber { get; set; }
        public string Invoice { get; set; }
        public string JournalNumber { get; set; }
        public Nullable<int> JournalType { get; set; }
        public string DebtorCode { get; set; }
        public string CreditorCode { get; set; }
        public string CompanyCostcenterCode { get; set; }
        public string CompanyCostunitCode { get; set; }
        public string CurrencyCode { get; set; }
        public double Rate { get; set; }
        public double AmountDebit { get; set; }
        public double AmountCredit { get; set; }
        public double VATBaseAmount { get; set; }
        public double VATAmount { get; set; }
        public string CurrencyAliasAC { get; set; }
        public double AmountDebitAC { get; set; }
        public double AmountCreditAC { get; set; }
        public double VATBaseAmountAC { get; set; }
        public double VATAmountAC { get; set; }
        public string CurrencyAliasFC { get; set; }
        public double RateFC { get; set; }
        public double AmountDebitFC { get; set; }
        public double AmountCreditFC { get; set; }
        public double VATBaseAmountFC { get; set; }
        public string CompanyCodeFrom { get; set; }
        public string CompanyCodeTo { get; set; }
        public string VATCode { get; set; }
        public double VATPercentage { get; set; }
        public string PaymentTermCode { get; set; }
        public bool IsStorno { get; set; }
        public double Quantity { get; set; }
        public int ProcessNumber { get; set; }
        public int ProcessOrder { get; set; }
        public int ProcessLine { get; set; }
        public string ProcessLineCode { get; set; }
        public bool TransactionClosed { get; set; }
        public bool TransactionValid { get; set; }
        public System.DateTime TransactionImported { get; set; }
        public Nullable<int> res_id { get; set; }
        public Nullable<System.Guid> DocumentID { get; set; }
        public int ID { get; set; }
        public double bdr_hfl { get; set; }
        public string exvalcode { get; set; }
        public double wisselkrs { get; set; }
        public double koers3 { get; set; }
        public double bdr_val { get; set; }
        public int dbk_verwnr { get; set; }
        public string oorsprong { get; set; }
        public string vlgn_gbk2 { get; set; }
        public Nullable<System.DateTime> afldat { get; set; }
        public string docnumber { get; set; }
        public Nullable<System.DateTime> docdate { get; set; }
        public int entryid { get; set; }
        public double exvalbdr { get; set; }
        public string entryorigin { get; set; }
        public Nullable<System.DateTime> vervdatkrd { get; set; }
        public Nullable<System.DateTime> vervdtkrd2 { get; set; }
        public Nullable<System.DateTime> vervdatfak { get; set; }
        public string kredbep { get; set; }
        public double bdrkredbep { get; set; }
        public double bdrkredbp2 { get; set; }
        public string betaalref { get; set; }
        public short stat_nr { get; set; }
        public string btw_nummer { get; set; }
        public string rapnr { get; set; }
        public string raplist { get; set; }
        public string artcode { get; set; }
        public string faktuurnr { get; set; }
        public string bud_vers { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public int ReminderCount { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int ReminderLayout { get; set; }
        public Nullable<System.DateTime> LastReminderDate { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
        public byte BlockItem { get; set; }
        public byte[] timestamp { get; set; }
        public string bankacc { get; set; }
        public string PaymentMethod { get; set; }
        public Nullable<System.Guid> Account { get; set; }
        public string facode { get; set; }
        public string transtype { get; set; }
        public string transsubtype { get; set; }
        public string freefield1 { get; set; }
        public string freefield2 { get; set; }
        public string freefield3 { get; set; }
        public Nullable<double> freefield4 { get; set; }
        public Nullable<double> freefield5 { get; set; }
        public string serialnumber { get; set; }
        public string project { get; set; }
        public int Status { get; set; }
        public string Message { get; set; }
        public System.DateTime ImportDate { get; set; }
        public Nullable<System.Guid> orderdebtor { get; set; }
        public string warehouse { get; set; }
        public string PayrollSubtype { get; set; }
        public Nullable<int> ReconcileNumber { get; set; }
        public string warehouse_location { get; set; }
        public Nullable<System.Guid> EntryGuid { get; set; }
        public Nullable<System.Guid> TransactionGuid { get; set; }
        public Nullable<System.Guid> TransactionGuid2 { get; set; }
        public Nullable<System.Guid> DocAttachmentID { get; set; }
        public Nullable<System.Guid> BankTransactionGUID { get; set; }
        public byte Checked { get; set; }
        public byte Reviewed { get; set; }
        public string CashRegisterAccount { get; set; }
        public string StockTrackingNumber { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<System.DateTime> ReportingDate { get; set; }
        public Nullable<double> Original_Quantity { get; set; }
        public string comp_code { get; set; }
        public string Selcode { get; set; }
        public string Unitcode { get; set; }
        public string Pricelist { get; set; }
        public Nullable<double> Discount { get; set; }
        public string Shipment { get; set; }
        public string IntTransportMethod { get; set; }
        public string IntPort { get; set; }
        public string IntSystem { get; set; }
        public string IntTransA { get; set; }
        public string IntStatNr { get; set; }
        public string IntStandardCode { get; set; }
        public string IntTransShipment { get; set; }
        public string IntTransB { get; set; }
        public string IntArea { get; set; }
        public string IntLandISO { get; set; }
        public string IntLandDestOrig { get; set; }
        public string IntDeliveryMethod { get; set; }
        public Nullable<double> IntStatUnit { get; set; }
        public Nullable<double> IntWeight { get; set; }
        public Nullable<byte> IntComplete { get; set; }
        public string IntLandAssembly { get; set; }
        public Nullable<byte> PayrollCosts { get; set; }
        public string TaxCode2 { get; set; }
        public string TaxCode3 { get; set; }
        public string TaxCode4 { get; set; }
        public string TaxCode5 { get; set; }
        public double TaxBasis2 { get; set; }
        public double TaxBasis3 { get; set; }
        public double TaxBasis4 { get; set; }
        public double TaxBasis5 { get; set; }
        public double TaxAmount2 { get; set; }
        public double TaxAmount3 { get; set; }
        public double TaxAmount4 { get; set; }
        public double TaxAmount5 { get; set; }
        public Nullable<short> Division { get; set; }
    }
}
