//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionTypes
    {
        public int TransactionType { get; set; }
        public string Description { get; set; }
        public int DescriptionTermID { get; set; }
        public string DescriptionSuffix { get; set; }
        public Nullable<int> DescriptionSuffixTermID { get; set; }
        public bool IsBudgetType { get; set; }
        public byte[] timestamp { get; set; }
        public Nullable<short> Division { get; set; }
    }
}
