//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class usrbar
    {
        public int res_id { get; set; }
        public int mnu_id { get; set; }
        public string type { get; set; }
        public Nullable<short> Division { get; set; }
    }
}
