//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class valuta
    {
        public int ID { get; set; }
        public string valcode { get; set; }
        public string oms30_0 { get; set; }
        public string oms30_1 { get; set; }
        public string oms30_2 { get; set; }
        public string oms30_3 { get; set; }
        public string oms30_4 { get; set; }
        public string afk_val { get; set; }
        public double omrekfact { get; set; }
        public string rekkrsvink { get; set; }
        public string rekkrswink { get; set; }
        public string rekkrsvvrk { get; set; }
        public string rekkrswvrk { get; set; }
        public string rekherw { get; set; }
        public string rekherww { get; set; }
        public string btwlaagvrk { get; set; }
        public string btwhoogvrk { get; set; }
        public string btwlaagink { get; set; }
        public string btwhoogink { get; set; }
        public byte dagkoers { get; set; }
        public byte doorbkvali { get; set; }
        public byte doorbkvalv { get; set; }
        public string omzetcode { get; set; }
        public byte invvalink { get; set; }
        public byte invvalvrk { get; set; }
        public short price_prec { get; set; }
        public short amount_prec { get; set; }
        public string cur_letter { get; set; }
        public byte xtra_rates { get; set; }
        public short rate_prec { get; set; }
        public byte emu_currency { get; set; }
        public Nullable<System.DateTime> emu_date { get; set; }
        public string swiftvalcd { get; set; }
        public string blwi_valcd { get; set; }
        public byte active { get; set; }
        public string freefield1 { get; set; }
        public string freefield2 { get; set; }
        public string freefield3 { get; set; }
        public string freefield4 { get; set; }
        public string freefield5 { get; set; }
        public string freefield6 { get; set; }
        public string freefield7 { get; set; }
        public double freefield8 { get; set; }
        public double freefield9 { get; set; }
        public double freefield10 { get; set; }
        public double freefield11 { get; set; }
        public double freefield12 { get; set; }
        public double freefield13 { get; set; }
        public Nullable<System.DateTime> freefield14 { get; set; }
        public Nullable<System.DateTime> freefield15 { get; set; }
        public Nullable<System.DateTime> freefield16 { get; set; }
        public byte freefield17 { get; set; }
        public byte freefield18 { get; set; }
        public byte freefield19 { get; set; }
        public byte freefield20 { get; set; }
        public byte Enabled { get; set; }
        public Nullable<short> Division { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
        public byte[] timestamp { get; set; }
    }
}
