//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorDetails
    {
        public int ID { get; set; }
        public short Division { get; set; }
        public string TaxForm { get; set; }
        public short Year { get; set; }
        public string VendorID { get; set; }
        public string Name { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string FedIDNumber { get; set; }
        public double UnmatchedPayment { get; set; }
        public double NumberFieldBox1 { get; set; }
        public double NumberFieldBox2 { get; set; }
        public double NumberFieldBox3 { get; set; }
        public double NumberFieldBox4 { get; set; }
        public double NumberFieldBox5 { get; set; }
        public double NumberFieldBox6 { get; set; }
        public double NumberFieldBox7 { get; set; }
        public double NumberFieldBox8 { get; set; }
        public bool YesNoFieldBox9 { get; set; }
        public double NumberFieldBox10 { get; set; }
        public double NumberFieldBox13 { get; set; }
        public double NumberFieldBox14 { get; set; }
        public double NumberFieldBox15A { get; set; }
        public double NumberFieldBox15B { get; set; }
        public double NumberFieldBox16 { get; set; }
        public double NumberFieldBox16II { get; set; }
        public string TextFieldBox17 { get; set; }
        public string TextFieldBox17II { get; set; }
        public double NumberFieldBox18 { get; set; }
        public double NumberFieldBox18II { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
        public byte[] TimeStamp { get; set; }
    }
}
