//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class verslg
    {
        public int ID { get; set; }
        public string verwerknr { get; set; }
        public Nullable<short> bkjrcode { get; set; }
        public string periode { get; set; }
        public string dagbknr { get; set; }
        public string oms40 { get; set; }
        public Nullable<System.DateTime> datum { get; set; }
        public double tot_debet { get; set; }
        public double tot_credit { get; set; }
        public string user_id { get; set; }
        public short aant_afgdr { get; set; }
        public Nullable<short> Division { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public System.Guid sysguid { get; set; }
        public byte[] timestamp { get; set; }
    }
}
