//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwInvest
    {
        public string ASSETGROUP { get; set; }
        public string PrimaryMethod { get; set; }
        public System.DateTime DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public string Description { get; set; }
        public string Number { get; set; }
        public Nullable<System.DateTime> UserDate_03 { get; set; }
        public Nullable<System.DateTime> purchdate { get; set; }
        public Nullable<System.DateTime> docdate { get; set; }
        public string status { get; set; }
        public string transsubtype { get; set; }
        public Nullable<double> InvD { get; set; }
        public Nullable<double> MAR { get; set; }
        public Nullable<double> Cession { get; set; }
        public Nullable<double> AmtDeb { get; set; }
        public Nullable<double> aCession { get; set; }
        public Nullable<double> aMAR { get; set; }
    }
}
