//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebStyle
    {
        public System.Guid ID { get; set; }
        public string SiteName { get; set; }
        public string SiteBGColour { get; set; }
        public string SiteLayout { get; set; }
        public bool SiteComboBox { get; set; }
        public bool SiteDocSearch { get; set; }
        public Nullable<System.Guid> Logo { get; set; }
        public Nullable<System.Guid> BGImage { get; set; }
        public Nullable<System.Guid> BGImageTop { get; set; }
        public Nullable<System.Guid> BGImageBottom { get; set; }
        public Nullable<System.Guid> BGImageTopFrame { get; set; }
        public string BGColourTopFrame { get; set; }
        public int WidthLeftFrame { get; set; }
        public Nullable<byte> IsByHandLeftFrame { get; set; }
        public string HTMLTextLeftFrame { get; set; }
        public string HTMLText { get; set; }
        public Nullable<System.DateTime> ActiveDate { get; set; }
        public byte IsActiveDate { get; set; }
        public Nullable<byte> IsHideBanner { get; set; }
        public Nullable<byte> IsMarqueeBanner { get; set; }
        public int MarqueeSpeedBanner { get; set; }
        public string TextColourBanner { get; set; }
        public string BGColourBanner { get; set; }
        public int FrontPageType { get; set; }
        public string FrontPage { get; set; }
        public int HeightTopFrame { get; set; }
        public Nullable<byte> IsByHandTopFrame { get; set; }
        public string HTMLTextTopFrame { get; set; }
        public string ASPLeftFrame { get; set; }
        public string ASPTopFrame { get; set; }
        public int SetupLeftFrame { get; set; }
        public int SetupTopFrame { get; set; }
        public string DomainName { get; set; }
        public bool IsEnabled { get; set; }
        public Nullable<System.Guid> LeftFrameDocID { get; set; }
        public Nullable<System.Guid> TopFrameDocID { get; set; }
        public string Bedrnr { get; set; }
        public string SiteTextColour { get; set; }
        public int WSType { get; set; }
        public string TBGColourTopFrame { get; set; }
        public Nullable<System.Guid> TBGImageTopFrame { get; set; }
        public string TabColorTopFrame { get; set; }
        public Nullable<System.Guid> RBGImage { get; set; }
        public string SiteLanguage { get; set; }
        public string LeftFontSize { get; set; }
        public string LeftFontFace { get; set; }
        public string TextAlignment { get; set; }
        public string ItemSearchType { get; set; }
        public byte SearchRequest { get; set; }
        public byte SearchItems { get; set; }
        public byte SearchDocuments { get; set; }
        public byte SearchAccounts { get; set; }
        public byte SearchProject { get; set; }
        public string Classification { get; set; }
        public string Sector { get; set; }
        public string MetatagKeyword { get; set; }
        public Nullable<short> Division { get; set; }
    }
}
