//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class XBRLTextBlockMappings
    {
        public System.Guid ID { get; set; }
        public int Division { get; set; }
        public System.Guid TextBlockGroup { get; set; }
        public System.Guid Element { get; set; }
        public Nullable<System.Guid> TopicParent { get; set; }
        public Nullable<long> TopicTime { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
        public byte[] timestamp { get; set; }
    }
}
