//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class XBRLTextBlocks
    {
        public int HID { get; set; }
        public System.Guid ID { get; set; }
        public int Division { get; set; }
        public Nullable<System.Guid> TextBlockGroup { get; set; }
        public string Code { get; set; }
        public string TextValue { get; set; }
        public bool Main { get; set; }
        public System.DateTime syscreated { get; set; }
        public int syscreator { get; set; }
        public System.DateTime sysmodified { get; set; }
        public int sysmodifier { get; set; }
    }
}
