//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class XMLFiles
    {
        public string Name { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<short> Division { get; set; }
    }
}
