//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class XMLGLTransactionsLog
    {
        public System.Guid ID { get; set; }
        public string CompanyCode { get; set; }
        public int HumresID { get; set; }
        public System.DateTime ImportDate { get; set; }
        public System.Guid EntryGuid { get; set; }
        public string Status { get; set; }
        public Nullable<short> Division { get; set; }
    }
}
